// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/rechargebonusparticipation"
)

// RechargeBonusParticipation is the model entity for the RechargeBonusParticipation schema.
type RechargeBonusParticipation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CampaignID holds the value of the "campaign_id" field.
	CampaignID int64 `json:"campaign_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// CompletedCount holds the value of the "completed_count" field.
	CompletedCount int `json:"completed_count,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RechargeBonusParticipation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rechargebonusparticipation.FieldID, rechargebonusparticipation.FieldCampaignID, rechargebonusparticipation.FieldUserID, rechargebonusparticipation.FieldCompletedCount:
			values[i] = new(sql.NullInt64)
		case rechargebonusparticipation.FieldCreatedAt, rechargebonusparticipation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RechargeBonusParticipation fields.
func (_m *RechargeBonusParticipation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rechargebonusparticipation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case rechargebonusparticipation.FieldCampaignID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field campaign_id", values[i])
			} else if value.Valid {
				_m.CampaignID = value.Int64
			}
		case rechargebonusparticipation.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case rechargebonusparticipation.FieldCompletedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field completed_count", values[i])
			} else if value.Valid {
				_m.CompletedCount = int(value.Int64)
			}
		case rechargebonusparticipation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rechargebonusparticipation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RechargeBonusParticipation.
// This includes values selected through modifiers, order, etc.
func (_m *RechargeBonusParticipation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RechargeBonusParticipation.
// Note that you need to call RechargeBonusParticipation.Unwrap() before calling this method if this RechargeBonusParticipation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RechargeBonusParticipation) Update() *RechargeBonusParticipationUpdateOne {
	return NewRechargeBonusParticipationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RechargeBonusParticipation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RechargeBonusParticipation) Unwrap() *RechargeBonusParticipation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RechargeBonusParticipation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RechargeBonusParticipation) String() string {
	var builder strings.Builder
	builder.WriteString("RechargeBonusParticipation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("campaign_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CampaignID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("completed_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompletedCount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RechargeBonusParticipations is a parsable slice of RechargeBonusParticipation.
type RechargeBonusParticipations []*RechargeBonusParticipation
