// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/recurringcreditbatch"
)

// RecurringCreditBatchUpdate is the builder for updating RecurringCreditBatch entities.
type RecurringCreditBatchUpdate struct {
	config
	hooks    []Hook
	mutation *RecurringCreditBatchMutation
}

// Where appends a list predicates to the RecurringCreditBatchUpdate builder.
func (_u *RecurringCreditBatchUpdate) Where(ps ...predicate.RecurringCreditBatch) *RecurringCreditBatchUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *RecurringCreditBatchUpdate) SetTaskID(v int64) *RecurringCreditBatchUpdate {
	_u.mutation.ResetTaskID()
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableTaskID(v *int64) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// AddTaskID adds value to the "task_id" field.
func (_u *RecurringCreditBatchUpdate) AddTaskID(v int64) *RecurringCreditBatchUpdate {
	_u.mutation.AddTaskID(v)
	return _u
}

// SetTaskName sets the "task_name" field.
func (_u *RecurringCreditBatchUpdate) SetTaskName(v string) *RecurringCreditBatchUpdate {
	_u.mutation.SetTaskName(v)
	return _u
}

// SetNillableTaskName sets the "task_name" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableTaskName(v *string) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetTaskName(*v)
	}
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *RecurringCreditBatchUpdate) SetScheduledAt(v time.Time) *RecurringCreditBatchUpdate {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableScheduledAt(v *time.Time) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RecurringCreditBatchUpdate) SetExpiresAt(v time.Time) *RecurringCreditBatchUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableExpiresAt(v *time.Time) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetQualificationStart sets the "qualification_start" field.
func (_u *RecurringCreditBatchUpdate) SetQualificationStart(v time.Time) *RecurringCreditBatchUpdate {
	_u.mutation.SetQualificationStart(v)
	return _u
}

// SetNillableQualificationStart sets the "qualification_start" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableQualificationStart(v *time.Time) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetQualificationStart(*v)
	}
	return _u
}

// SetQualificationEnd sets the "qualification_end" field.
func (_u *RecurringCreditBatchUpdate) SetQualificationEnd(v time.Time) *RecurringCreditBatchUpdate {
	_u.mutation.SetQualificationEnd(v)
	return _u
}

// SetNillableQualificationEnd sets the "qualification_end" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableQualificationEnd(v *time.Time) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetQualificationEnd(*v)
	}
	return _u
}

// SetQualificationCutoffAt sets the "qualification_cutoff_at" field.
func (_u *RecurringCreditBatchUpdate) SetQualificationCutoffAt(v time.Time) *RecurringCreditBatchUpdate {
	_u.mutation.SetQualificationCutoffAt(v)
	return _u
}

// SetNillableQualificationCutoffAt sets the "qualification_cutoff_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableQualificationCutoffAt(v *time.Time) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetQualificationCutoffAt(*v)
	}
	return _u
}

// ClearQualificationCutoffAt clears the value of the "qualification_cutoff_at" field.
func (_u *RecurringCreditBatchUpdate) ClearQualificationCutoffAt() *RecurringCreditBatchUpdate {
	_u.mutation.ClearQualificationCutoffAt()
	return _u
}

// SetConfigVersion sets the "config_version" field.
func (_u *RecurringCreditBatchUpdate) SetConfigVersion(v int) *RecurringCreditBatchUpdate {
	_u.mutation.ResetConfigVersion()
	_u.mutation.SetConfigVersion(v)
	return _u
}

// SetNillableConfigVersion sets the "config_version" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableConfigVersion(v *int) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetConfigVersion(*v)
	}
	return _u
}

// AddConfigVersion adds value to the "config_version" field.
func (_u *RecurringCreditBatchUpdate) AddConfigVersion(v int) *RecurringCreditBatchUpdate {
	_u.mutation.AddConfigVersion(v)
	return _u
}

// SetEligibilityPolicy sets the "eligibility_policy" field.
func (_u *RecurringCreditBatchUpdate) SetEligibilityPolicy(v string) *RecurringCreditBatchUpdate {
	_u.mutation.SetEligibilityPolicy(v)
	return _u
}

// SetNillableEligibilityPolicy sets the "eligibility_policy" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableEligibilityPolicy(v *string) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetEligibilityPolicy(*v)
	}
	return _u
}

// SetScheduleType sets the "schedule_type" field.
func (_u *RecurringCreditBatchUpdate) SetScheduleType(v string) *RecurringCreditBatchUpdate {
	_u.mutation.SetScheduleType(v)
	return _u
}

// SetNillableScheduleType sets the "schedule_type" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableScheduleType(v *string) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetScheduleType(*v)
	}
	return _u
}

// SetDayOfMonth sets the "day_of_month" field.
func (_u *RecurringCreditBatchUpdate) SetDayOfMonth(v int) *RecurringCreditBatchUpdate {
	_u.mutation.ResetDayOfMonth()
	_u.mutation.SetDayOfMonth(v)
	return _u
}

// SetNillableDayOfMonth sets the "day_of_month" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableDayOfMonth(v *int) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetDayOfMonth(*v)
	}
	return _u
}

// AddDayOfMonth adds value to the "day_of_month" field.
func (_u *RecurringCreditBatchUpdate) AddDayOfMonth(v int) *RecurringCreditBatchUpdate {
	_u.mutation.AddDayOfMonth(v)
	return _u
}

// ClearDayOfMonth clears the value of the "day_of_month" field.
func (_u *RecurringCreditBatchUpdate) ClearDayOfMonth() *RecurringCreditBatchUpdate {
	_u.mutation.ClearDayOfMonth()
	return _u
}

// SetDayOfWeek sets the "day_of_week" field.
func (_u *RecurringCreditBatchUpdate) SetDayOfWeek(v int) *RecurringCreditBatchUpdate {
	_u.mutation.ResetDayOfWeek()
	_u.mutation.SetDayOfWeek(v)
	return _u
}

// SetNillableDayOfWeek sets the "day_of_week" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableDayOfWeek(v *int) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetDayOfWeek(*v)
	}
	return _u
}

// AddDayOfWeek adds value to the "day_of_week" field.
func (_u *RecurringCreditBatchUpdate) AddDayOfWeek(v int) *RecurringCreditBatchUpdate {
	_u.mutation.AddDayOfWeek(v)
	return _u
}

// ClearDayOfWeek clears the value of the "day_of_week" field.
func (_u *RecurringCreditBatchUpdate) ClearDayOfWeek() *RecurringCreditBatchUpdate {
	_u.mutation.ClearDayOfWeek()
	return _u
}

// SetLocalTime sets the "local_time" field.
func (_u *RecurringCreditBatchUpdate) SetLocalTime(v string) *RecurringCreditBatchUpdate {
	_u.mutation.SetLocalTime(v)
	return _u
}

// SetNillableLocalTime sets the "local_time" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableLocalTime(v *string) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetLocalTime(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *RecurringCreditBatchUpdate) SetTimezone(v string) *RecurringCreditBatchUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableTimezone(v *string) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RecurringCreditBatchUpdate) SetAmount(v float64) *RecurringCreditBatchUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableAmount(v *float64) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RecurringCreditBatchUpdate) AddAmount(v float64) *RecurringCreditBatchUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *RecurringCreditBatchUpdate) SetValidityDays(v int) *RecurringCreditBatchUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableValidityDays(v *int) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *RecurringCreditBatchUpdate) AddValidityDays(v int) *RecurringCreditBatchUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// ClearValidityDays clears the value of the "validity_days" field.
func (_u *RecurringCreditBatchUpdate) ClearValidityDays() *RecurringCreditBatchUpdate {
	_u.mutation.ClearValidityDays()
	return _u
}

// SetExecutionMode sets the "execution_mode" field.
func (_u *RecurringCreditBatchUpdate) SetExecutionMode(v string) *RecurringCreditBatchUpdate {
	_u.mutation.SetExecutionMode(v)
	return _u
}

// SetNillableExecutionMode sets the "execution_mode" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableExecutionMode(v *string) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetExecutionMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RecurringCreditBatchUpdate) SetStatus(v string) *RecurringCreditBatchUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableStatus(v *string) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *RecurringCreditBatchUpdate) SetClaimedAt(v time.Time) *RecurringCreditBatchUpdate {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableClaimedAt(v *time.Time) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (_u *RecurringCreditBatchUpdate) ClearClaimedAt() *RecurringCreditBatchUpdate {
	_u.mutation.ClearClaimedAt()
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *RecurringCreditBatchUpdate) SetLeaseOwner(v string) *RecurringCreditBatchUpdate {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableLeaseOwner(v *string) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *RecurringCreditBatchUpdate) SetLeaseExpiresAt(v time.Time) *RecurringCreditBatchUpdate {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableLeaseExpiresAt(v *time.Time) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (_u *RecurringCreditBatchUpdate) ClearLeaseExpiresAt() *RecurringCreditBatchUpdate {
	_u.mutation.ClearLeaseExpiresAt()
	return _u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_u *RecurringCreditBatchUpdate) SetHeartbeatAt(v time.Time) *RecurringCreditBatchUpdate {
	_u.mutation.SetHeartbeatAt(v)
	return _u
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableHeartbeatAt(v *time.Time) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetHeartbeatAt(*v)
	}
	return _u
}

// ClearHeartbeatAt clears the value of the "heartbeat_at" field.
func (_u *RecurringCreditBatchUpdate) ClearHeartbeatAt() *RecurringCreditBatchUpdate {
	_u.mutation.ClearHeartbeatAt()
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *RecurringCreditBatchUpdate) SetAttemptCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableAttemptCount(v *int) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *RecurringCreditBatchUpdate) AddAttemptCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetEligibleUserCount sets the "eligible_user_count" field.
func (_u *RecurringCreditBatchUpdate) SetEligibleUserCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.ResetEligibleUserCount()
	_u.mutation.SetEligibleUserCount(v)
	return _u
}

// SetNillableEligibleUserCount sets the "eligible_user_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableEligibleUserCount(v *int) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetEligibleUserCount(*v)
	}
	return _u
}

// AddEligibleUserCount adds value to the "eligible_user_count" field.
func (_u *RecurringCreditBatchUpdate) AddEligibleUserCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.AddEligibleUserCount(v)
	return _u
}

// SetIssuedUserCount sets the "issued_user_count" field.
func (_u *RecurringCreditBatchUpdate) SetIssuedUserCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.ResetIssuedUserCount()
	_u.mutation.SetIssuedUserCount(v)
	return _u
}

// SetNillableIssuedUserCount sets the "issued_user_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableIssuedUserCount(v *int) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetIssuedUserCount(*v)
	}
	return _u
}

// AddIssuedUserCount adds value to the "issued_user_count" field.
func (_u *RecurringCreditBatchUpdate) AddIssuedUserCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.AddIssuedUserCount(v)
	return _u
}

// SetExcludedUserCount sets the "excluded_user_count" field.
func (_u *RecurringCreditBatchUpdate) SetExcludedUserCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.ResetExcludedUserCount()
	_u.mutation.SetExcludedUserCount(v)
	return _u
}

// SetNillableExcludedUserCount sets the "excluded_user_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableExcludedUserCount(v *int) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetExcludedUserCount(*v)
	}
	return _u
}

// AddExcludedUserCount adds value to the "excluded_user_count" field.
func (_u *RecurringCreditBatchUpdate) AddExcludedUserCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.AddExcludedUserCount(v)
	return _u
}

// SetUsageEligibleCount sets the "usage_eligible_count" field.
func (_u *RecurringCreditBatchUpdate) SetUsageEligibleCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.ResetUsageEligibleCount()
	_u.mutation.SetUsageEligibleCount(v)
	return _u
}

// SetNillableUsageEligibleCount sets the "usage_eligible_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableUsageEligibleCount(v *int) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetUsageEligibleCount(*v)
	}
	return _u
}

// AddUsageEligibleCount adds value to the "usage_eligible_count" field.
func (_u *RecurringCreditBatchUpdate) AddUsageEligibleCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.AddUsageEligibleCount(v)
	return _u
}

// SetRechargeEligibleCount sets the "recharge_eligible_count" field.
func (_u *RecurringCreditBatchUpdate) SetRechargeEligibleCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.ResetRechargeEligibleCount()
	_u.mutation.SetRechargeEligibleCount(v)
	return _u
}

// SetNillableRechargeEligibleCount sets the "recharge_eligible_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableRechargeEligibleCount(v *int) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetRechargeEligibleCount(*v)
	}
	return _u
}

// AddRechargeEligibleCount adds value to the "recharge_eligible_count" field.
func (_u *RecurringCreditBatchUpdate) AddRechargeEligibleCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.AddRechargeEligibleCount(v)
	return _u
}

// SetAPIActiveCount sets the "api_active_count" field.
func (_u *RecurringCreditBatchUpdate) SetAPIActiveCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.ResetAPIActiveCount()
	_u.mutation.SetAPIActiveCount(v)
	return _u
}

// SetNillableAPIActiveCount sets the "api_active_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableAPIActiveCount(v *int) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetAPIActiveCount(*v)
	}
	return _u
}

// AddAPIActiveCount adds value to the "api_active_count" field.
func (_u *RecurringCreditBatchUpdate) AddAPIActiveCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.AddAPIActiveCount(v)
	return _u
}

// SetSiteActiveCount sets the "site_active_count" field.
func (_u *RecurringCreditBatchUpdate) SetSiteActiveCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.ResetSiteActiveCount()
	_u.mutation.SetSiteActiveCount(v)
	return _u
}

// SetNillableSiteActiveCount sets the "site_active_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableSiteActiveCount(v *int) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetSiteActiveCount(*v)
	}
	return _u
}

// AddSiteActiveCount adds value to the "site_active_count" field.
func (_u *RecurringCreditBatchUpdate) AddSiteActiveCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.AddSiteActiveCount(v)
	return _u
}

// SetBothActiveCount sets the "both_active_count" field.
func (_u *RecurringCreditBatchUpdate) SetBothActiveCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.ResetBothActiveCount()
	_u.mutation.SetBothActiveCount(v)
	return _u
}

// SetNillableBothActiveCount sets the "both_active_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableBothActiveCount(v *int) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetBothActiveCount(*v)
	}
	return _u
}

// AddBothActiveCount adds value to the "both_active_count" field.
func (_u *RecurringCreditBatchUpdate) AddBothActiveCount(v int) *RecurringCreditBatchUpdate {
	_u.mutation.AddBothActiveCount(v)
	return _u
}

// SetSnapshotCompletedAt sets the "snapshot_completed_at" field.
func (_u *RecurringCreditBatchUpdate) SetSnapshotCompletedAt(v time.Time) *RecurringCreditBatchUpdate {
	_u.mutation.SetSnapshotCompletedAt(v)
	return _u
}

// SetNillableSnapshotCompletedAt sets the "snapshot_completed_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableSnapshotCompletedAt(v *time.Time) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetSnapshotCompletedAt(*v)
	}
	return _u
}

// ClearSnapshotCompletedAt clears the value of the "snapshot_completed_at" field.
func (_u *RecurringCreditBatchUpdate) ClearSnapshotCompletedAt() *RecurringCreditBatchUpdate {
	_u.mutation.ClearSnapshotCompletedAt()
	return _u
}

// SetIssuedAmount sets the "issued_amount" field.
func (_u *RecurringCreditBatchUpdate) SetIssuedAmount(v float64) *RecurringCreditBatchUpdate {
	_u.mutation.ResetIssuedAmount()
	_u.mutation.SetIssuedAmount(v)
	return _u
}

// SetNillableIssuedAmount sets the "issued_amount" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableIssuedAmount(v *float64) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetIssuedAmount(*v)
	}
	return _u
}

// AddIssuedAmount adds value to the "issued_amount" field.
func (_u *RecurringCreditBatchUpdate) AddIssuedAmount(v float64) *RecurringCreditBatchUpdate {
	_u.mutation.AddIssuedAmount(v)
	return _u
}

// SetFailureCode sets the "failure_code" field.
func (_u *RecurringCreditBatchUpdate) SetFailureCode(v string) *RecurringCreditBatchUpdate {
	_u.mutation.SetFailureCode(v)
	return _u
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableFailureCode(v *string) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetFailureCode(*v)
	}
	return _u
}

// SetFailureMessage sets the "failure_message" field.
func (_u *RecurringCreditBatchUpdate) SetFailureMessage(v string) *RecurringCreditBatchUpdate {
	_u.mutation.SetFailureMessage(v)
	return _u
}

// SetNillableFailureMessage sets the "failure_message" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableFailureMessage(v *string) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetFailureMessage(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *RecurringCreditBatchUpdate) SetFinishedAt(v time.Time) *RecurringCreditBatchUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdate) SetNillableFinishedAt(v *time.Time) *RecurringCreditBatchUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *RecurringCreditBatchUpdate) ClearFinishedAt() *RecurringCreditBatchUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RecurringCreditBatchUpdate) SetUpdatedAt(v time.Time) *RecurringCreditBatchUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RecurringCreditBatchMutation object of the builder.
func (_u *RecurringCreditBatchUpdate) Mutation() *RecurringCreditBatchMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RecurringCreditBatchUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecurringCreditBatchUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RecurringCreditBatchUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecurringCreditBatchUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RecurringCreditBatchUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := recurringcreditbatch.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecurringCreditBatchUpdate) check() error {
	if v, ok := _u.mutation.TaskName(); ok {
		if err := recurringcreditbatch.TaskNameValidator(v); err != nil {
			return &ValidationError{Name: "task_name", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.task_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EligibilityPolicy(); ok {
		if err := recurringcreditbatch.EligibilityPolicyValidator(v); err != nil {
			return &ValidationError{Name: "eligibility_policy", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.eligibility_policy": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScheduleType(); ok {
		if err := recurringcreditbatch.ScheduleTypeValidator(v); err != nil {
			return &ValidationError{Name: "schedule_type", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.schedule_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LocalTime(); ok {
		if err := recurringcreditbatch.LocalTimeValidator(v); err != nil {
			return &ValidationError{Name: "local_time", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.local_time": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timezone(); ok {
		if err := recurringcreditbatch.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExecutionMode(); ok {
		if err := recurringcreditbatch.ExecutionModeValidator(v); err != nil {
			return &ValidationError{Name: "execution_mode", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.execution_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := recurringcreditbatch.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := recurringcreditbatch.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.lease_owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureCode(); ok {
		if err := recurringcreditbatch.FailureCodeValidator(v); err != nil {
			return &ValidationError{Name: "failure_code", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.failure_code": %w`, err)}
		}
	}
	return nil
}

func (_u *RecurringCreditBatchUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recurringcreditbatch.Table, recurringcreditbatch.Columns, sqlgraph.NewFieldSpec(recurringcreditbatch.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(recurringcreditbatch.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTaskID(); ok {
		_spec.AddField(recurringcreditbatch.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TaskName(); ok {
		_spec.SetField(recurringcreditbatch.FieldTaskName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldScheduledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.QualificationStart(); ok {
		_spec.SetField(recurringcreditbatch.FieldQualificationStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.QualificationEnd(); ok {
		_spec.SetField(recurringcreditbatch.FieldQualificationEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.QualificationCutoffAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldQualificationCutoffAt, field.TypeTime, value)
	}
	if _u.mutation.QualificationCutoffAtCleared() {
		_spec.ClearField(recurringcreditbatch.FieldQualificationCutoffAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConfigVersion(); ok {
		_spec.SetField(recurringcreditbatch.FieldConfigVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConfigVersion(); ok {
		_spec.AddField(recurringcreditbatch.FieldConfigVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EligibilityPolicy(); ok {
		_spec.SetField(recurringcreditbatch.FieldEligibilityPolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScheduleType(); ok {
		_spec.SetField(recurringcreditbatch.FieldScheduleType, field.TypeString, value)
	}
	if value, ok := _u.mutation.DayOfMonth(); ok {
		_spec.SetField(recurringcreditbatch.FieldDayOfMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDayOfMonth(); ok {
		_spec.AddField(recurringcreditbatch.FieldDayOfMonth, field.TypeInt, value)
	}
	if _u.mutation.DayOfMonthCleared() {
		_spec.ClearField(recurringcreditbatch.FieldDayOfMonth, field.TypeInt)
	}
	if value, ok := _u.mutation.DayOfWeek(); ok {
		_spec.SetField(recurringcreditbatch.FieldDayOfWeek, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDayOfWeek(); ok {
		_spec.AddField(recurringcreditbatch.FieldDayOfWeek, field.TypeInt, value)
	}
	if _u.mutation.DayOfWeekCleared() {
		_spec.ClearField(recurringcreditbatch.FieldDayOfWeek, field.TypeInt)
	}
	if value, ok := _u.mutation.LocalTime(); ok {
		_spec.SetField(recurringcreditbatch.FieldLocalTime, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(recurringcreditbatch.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(recurringcreditbatch.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(recurringcreditbatch.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(recurringcreditbatch.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(recurringcreditbatch.FieldValidityDays, field.TypeInt, value)
	}
	if _u.mutation.ValidityDaysCleared() {
		_spec.ClearField(recurringcreditbatch.FieldValidityDays, field.TypeInt)
	}
	if value, ok := _u.mutation.ExecutionMode(); ok {
		_spec.SetField(recurringcreditbatch.FieldExecutionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(recurringcreditbatch.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.ClaimedAtCleared() {
		_spec.ClearField(recurringcreditbatch.FieldClaimedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(recurringcreditbatch.FieldLeaseOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LeaseExpiresAtCleared() {
		_spec.ClearField(recurringcreditbatch.FieldLeaseExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HeartbeatAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldHeartbeatAt, field.TypeTime, value)
	}
	if _u.mutation.HeartbeatAtCleared() {
		_spec.ClearField(recurringcreditbatch.FieldHeartbeatAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EligibleUserCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldEligibleUserCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEligibleUserCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldEligibleUserCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IssuedUserCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldIssuedUserCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIssuedUserCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldIssuedUserCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExcludedUserCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldExcludedUserCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExcludedUserCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldExcludedUserCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsageEligibleCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldUsageEligibleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsageEligibleCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldUsageEligibleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RechargeEligibleCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldRechargeEligibleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRechargeEligibleCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldRechargeEligibleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.APIActiveCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldAPIActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAPIActiveCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldAPIActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SiteActiveCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldSiteActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSiteActiveCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldSiteActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BothActiveCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldBothActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBothActiveCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldBothActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SnapshotCompletedAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldSnapshotCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.SnapshotCompletedAtCleared() {
		_spec.ClearField(recurringcreditbatch.FieldSnapshotCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IssuedAmount(); ok {
		_spec.SetField(recurringcreditbatch.FieldIssuedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedIssuedAmount(); ok {
		_spec.AddField(recurringcreditbatch.FieldIssuedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FailureCode(); ok {
		_spec.SetField(recurringcreditbatch.FieldFailureCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureMessage(); ok {
		_spec.SetField(recurringcreditbatch.FieldFailureMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(recurringcreditbatch.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recurringcreditbatch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RecurringCreditBatchUpdateOne is the builder for updating a single RecurringCreditBatch entity.
type RecurringCreditBatchUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecurringCreditBatchMutation
}

// SetTaskID sets the "task_id" field.
func (_u *RecurringCreditBatchUpdateOne) SetTaskID(v int64) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetTaskID()
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableTaskID(v *int64) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// AddTaskID adds value to the "task_id" field.
func (_u *RecurringCreditBatchUpdateOne) AddTaskID(v int64) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddTaskID(v)
	return _u
}

// SetTaskName sets the "task_name" field.
func (_u *RecurringCreditBatchUpdateOne) SetTaskName(v string) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetTaskName(v)
	return _u
}

// SetNillableTaskName sets the "task_name" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableTaskName(v *string) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetTaskName(*v)
	}
	return _u
}

// SetScheduledAt sets the "scheduled_at" field.
func (_u *RecurringCreditBatchUpdateOne) SetScheduledAt(v time.Time) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetScheduledAt(v)
	return _u
}

// SetNillableScheduledAt sets the "scheduled_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableScheduledAt(v *time.Time) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetScheduledAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RecurringCreditBatchUpdateOne) SetExpiresAt(v time.Time) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableExpiresAt(v *time.Time) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetQualificationStart sets the "qualification_start" field.
func (_u *RecurringCreditBatchUpdateOne) SetQualificationStart(v time.Time) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetQualificationStart(v)
	return _u
}

// SetNillableQualificationStart sets the "qualification_start" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableQualificationStart(v *time.Time) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetQualificationStart(*v)
	}
	return _u
}

// SetQualificationEnd sets the "qualification_end" field.
func (_u *RecurringCreditBatchUpdateOne) SetQualificationEnd(v time.Time) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetQualificationEnd(v)
	return _u
}

// SetNillableQualificationEnd sets the "qualification_end" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableQualificationEnd(v *time.Time) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetQualificationEnd(*v)
	}
	return _u
}

// SetQualificationCutoffAt sets the "qualification_cutoff_at" field.
func (_u *RecurringCreditBatchUpdateOne) SetQualificationCutoffAt(v time.Time) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetQualificationCutoffAt(v)
	return _u
}

// SetNillableQualificationCutoffAt sets the "qualification_cutoff_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableQualificationCutoffAt(v *time.Time) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetQualificationCutoffAt(*v)
	}
	return _u
}

// ClearQualificationCutoffAt clears the value of the "qualification_cutoff_at" field.
func (_u *RecurringCreditBatchUpdateOne) ClearQualificationCutoffAt() *RecurringCreditBatchUpdateOne {
	_u.mutation.ClearQualificationCutoffAt()
	return _u
}

// SetConfigVersion sets the "config_version" field.
func (_u *RecurringCreditBatchUpdateOne) SetConfigVersion(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetConfigVersion()
	_u.mutation.SetConfigVersion(v)
	return _u
}

// SetNillableConfigVersion sets the "config_version" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableConfigVersion(v *int) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetConfigVersion(*v)
	}
	return _u
}

// AddConfigVersion adds value to the "config_version" field.
func (_u *RecurringCreditBatchUpdateOne) AddConfigVersion(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddConfigVersion(v)
	return _u
}

// SetEligibilityPolicy sets the "eligibility_policy" field.
func (_u *RecurringCreditBatchUpdateOne) SetEligibilityPolicy(v string) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetEligibilityPolicy(v)
	return _u
}

// SetNillableEligibilityPolicy sets the "eligibility_policy" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableEligibilityPolicy(v *string) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetEligibilityPolicy(*v)
	}
	return _u
}

// SetScheduleType sets the "schedule_type" field.
func (_u *RecurringCreditBatchUpdateOne) SetScheduleType(v string) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetScheduleType(v)
	return _u
}

// SetNillableScheduleType sets the "schedule_type" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableScheduleType(v *string) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetScheduleType(*v)
	}
	return _u
}

// SetDayOfMonth sets the "day_of_month" field.
func (_u *RecurringCreditBatchUpdateOne) SetDayOfMonth(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetDayOfMonth()
	_u.mutation.SetDayOfMonth(v)
	return _u
}

// SetNillableDayOfMonth sets the "day_of_month" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableDayOfMonth(v *int) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetDayOfMonth(*v)
	}
	return _u
}

// AddDayOfMonth adds value to the "day_of_month" field.
func (_u *RecurringCreditBatchUpdateOne) AddDayOfMonth(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddDayOfMonth(v)
	return _u
}

// ClearDayOfMonth clears the value of the "day_of_month" field.
func (_u *RecurringCreditBatchUpdateOne) ClearDayOfMonth() *RecurringCreditBatchUpdateOne {
	_u.mutation.ClearDayOfMonth()
	return _u
}

// SetDayOfWeek sets the "day_of_week" field.
func (_u *RecurringCreditBatchUpdateOne) SetDayOfWeek(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetDayOfWeek()
	_u.mutation.SetDayOfWeek(v)
	return _u
}

// SetNillableDayOfWeek sets the "day_of_week" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableDayOfWeek(v *int) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetDayOfWeek(*v)
	}
	return _u
}

// AddDayOfWeek adds value to the "day_of_week" field.
func (_u *RecurringCreditBatchUpdateOne) AddDayOfWeek(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddDayOfWeek(v)
	return _u
}

// ClearDayOfWeek clears the value of the "day_of_week" field.
func (_u *RecurringCreditBatchUpdateOne) ClearDayOfWeek() *RecurringCreditBatchUpdateOne {
	_u.mutation.ClearDayOfWeek()
	return _u
}

// SetLocalTime sets the "local_time" field.
func (_u *RecurringCreditBatchUpdateOne) SetLocalTime(v string) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetLocalTime(v)
	return _u
}

// SetNillableLocalTime sets the "local_time" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableLocalTime(v *string) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetLocalTime(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *RecurringCreditBatchUpdateOne) SetTimezone(v string) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableTimezone(v *string) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RecurringCreditBatchUpdateOne) SetAmount(v float64) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableAmount(v *float64) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RecurringCreditBatchUpdateOne) AddAmount(v float64) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *RecurringCreditBatchUpdateOne) SetValidityDays(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableValidityDays(v *int) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *RecurringCreditBatchUpdateOne) AddValidityDays(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// ClearValidityDays clears the value of the "validity_days" field.
func (_u *RecurringCreditBatchUpdateOne) ClearValidityDays() *RecurringCreditBatchUpdateOne {
	_u.mutation.ClearValidityDays()
	return _u
}

// SetExecutionMode sets the "execution_mode" field.
func (_u *RecurringCreditBatchUpdateOne) SetExecutionMode(v string) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetExecutionMode(v)
	return _u
}

// SetNillableExecutionMode sets the "execution_mode" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableExecutionMode(v *string) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetExecutionMode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RecurringCreditBatchUpdateOne) SetStatus(v string) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableStatus(v *string) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetClaimedAt sets the "claimed_at" field.
func (_u *RecurringCreditBatchUpdateOne) SetClaimedAt(v time.Time) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetClaimedAt(v)
	return _u
}

// SetNillableClaimedAt sets the "claimed_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableClaimedAt(v *time.Time) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetClaimedAt(*v)
	}
	return _u
}

// ClearClaimedAt clears the value of the "claimed_at" field.
func (_u *RecurringCreditBatchUpdateOne) ClearClaimedAt() *RecurringCreditBatchUpdateOne {
	_u.mutation.ClearClaimedAt()
	return _u
}

// SetLeaseOwner sets the "lease_owner" field.
func (_u *RecurringCreditBatchUpdateOne) SetLeaseOwner(v string) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetLeaseOwner(v)
	return _u
}

// SetNillableLeaseOwner sets the "lease_owner" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableLeaseOwner(v *string) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetLeaseOwner(*v)
	}
	return _u
}

// SetLeaseExpiresAt sets the "lease_expires_at" field.
func (_u *RecurringCreditBatchUpdateOne) SetLeaseExpiresAt(v time.Time) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetLeaseExpiresAt(v)
	return _u
}

// SetNillableLeaseExpiresAt sets the "lease_expires_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableLeaseExpiresAt(v *time.Time) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetLeaseExpiresAt(*v)
	}
	return _u
}

// ClearLeaseExpiresAt clears the value of the "lease_expires_at" field.
func (_u *RecurringCreditBatchUpdateOne) ClearLeaseExpiresAt() *RecurringCreditBatchUpdateOne {
	_u.mutation.ClearLeaseExpiresAt()
	return _u
}

// SetHeartbeatAt sets the "heartbeat_at" field.
func (_u *RecurringCreditBatchUpdateOne) SetHeartbeatAt(v time.Time) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetHeartbeatAt(v)
	return _u
}

// SetNillableHeartbeatAt sets the "heartbeat_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableHeartbeatAt(v *time.Time) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetHeartbeatAt(*v)
	}
	return _u
}

// ClearHeartbeatAt clears the value of the "heartbeat_at" field.
func (_u *RecurringCreditBatchUpdateOne) ClearHeartbeatAt() *RecurringCreditBatchUpdateOne {
	_u.mutation.ClearHeartbeatAt()
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *RecurringCreditBatchUpdateOne) SetAttemptCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableAttemptCount(v *int) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *RecurringCreditBatchUpdateOne) AddAttemptCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetEligibleUserCount sets the "eligible_user_count" field.
func (_u *RecurringCreditBatchUpdateOne) SetEligibleUserCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetEligibleUserCount()
	_u.mutation.SetEligibleUserCount(v)
	return _u
}

// SetNillableEligibleUserCount sets the "eligible_user_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableEligibleUserCount(v *int) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetEligibleUserCount(*v)
	}
	return _u
}

// AddEligibleUserCount adds value to the "eligible_user_count" field.
func (_u *RecurringCreditBatchUpdateOne) AddEligibleUserCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddEligibleUserCount(v)
	return _u
}

// SetIssuedUserCount sets the "issued_user_count" field.
func (_u *RecurringCreditBatchUpdateOne) SetIssuedUserCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetIssuedUserCount()
	_u.mutation.SetIssuedUserCount(v)
	return _u
}

// SetNillableIssuedUserCount sets the "issued_user_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableIssuedUserCount(v *int) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetIssuedUserCount(*v)
	}
	return _u
}

// AddIssuedUserCount adds value to the "issued_user_count" field.
func (_u *RecurringCreditBatchUpdateOne) AddIssuedUserCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddIssuedUserCount(v)
	return _u
}

// SetExcludedUserCount sets the "excluded_user_count" field.
func (_u *RecurringCreditBatchUpdateOne) SetExcludedUserCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetExcludedUserCount()
	_u.mutation.SetExcludedUserCount(v)
	return _u
}

// SetNillableExcludedUserCount sets the "excluded_user_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableExcludedUserCount(v *int) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetExcludedUserCount(*v)
	}
	return _u
}

// AddExcludedUserCount adds value to the "excluded_user_count" field.
func (_u *RecurringCreditBatchUpdateOne) AddExcludedUserCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddExcludedUserCount(v)
	return _u
}

// SetUsageEligibleCount sets the "usage_eligible_count" field.
func (_u *RecurringCreditBatchUpdateOne) SetUsageEligibleCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetUsageEligibleCount()
	_u.mutation.SetUsageEligibleCount(v)
	return _u
}

// SetNillableUsageEligibleCount sets the "usage_eligible_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableUsageEligibleCount(v *int) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetUsageEligibleCount(*v)
	}
	return _u
}

// AddUsageEligibleCount adds value to the "usage_eligible_count" field.
func (_u *RecurringCreditBatchUpdateOne) AddUsageEligibleCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddUsageEligibleCount(v)
	return _u
}

// SetRechargeEligibleCount sets the "recharge_eligible_count" field.
func (_u *RecurringCreditBatchUpdateOne) SetRechargeEligibleCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetRechargeEligibleCount()
	_u.mutation.SetRechargeEligibleCount(v)
	return _u
}

// SetNillableRechargeEligibleCount sets the "recharge_eligible_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableRechargeEligibleCount(v *int) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetRechargeEligibleCount(*v)
	}
	return _u
}

// AddRechargeEligibleCount adds value to the "recharge_eligible_count" field.
func (_u *RecurringCreditBatchUpdateOne) AddRechargeEligibleCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddRechargeEligibleCount(v)
	return _u
}

// SetAPIActiveCount sets the "api_active_count" field.
func (_u *RecurringCreditBatchUpdateOne) SetAPIActiveCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetAPIActiveCount()
	_u.mutation.SetAPIActiveCount(v)
	return _u
}

// SetNillableAPIActiveCount sets the "api_active_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableAPIActiveCount(v *int) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetAPIActiveCount(*v)
	}
	return _u
}

// AddAPIActiveCount adds value to the "api_active_count" field.
func (_u *RecurringCreditBatchUpdateOne) AddAPIActiveCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddAPIActiveCount(v)
	return _u
}

// SetSiteActiveCount sets the "site_active_count" field.
func (_u *RecurringCreditBatchUpdateOne) SetSiteActiveCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetSiteActiveCount()
	_u.mutation.SetSiteActiveCount(v)
	return _u
}

// SetNillableSiteActiveCount sets the "site_active_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableSiteActiveCount(v *int) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetSiteActiveCount(*v)
	}
	return _u
}

// AddSiteActiveCount adds value to the "site_active_count" field.
func (_u *RecurringCreditBatchUpdateOne) AddSiteActiveCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddSiteActiveCount(v)
	return _u
}

// SetBothActiveCount sets the "both_active_count" field.
func (_u *RecurringCreditBatchUpdateOne) SetBothActiveCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetBothActiveCount()
	_u.mutation.SetBothActiveCount(v)
	return _u
}

// SetNillableBothActiveCount sets the "both_active_count" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableBothActiveCount(v *int) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetBothActiveCount(*v)
	}
	return _u
}

// AddBothActiveCount adds value to the "both_active_count" field.
func (_u *RecurringCreditBatchUpdateOne) AddBothActiveCount(v int) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddBothActiveCount(v)
	return _u
}

// SetSnapshotCompletedAt sets the "snapshot_completed_at" field.
func (_u *RecurringCreditBatchUpdateOne) SetSnapshotCompletedAt(v time.Time) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetSnapshotCompletedAt(v)
	return _u
}

// SetNillableSnapshotCompletedAt sets the "snapshot_completed_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableSnapshotCompletedAt(v *time.Time) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetSnapshotCompletedAt(*v)
	}
	return _u
}

// ClearSnapshotCompletedAt clears the value of the "snapshot_completed_at" field.
func (_u *RecurringCreditBatchUpdateOne) ClearSnapshotCompletedAt() *RecurringCreditBatchUpdateOne {
	_u.mutation.ClearSnapshotCompletedAt()
	return _u
}

// SetIssuedAmount sets the "issued_amount" field.
func (_u *RecurringCreditBatchUpdateOne) SetIssuedAmount(v float64) *RecurringCreditBatchUpdateOne {
	_u.mutation.ResetIssuedAmount()
	_u.mutation.SetIssuedAmount(v)
	return _u
}

// SetNillableIssuedAmount sets the "issued_amount" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableIssuedAmount(v *float64) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetIssuedAmount(*v)
	}
	return _u
}

// AddIssuedAmount adds value to the "issued_amount" field.
func (_u *RecurringCreditBatchUpdateOne) AddIssuedAmount(v float64) *RecurringCreditBatchUpdateOne {
	_u.mutation.AddIssuedAmount(v)
	return _u
}

// SetFailureCode sets the "failure_code" field.
func (_u *RecurringCreditBatchUpdateOne) SetFailureCode(v string) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetFailureCode(v)
	return _u
}

// SetNillableFailureCode sets the "failure_code" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableFailureCode(v *string) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetFailureCode(*v)
	}
	return _u
}

// SetFailureMessage sets the "failure_message" field.
func (_u *RecurringCreditBatchUpdateOne) SetFailureMessage(v string) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetFailureMessage(v)
	return _u
}

// SetNillableFailureMessage sets the "failure_message" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableFailureMessage(v *string) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetFailureMessage(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *RecurringCreditBatchUpdateOne) SetFinishedAt(v time.Time) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *RecurringCreditBatchUpdateOne) SetNillableFinishedAt(v *time.Time) *RecurringCreditBatchUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *RecurringCreditBatchUpdateOne) ClearFinishedAt() *RecurringCreditBatchUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RecurringCreditBatchUpdateOne) SetUpdatedAt(v time.Time) *RecurringCreditBatchUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RecurringCreditBatchMutation object of the builder.
func (_u *RecurringCreditBatchUpdateOne) Mutation() *RecurringCreditBatchMutation {
	return _u.mutation
}

// Where appends a list predicates to the RecurringCreditBatchUpdate builder.
func (_u *RecurringCreditBatchUpdateOne) Where(ps ...predicate.RecurringCreditBatch) *RecurringCreditBatchUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RecurringCreditBatchUpdateOne) Select(field string, fields ...string) *RecurringCreditBatchUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RecurringCreditBatch entity.
func (_u *RecurringCreditBatchUpdateOne) Save(ctx context.Context) (*RecurringCreditBatch, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RecurringCreditBatchUpdateOne) SaveX(ctx context.Context) *RecurringCreditBatch {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RecurringCreditBatchUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RecurringCreditBatchUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RecurringCreditBatchUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := recurringcreditbatch.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RecurringCreditBatchUpdateOne) check() error {
	if v, ok := _u.mutation.TaskName(); ok {
		if err := recurringcreditbatch.TaskNameValidator(v); err != nil {
			return &ValidationError{Name: "task_name", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.task_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EligibilityPolicy(); ok {
		if err := recurringcreditbatch.EligibilityPolicyValidator(v); err != nil {
			return &ValidationError{Name: "eligibility_policy", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.eligibility_policy": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScheduleType(); ok {
		if err := recurringcreditbatch.ScheduleTypeValidator(v); err != nil {
			return &ValidationError{Name: "schedule_type", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.schedule_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LocalTime(); ok {
		if err := recurringcreditbatch.LocalTimeValidator(v); err != nil {
			return &ValidationError{Name: "local_time", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.local_time": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timezone(); ok {
		if err := recurringcreditbatch.TimezoneValidator(v); err != nil {
			return &ValidationError{Name: "timezone", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.timezone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExecutionMode(); ok {
		if err := recurringcreditbatch.ExecutionModeValidator(v); err != nil {
			return &ValidationError{Name: "execution_mode", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.execution_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := recurringcreditbatch.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LeaseOwner(); ok {
		if err := recurringcreditbatch.LeaseOwnerValidator(v); err != nil {
			return &ValidationError{Name: "lease_owner", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.lease_owner": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FailureCode(); ok {
		if err := recurringcreditbatch.FailureCodeValidator(v); err != nil {
			return &ValidationError{Name: "failure_code", err: fmt.Errorf(`ent: validator failed for field "RecurringCreditBatch.failure_code": %w`, err)}
		}
	}
	return nil
}

func (_u *RecurringCreditBatchUpdateOne) sqlSave(ctx context.Context) (_node *RecurringCreditBatch, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recurringcreditbatch.Table, recurringcreditbatch.Columns, sqlgraph.NewFieldSpec(recurringcreditbatch.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RecurringCreditBatch.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recurringcreditbatch.FieldID)
		for _, f := range fields {
			if !recurringcreditbatch.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recurringcreditbatch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(recurringcreditbatch.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTaskID(); ok {
		_spec.AddField(recurringcreditbatch.FieldTaskID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TaskName(); ok {
		_spec.SetField(recurringcreditbatch.FieldTaskName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScheduledAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldScheduledAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.QualificationStart(); ok {
		_spec.SetField(recurringcreditbatch.FieldQualificationStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.QualificationEnd(); ok {
		_spec.SetField(recurringcreditbatch.FieldQualificationEnd, field.TypeTime, value)
	}
	if value, ok := _u.mutation.QualificationCutoffAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldQualificationCutoffAt, field.TypeTime, value)
	}
	if _u.mutation.QualificationCutoffAtCleared() {
		_spec.ClearField(recurringcreditbatch.FieldQualificationCutoffAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConfigVersion(); ok {
		_spec.SetField(recurringcreditbatch.FieldConfigVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConfigVersion(); ok {
		_spec.AddField(recurringcreditbatch.FieldConfigVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EligibilityPolicy(); ok {
		_spec.SetField(recurringcreditbatch.FieldEligibilityPolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScheduleType(); ok {
		_spec.SetField(recurringcreditbatch.FieldScheduleType, field.TypeString, value)
	}
	if value, ok := _u.mutation.DayOfMonth(); ok {
		_spec.SetField(recurringcreditbatch.FieldDayOfMonth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDayOfMonth(); ok {
		_spec.AddField(recurringcreditbatch.FieldDayOfMonth, field.TypeInt, value)
	}
	if _u.mutation.DayOfMonthCleared() {
		_spec.ClearField(recurringcreditbatch.FieldDayOfMonth, field.TypeInt)
	}
	if value, ok := _u.mutation.DayOfWeek(); ok {
		_spec.SetField(recurringcreditbatch.FieldDayOfWeek, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDayOfWeek(); ok {
		_spec.AddField(recurringcreditbatch.FieldDayOfWeek, field.TypeInt, value)
	}
	if _u.mutation.DayOfWeekCleared() {
		_spec.ClearField(recurringcreditbatch.FieldDayOfWeek, field.TypeInt)
	}
	if value, ok := _u.mutation.LocalTime(); ok {
		_spec.SetField(recurringcreditbatch.FieldLocalTime, field.TypeString, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(recurringcreditbatch.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(recurringcreditbatch.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(recurringcreditbatch.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(recurringcreditbatch.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(recurringcreditbatch.FieldValidityDays, field.TypeInt, value)
	}
	if _u.mutation.ValidityDaysCleared() {
		_spec.ClearField(recurringcreditbatch.FieldValidityDays, field.TypeInt)
	}
	if value, ok := _u.mutation.ExecutionMode(); ok {
		_spec.SetField(recurringcreditbatch.FieldExecutionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(recurringcreditbatch.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClaimedAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldClaimedAt, field.TypeTime, value)
	}
	if _u.mutation.ClaimedAtCleared() {
		_spec.ClearField(recurringcreditbatch.FieldClaimedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LeaseOwner(); ok {
		_spec.SetField(recurringcreditbatch.FieldLeaseOwner, field.TypeString, value)
	}
	if value, ok := _u.mutation.LeaseExpiresAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldLeaseExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LeaseExpiresAtCleared() {
		_spec.ClearField(recurringcreditbatch.FieldLeaseExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HeartbeatAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldHeartbeatAt, field.TypeTime, value)
	}
	if _u.mutation.HeartbeatAtCleared() {
		_spec.ClearField(recurringcreditbatch.FieldHeartbeatAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.EligibleUserCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldEligibleUserCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEligibleUserCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldEligibleUserCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IssuedUserCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldIssuedUserCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIssuedUserCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldIssuedUserCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExcludedUserCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldExcludedUserCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExcludedUserCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldExcludedUserCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UsageEligibleCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldUsageEligibleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUsageEligibleCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldUsageEligibleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RechargeEligibleCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldRechargeEligibleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRechargeEligibleCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldRechargeEligibleCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.APIActiveCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldAPIActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAPIActiveCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldAPIActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SiteActiveCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldSiteActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSiteActiveCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldSiteActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BothActiveCount(); ok {
		_spec.SetField(recurringcreditbatch.FieldBothActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBothActiveCount(); ok {
		_spec.AddField(recurringcreditbatch.FieldBothActiveCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SnapshotCompletedAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldSnapshotCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.SnapshotCompletedAtCleared() {
		_spec.ClearField(recurringcreditbatch.FieldSnapshotCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.IssuedAmount(); ok {
		_spec.SetField(recurringcreditbatch.FieldIssuedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedIssuedAmount(); ok {
		_spec.AddField(recurringcreditbatch.FieldIssuedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.FailureCode(); ok {
		_spec.SetField(recurringcreditbatch.FieldFailureCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.FailureMessage(); ok {
		_spec.SetField(recurringcreditbatch.FieldFailureMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(recurringcreditbatch.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(recurringcreditbatch.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &RecurringCreditBatch{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recurringcreditbatch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
