// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/resetrebateuserattempt"
)

// ResetRebateUserAttempt is the model entity for the ResetRebateUserAttempt schema.
type ResetRebateUserAttempt struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// BatchID holds the value of the "batch_id" field.
	BatchID int64 `json:"batch_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// AttemptNo holds the value of the "attempt_no" field.
	AttemptNo int `json:"attempt_no,omitempty"`
	// AdminID holds the value of the "admin_id" field.
	AdminID int64 `json:"admin_id,omitempty"`
	// AdminEmail holds the value of the "admin_email" field.
	AdminEmail string `json:"admin_email,omitempty"`
	// AttemptType holds the value of the "attempt_type" field.
	AttemptType string `json:"attempt_type,omitempty"`
	// Result holds the value of the "result" field.
	Result string `json:"result,omitempty"`
	// ExpectedAmount holds the value of the "expected_amount" field.
	ExpectedAmount string `json:"expected_amount,omitempty"`
	// GrantID holds the value of the "grant_id" field.
	GrantID *int64 `json:"grant_id,omitempty"`
	// ErrorCode holds the value of the "error_code" field.
	ErrorCode string `json:"error_code,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResetRebateUserAttempt) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resetrebateuserattempt.FieldID, resetrebateuserattempt.FieldBatchID, resetrebateuserattempt.FieldUserID, resetrebateuserattempt.FieldAttemptNo, resetrebateuserattempt.FieldAdminID, resetrebateuserattempt.FieldGrantID:
			values[i] = new(sql.NullInt64)
		case resetrebateuserattempt.FieldAdminEmail, resetrebateuserattempt.FieldAttemptType, resetrebateuserattempt.FieldResult, resetrebateuserattempt.FieldExpectedAmount, resetrebateuserattempt.FieldErrorCode, resetrebateuserattempt.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case resetrebateuserattempt.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResetRebateUserAttempt fields.
func (_m *ResetRebateUserAttempt) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resetrebateuserattempt.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case resetrebateuserattempt.FieldBatchID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field batch_id", values[i])
			} else if value.Valid {
				_m.BatchID = value.Int64
			}
		case resetrebateuserattempt.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case resetrebateuserattempt.FieldAttemptNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_no", values[i])
			} else if value.Valid {
				_m.AttemptNo = int(value.Int64)
			}
		case resetrebateuserattempt.FieldAdminID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field admin_id", values[i])
			} else if value.Valid {
				_m.AdminID = value.Int64
			}
		case resetrebateuserattempt.FieldAdminEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field admin_email", values[i])
			} else if value.Valid {
				_m.AdminEmail = value.String
			}
		case resetrebateuserattempt.FieldAttemptType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_type", values[i])
			} else if value.Valid {
				_m.AttemptType = value.String
			}
		case resetrebateuserattempt.FieldResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value.Valid {
				_m.Result = value.String
			}
		case resetrebateuserattempt.FieldExpectedAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field expected_amount", values[i])
			} else if value.Valid {
				_m.ExpectedAmount = value.String
			}
		case resetrebateuserattempt.FieldGrantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field grant_id", values[i])
			} else if value.Valid {
				_m.GrantID = new(int64)
				*_m.GrantID = value.Int64
			}
		case resetrebateuserattempt.FieldErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_code", values[i])
			} else if value.Valid {
				_m.ErrorCode = value.String
			}
		case resetrebateuserattempt.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		case resetrebateuserattempt.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResetRebateUserAttempt.
// This includes values selected through modifiers, order, etc.
func (_m *ResetRebateUserAttempt) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ResetRebateUserAttempt.
// Note that you need to call ResetRebateUserAttempt.Unwrap() before calling this method if this ResetRebateUserAttempt
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ResetRebateUserAttempt) Update() *ResetRebateUserAttemptUpdateOne {
	return NewResetRebateUserAttemptClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ResetRebateUserAttempt entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ResetRebateUserAttempt) Unwrap() *ResetRebateUserAttempt {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResetRebateUserAttempt is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ResetRebateUserAttempt) String() string {
	var builder strings.Builder
	builder.WriteString("ResetRebateUserAttempt(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("batch_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BatchID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("attempt_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptNo))
	builder.WriteString(", ")
	builder.WriteString("admin_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AdminID))
	builder.WriteString(", ")
	builder.WriteString("admin_email=")
	builder.WriteString(_m.AdminEmail)
	builder.WriteString(", ")
	builder.WriteString("attempt_type=")
	builder.WriteString(_m.AttemptType)
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(_m.Result)
	builder.WriteString(", ")
	builder.WriteString("expected_amount=")
	builder.WriteString(_m.ExpectedAmount)
	builder.WriteString(", ")
	if v := _m.GrantID; v != nil {
		builder.WriteString("grant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("error_code=")
	builder.WriteString(_m.ErrorCode)
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ResetRebateUserAttempts is a parsable slice of ResetRebateUserAttempt.
type ResetRebateUserAttempts []*ResetRebateUserAttempt
