// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/resetrebateuseritem"
)

// ResetRebateUserItemCreate is the builder for creating a ResetRebateUserItem entity.
type ResetRebateUserItemCreate struct {
	config
	mutation *ResetRebateUserItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBatchID sets the "batch_id" field.
func (_c *ResetRebateUserItemCreate) SetBatchID(v int64) *ResetRebateUserItemCreate {
	_c.mutation.SetBatchID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ResetRebateUserItemCreate) SetUserID(v int64) *ResetRebateUserItemCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *ResetRebateUserItemCreate) SetEmail(v string) *ResetRebateUserItemCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *ResetRebateUserItemCreate) SetNillableEmail(v *string) *ResetRebateUserItemCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *ResetRebateUserItemCreate) SetUsername(v string) *ResetRebateUserItemCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *ResetRebateUserItemCreate) SetNillableUsername(v *string) *ResetRebateUserItemCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetUserStatus sets the "user_status" field.
func (_c *ResetRebateUserItemCreate) SetUserStatus(v string) *ResetRebateUserItemCreate {
	_c.mutation.SetUserStatus(v)
	return _c
}

// SetNillableUserStatus sets the "user_status" field if the given value is not nil.
func (_c *ResetRebateUserItemCreate) SetNillableUserStatus(v *string) *ResetRebateUserItemCreate {
	if v != nil {
		_c.SetUserStatus(*v)
	}
	return _c
}

// SetUserDeleted sets the "user_deleted" field.
func (_c *ResetRebateUserItemCreate) SetUserDeleted(v bool) *ResetRebateUserItemCreate {
	_c.mutation.SetUserDeleted(v)
	return _c
}

// SetNillableUserDeleted sets the "user_deleted" field if the given value is not nil.
func (_c *ResetRebateUserItemCreate) SetNillableUserDeleted(v *bool) *ResetRebateUserItemCreate {
	if v != nil {
		_c.SetUserDeleted(*v)
	}
	return _c
}

// SetActualAmount sets the "actual_amount" field.
func (_c *ResetRebateUserItemCreate) SetActualAmount(v float64) *ResetRebateUserItemCreate {
	_c.mutation.SetActualAmount(v)
	return _c
}

// SetNillableActualAmount sets the "actual_amount" field if the given value is not nil.
func (_c *ResetRebateUserItemCreate) SetNillableActualAmount(v *float64) *ResetRebateUserItemCreate {
	if v != nil {
		_c.SetActualAmount(*v)
	}
	return _c
}

// SetRebateRatio sets the "rebate_ratio" field.
func (_c *ResetRebateUserItemCreate) SetRebateRatio(v int) *ResetRebateUserItemCreate {
	_c.mutation.SetRebateRatio(v)
	return _c
}

// SetNillableRebateRatio sets the "rebate_ratio" field if the given value is not nil.
func (_c *ResetRebateUserItemCreate) SetNillableRebateRatio(v *int) *ResetRebateUserItemCreate {
	if v != nil {
		_c.SetRebateRatio(*v)
	}
	return _c
}

// SetRebateAmount sets the "rebate_amount" field.
func (_c *ResetRebateUserItemCreate) SetRebateAmount(v float64) *ResetRebateUserItemCreate {
	_c.mutation.SetRebateAmount(v)
	return _c
}

// SetNillableRebateAmount sets the "rebate_amount" field if the given value is not nil.
func (_c *ResetRebateUserItemCreate) SetNillableRebateAmount(v *float64) *ResetRebateUserItemCreate {
	if v != nil {
		_c.SetRebateAmount(*v)
	}
	return _c
}

// SetIssued sets the "issued" field.
func (_c *ResetRebateUserItemCreate) SetIssued(v bool) *ResetRebateUserItemCreate {
	_c.mutation.SetIssued(v)
	return _c
}

// SetNillableIssued sets the "issued" field if the given value is not nil.
func (_c *ResetRebateUserItemCreate) SetNillableIssued(v *bool) *ResetRebateUserItemCreate {
	if v != nil {
		_c.SetIssued(*v)
	}
	return _c
}

// SetExclusionReason sets the "exclusion_reason" field.
func (_c *ResetRebateUserItemCreate) SetExclusionReason(v string) *ResetRebateUserItemCreate {
	_c.mutation.SetExclusionReason(v)
	return _c
}

// SetNillableExclusionReason sets the "exclusion_reason" field if the given value is not nil.
func (_c *ResetRebateUserItemCreate) SetNillableExclusionReason(v *string) *ResetRebateUserItemCreate {
	if v != nil {
		_c.SetExclusionReason(*v)
	}
	return _c
}

// SetGrantID sets the "grant_id" field.
func (_c *ResetRebateUserItemCreate) SetGrantID(v int64) *ResetRebateUserItemCreate {
	_c.mutation.SetGrantID(v)
	return _c
}

// SetNillableGrantID sets the "grant_id" field if the given value is not nil.
func (_c *ResetRebateUserItemCreate) SetNillableGrantID(v *int64) *ResetRebateUserItemCreate {
	if v != nil {
		_c.SetGrantID(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ResetRebateUserItemCreate) SetExpiresAt(v time.Time) *ResetRebateUserItemCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ResetRebateUserItemCreate) SetNillableExpiresAt(v *time.Time) *ResetRebateUserItemCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// Mutation returns the ResetRebateUserItemMutation object of the builder.
func (_c *ResetRebateUserItemCreate) Mutation() *ResetRebateUserItemMutation {
	return _c.mutation
}

// Save creates the ResetRebateUserItem in the database.
func (_c *ResetRebateUserItemCreate) Save(ctx context.Context) (*ResetRebateUserItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResetRebateUserItemCreate) SaveX(ctx context.Context) *ResetRebateUserItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResetRebateUserItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResetRebateUserItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResetRebateUserItemCreate) defaults() {
	if _, ok := _c.mutation.Email(); !ok {
		v := resetrebateuseritem.DefaultEmail
		_c.mutation.SetEmail(v)
	}
	if _, ok := _c.mutation.Username(); !ok {
		v := resetrebateuseritem.DefaultUsername
		_c.mutation.SetUsername(v)
	}
	if _, ok := _c.mutation.UserStatus(); !ok {
		v := resetrebateuseritem.DefaultUserStatus
		_c.mutation.SetUserStatus(v)
	}
	if _, ok := _c.mutation.UserDeleted(); !ok {
		v := resetrebateuseritem.DefaultUserDeleted
		_c.mutation.SetUserDeleted(v)
	}
	if _, ok := _c.mutation.ActualAmount(); !ok {
		v := resetrebateuseritem.DefaultActualAmount
		_c.mutation.SetActualAmount(v)
	}
	if _, ok := _c.mutation.RebateAmount(); !ok {
		v := resetrebateuseritem.DefaultRebateAmount
		_c.mutation.SetRebateAmount(v)
	}
	if _, ok := _c.mutation.Issued(); !ok {
		v := resetrebateuseritem.DefaultIssued
		_c.mutation.SetIssued(v)
	}
	if _, ok := _c.mutation.ExclusionReason(); !ok {
		v := resetrebateuseritem.DefaultExclusionReason
		_c.mutation.SetExclusionReason(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResetRebateUserItemCreate) check() error {
	if _, ok := _c.mutation.BatchID(); !ok {
		return &ValidationError{Name: "batch_id", err: errors.New(`ent: missing required field "ResetRebateUserItem.batch_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ResetRebateUserItem.user_id"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "ResetRebateUserItem.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := resetrebateuseritem.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "ResetRebateUserItem.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "ResetRebateUserItem.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := resetrebateuseritem.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "ResetRebateUserItem.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserStatus(); !ok {
		return &ValidationError{Name: "user_status", err: errors.New(`ent: missing required field "ResetRebateUserItem.user_status"`)}
	}
	if v, ok := _c.mutation.UserStatus(); ok {
		if err := resetrebateuseritem.UserStatusValidator(v); err != nil {
			return &ValidationError{Name: "user_status", err: fmt.Errorf(`ent: validator failed for field "ResetRebateUserItem.user_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserDeleted(); !ok {
		return &ValidationError{Name: "user_deleted", err: errors.New(`ent: missing required field "ResetRebateUserItem.user_deleted"`)}
	}
	if _, ok := _c.mutation.ActualAmount(); !ok {
		return &ValidationError{Name: "actual_amount", err: errors.New(`ent: missing required field "ResetRebateUserItem.actual_amount"`)}
	}
	if _, ok := _c.mutation.RebateAmount(); !ok {
		return &ValidationError{Name: "rebate_amount", err: errors.New(`ent: missing required field "ResetRebateUserItem.rebate_amount"`)}
	}
	if _, ok := _c.mutation.Issued(); !ok {
		return &ValidationError{Name: "issued", err: errors.New(`ent: missing required field "ResetRebateUserItem.issued"`)}
	}
	if _, ok := _c.mutation.ExclusionReason(); !ok {
		return &ValidationError{Name: "exclusion_reason", err: errors.New(`ent: missing required field "ResetRebateUserItem.exclusion_reason"`)}
	}
	if v, ok := _c.mutation.ExclusionReason(); ok {
		if err := resetrebateuseritem.ExclusionReasonValidator(v); err != nil {
			return &ValidationError{Name: "exclusion_reason", err: fmt.Errorf(`ent: validator failed for field "ResetRebateUserItem.exclusion_reason": %w`, err)}
		}
	}
	return nil
}

func (_c *ResetRebateUserItemCreate) sqlSave(ctx context.Context) (*ResetRebateUserItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResetRebateUserItemCreate) createSpec() (*ResetRebateUserItem, *sqlgraph.CreateSpec) {
	var (
		_node = &ResetRebateUserItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resetrebateuseritem.Table, sqlgraph.NewFieldSpec(resetrebateuseritem.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.BatchID(); ok {
		_spec.SetField(resetrebateuseritem.FieldBatchID, field.TypeInt64, value)
		_node.BatchID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(resetrebateuseritem.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(resetrebateuseritem.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(resetrebateuseritem.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.UserStatus(); ok {
		_spec.SetField(resetrebateuseritem.FieldUserStatus, field.TypeString, value)
		_node.UserStatus = value
	}
	if value, ok := _c.mutation.UserDeleted(); ok {
		_spec.SetField(resetrebateuseritem.FieldUserDeleted, field.TypeBool, value)
		_node.UserDeleted = value
	}
	if value, ok := _c.mutation.ActualAmount(); ok {
		_spec.SetField(resetrebateuseritem.FieldActualAmount, field.TypeFloat64, value)
		_node.ActualAmount = value
	}
	if value, ok := _c.mutation.RebateRatio(); ok {
		_spec.SetField(resetrebateuseritem.FieldRebateRatio, field.TypeInt, value)
		_node.RebateRatio = &value
	}
	if value, ok := _c.mutation.RebateAmount(); ok {
		_spec.SetField(resetrebateuseritem.FieldRebateAmount, field.TypeFloat64, value)
		_node.RebateAmount = value
	}
	if value, ok := _c.mutation.Issued(); ok {
		_spec.SetField(resetrebateuseritem.FieldIssued, field.TypeBool, value)
		_node.Issued = value
	}
	if value, ok := _c.mutation.ExclusionReason(); ok {
		_spec.SetField(resetrebateuseritem.FieldExclusionReason, field.TypeString, value)
		_node.ExclusionReason = value
	}
	if value, ok := _c.mutation.GrantID(); ok {
		_spec.SetField(resetrebateuseritem.FieldGrantID, field.TypeInt64, value)
		_node.GrantID = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(resetrebateuseritem.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResetRebateUserItem.Create().
//		SetBatchID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResetRebateUserItemUpsert) {
//			SetBatchID(v+v).
//		}).
//		Exec(ctx)
func (_c *ResetRebateUserItemCreate) OnConflict(opts ...sql.ConflictOption) *ResetRebateUserItemUpsertOne {
	_c.conflict = opts
	return &ResetRebateUserItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResetRebateUserItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResetRebateUserItemCreate) OnConflictColumns(columns ...string) *ResetRebateUserItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResetRebateUserItemUpsertOne{
		create: _c,
	}
}

type (
	// ResetRebateUserItemUpsertOne is the builder for "upsert"-ing
	//  one ResetRebateUserItem node.
	ResetRebateUserItemUpsertOne struct {
		create *ResetRebateUserItemCreate
	}

	// ResetRebateUserItemUpsert is the "OnConflict" setter.
	ResetRebateUserItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetBatchID sets the "batch_id" field.
func (u *ResetRebateUserItemUpsert) SetBatchID(v int64) *ResetRebateUserItemUpsert {
	u.Set(resetrebateuseritem.FieldBatchID, v)
	return u
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsert) UpdateBatchID() *ResetRebateUserItemUpsert {
	u.SetExcluded(resetrebateuseritem.FieldBatchID)
	return u
}

// AddBatchID adds v to the "batch_id" field.
func (u *ResetRebateUserItemUpsert) AddBatchID(v int64) *ResetRebateUserItemUpsert {
	u.Add(resetrebateuseritem.FieldBatchID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ResetRebateUserItemUpsert) SetUserID(v int64) *ResetRebateUserItemUpsert {
	u.Set(resetrebateuseritem.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsert) UpdateUserID() *ResetRebateUserItemUpsert {
	u.SetExcluded(resetrebateuseritem.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *ResetRebateUserItemUpsert) AddUserID(v int64) *ResetRebateUserItemUpsert {
	u.Add(resetrebateuseritem.FieldUserID, v)
	return u
}

// SetEmail sets the "email" field.
func (u *ResetRebateUserItemUpsert) SetEmail(v string) *ResetRebateUserItemUpsert {
	u.Set(resetrebateuseritem.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsert) UpdateEmail() *ResetRebateUserItemUpsert {
	u.SetExcluded(resetrebateuseritem.FieldEmail)
	return u
}

// SetUsername sets the "username" field.
func (u *ResetRebateUserItemUpsert) SetUsername(v string) *ResetRebateUserItemUpsert {
	u.Set(resetrebateuseritem.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsert) UpdateUsername() *ResetRebateUserItemUpsert {
	u.SetExcluded(resetrebateuseritem.FieldUsername)
	return u
}

// SetUserStatus sets the "user_status" field.
func (u *ResetRebateUserItemUpsert) SetUserStatus(v string) *ResetRebateUserItemUpsert {
	u.Set(resetrebateuseritem.FieldUserStatus, v)
	return u
}

// UpdateUserStatus sets the "user_status" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsert) UpdateUserStatus() *ResetRebateUserItemUpsert {
	u.SetExcluded(resetrebateuseritem.FieldUserStatus)
	return u
}

// SetUserDeleted sets the "user_deleted" field.
func (u *ResetRebateUserItemUpsert) SetUserDeleted(v bool) *ResetRebateUserItemUpsert {
	u.Set(resetrebateuseritem.FieldUserDeleted, v)
	return u
}

// UpdateUserDeleted sets the "user_deleted" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsert) UpdateUserDeleted() *ResetRebateUserItemUpsert {
	u.SetExcluded(resetrebateuseritem.FieldUserDeleted)
	return u
}

// SetActualAmount sets the "actual_amount" field.
func (u *ResetRebateUserItemUpsert) SetActualAmount(v float64) *ResetRebateUserItemUpsert {
	u.Set(resetrebateuseritem.FieldActualAmount, v)
	return u
}

// UpdateActualAmount sets the "actual_amount" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsert) UpdateActualAmount() *ResetRebateUserItemUpsert {
	u.SetExcluded(resetrebateuseritem.FieldActualAmount)
	return u
}

// AddActualAmount adds v to the "actual_amount" field.
func (u *ResetRebateUserItemUpsert) AddActualAmount(v float64) *ResetRebateUserItemUpsert {
	u.Add(resetrebateuseritem.FieldActualAmount, v)
	return u
}

// SetRebateRatio sets the "rebate_ratio" field.
func (u *ResetRebateUserItemUpsert) SetRebateRatio(v int) *ResetRebateUserItemUpsert {
	u.Set(resetrebateuseritem.FieldRebateRatio, v)
	return u
}

// UpdateRebateRatio sets the "rebate_ratio" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsert) UpdateRebateRatio() *ResetRebateUserItemUpsert {
	u.SetExcluded(resetrebateuseritem.FieldRebateRatio)
	return u
}

// AddRebateRatio adds v to the "rebate_ratio" field.
func (u *ResetRebateUserItemUpsert) AddRebateRatio(v int) *ResetRebateUserItemUpsert {
	u.Add(resetrebateuseritem.FieldRebateRatio, v)
	return u
}

// ClearRebateRatio clears the value of the "rebate_ratio" field.
func (u *ResetRebateUserItemUpsert) ClearRebateRatio() *ResetRebateUserItemUpsert {
	u.SetNull(resetrebateuseritem.FieldRebateRatio)
	return u
}

// SetRebateAmount sets the "rebate_amount" field.
func (u *ResetRebateUserItemUpsert) SetRebateAmount(v float64) *ResetRebateUserItemUpsert {
	u.Set(resetrebateuseritem.FieldRebateAmount, v)
	return u
}

// UpdateRebateAmount sets the "rebate_amount" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsert) UpdateRebateAmount() *ResetRebateUserItemUpsert {
	u.SetExcluded(resetrebateuseritem.FieldRebateAmount)
	return u
}

// AddRebateAmount adds v to the "rebate_amount" field.
func (u *ResetRebateUserItemUpsert) AddRebateAmount(v float64) *ResetRebateUserItemUpsert {
	u.Add(resetrebateuseritem.FieldRebateAmount, v)
	return u
}

// SetIssued sets the "issued" field.
func (u *ResetRebateUserItemUpsert) SetIssued(v bool) *ResetRebateUserItemUpsert {
	u.Set(resetrebateuseritem.FieldIssued, v)
	return u
}

// UpdateIssued sets the "issued" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsert) UpdateIssued() *ResetRebateUserItemUpsert {
	u.SetExcluded(resetrebateuseritem.FieldIssued)
	return u
}

// SetExclusionReason sets the "exclusion_reason" field.
func (u *ResetRebateUserItemUpsert) SetExclusionReason(v string) *ResetRebateUserItemUpsert {
	u.Set(resetrebateuseritem.FieldExclusionReason, v)
	return u
}

// UpdateExclusionReason sets the "exclusion_reason" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsert) UpdateExclusionReason() *ResetRebateUserItemUpsert {
	u.SetExcluded(resetrebateuseritem.FieldExclusionReason)
	return u
}

// SetGrantID sets the "grant_id" field.
func (u *ResetRebateUserItemUpsert) SetGrantID(v int64) *ResetRebateUserItemUpsert {
	u.Set(resetrebateuseritem.FieldGrantID, v)
	return u
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsert) UpdateGrantID() *ResetRebateUserItemUpsert {
	u.SetExcluded(resetrebateuseritem.FieldGrantID)
	return u
}

// AddGrantID adds v to the "grant_id" field.
func (u *ResetRebateUserItemUpsert) AddGrantID(v int64) *ResetRebateUserItemUpsert {
	u.Add(resetrebateuseritem.FieldGrantID, v)
	return u
}

// ClearGrantID clears the value of the "grant_id" field.
func (u *ResetRebateUserItemUpsert) ClearGrantID() *ResetRebateUserItemUpsert {
	u.SetNull(resetrebateuseritem.FieldGrantID)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ResetRebateUserItemUpsert) SetExpiresAt(v time.Time) *ResetRebateUserItemUpsert {
	u.Set(resetrebateuseritem.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsert) UpdateExpiresAt() *ResetRebateUserItemUpsert {
	u.SetExcluded(resetrebateuseritem.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ResetRebateUserItemUpsert) ClearExpiresAt() *ResetRebateUserItemUpsert {
	u.SetNull(resetrebateuseritem.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ResetRebateUserItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResetRebateUserItemUpsertOne) UpdateNewValues() *ResetRebateUserItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResetRebateUserItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResetRebateUserItemUpsertOne) Ignore() *ResetRebateUserItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResetRebateUserItemUpsertOne) DoNothing() *ResetRebateUserItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResetRebateUserItemCreate.OnConflict
// documentation for more info.
func (u *ResetRebateUserItemUpsertOne) Update(set func(*ResetRebateUserItemUpsert)) *ResetRebateUserItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResetRebateUserItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *ResetRebateUserItemUpsertOne) SetBatchID(v int64) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetBatchID(v)
	})
}

// AddBatchID adds v to the "batch_id" field.
func (u *ResetRebateUserItemUpsertOne) AddBatchID(v int64) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.AddBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertOne) UpdateBatchID() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateBatchID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ResetRebateUserItemUpsertOne) SetUserID(v int64) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ResetRebateUserItemUpsertOne) AddUserID(v int64) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertOne) UpdateUserID() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateUserID()
	})
}

// SetEmail sets the "email" field.
func (u *ResetRebateUserItemUpsertOne) SetEmail(v string) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertOne) UpdateEmail() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateEmail()
	})
}

// SetUsername sets the "username" field.
func (u *ResetRebateUserItemUpsertOne) SetUsername(v string) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertOne) UpdateUsername() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateUsername()
	})
}

// SetUserStatus sets the "user_status" field.
func (u *ResetRebateUserItemUpsertOne) SetUserStatus(v string) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetUserStatus(v)
	})
}

// UpdateUserStatus sets the "user_status" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertOne) UpdateUserStatus() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateUserStatus()
	})
}

// SetUserDeleted sets the "user_deleted" field.
func (u *ResetRebateUserItemUpsertOne) SetUserDeleted(v bool) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetUserDeleted(v)
	})
}

// UpdateUserDeleted sets the "user_deleted" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertOne) UpdateUserDeleted() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateUserDeleted()
	})
}

// SetActualAmount sets the "actual_amount" field.
func (u *ResetRebateUserItemUpsertOne) SetActualAmount(v float64) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetActualAmount(v)
	})
}

// AddActualAmount adds v to the "actual_amount" field.
func (u *ResetRebateUserItemUpsertOne) AddActualAmount(v float64) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.AddActualAmount(v)
	})
}

// UpdateActualAmount sets the "actual_amount" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertOne) UpdateActualAmount() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateActualAmount()
	})
}

// SetRebateRatio sets the "rebate_ratio" field.
func (u *ResetRebateUserItemUpsertOne) SetRebateRatio(v int) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetRebateRatio(v)
	})
}

// AddRebateRatio adds v to the "rebate_ratio" field.
func (u *ResetRebateUserItemUpsertOne) AddRebateRatio(v int) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.AddRebateRatio(v)
	})
}

// UpdateRebateRatio sets the "rebate_ratio" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertOne) UpdateRebateRatio() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateRebateRatio()
	})
}

// ClearRebateRatio clears the value of the "rebate_ratio" field.
func (u *ResetRebateUserItemUpsertOne) ClearRebateRatio() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.ClearRebateRatio()
	})
}

// SetRebateAmount sets the "rebate_amount" field.
func (u *ResetRebateUserItemUpsertOne) SetRebateAmount(v float64) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetRebateAmount(v)
	})
}

// AddRebateAmount adds v to the "rebate_amount" field.
func (u *ResetRebateUserItemUpsertOne) AddRebateAmount(v float64) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.AddRebateAmount(v)
	})
}

// UpdateRebateAmount sets the "rebate_amount" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertOne) UpdateRebateAmount() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateRebateAmount()
	})
}

// SetIssued sets the "issued" field.
func (u *ResetRebateUserItemUpsertOne) SetIssued(v bool) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetIssued(v)
	})
}

// UpdateIssued sets the "issued" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertOne) UpdateIssued() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateIssued()
	})
}

// SetExclusionReason sets the "exclusion_reason" field.
func (u *ResetRebateUserItemUpsertOne) SetExclusionReason(v string) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetExclusionReason(v)
	})
}

// UpdateExclusionReason sets the "exclusion_reason" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertOne) UpdateExclusionReason() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateExclusionReason()
	})
}

// SetGrantID sets the "grant_id" field.
func (u *ResetRebateUserItemUpsertOne) SetGrantID(v int64) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetGrantID(v)
	})
}

// AddGrantID adds v to the "grant_id" field.
func (u *ResetRebateUserItemUpsertOne) AddGrantID(v int64) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.AddGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertOne) UpdateGrantID() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateGrantID()
	})
}

// ClearGrantID clears the value of the "grant_id" field.
func (u *ResetRebateUserItemUpsertOne) ClearGrantID() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.ClearGrantID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ResetRebateUserItemUpsertOne) SetExpiresAt(v time.Time) *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertOne) UpdateExpiresAt() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ResetRebateUserItemUpsertOne) ClearExpiresAt() *ResetRebateUserItemUpsertOne {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *ResetRebateUserItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResetRebateUserItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResetRebateUserItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResetRebateUserItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResetRebateUserItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResetRebateUserItemCreateBulk is the builder for creating many ResetRebateUserItem entities in bulk.
type ResetRebateUserItemCreateBulk struct {
	config
	err      error
	builders []*ResetRebateUserItemCreate
	conflict []sql.ConflictOption
}

// Save creates the ResetRebateUserItem entities in the database.
func (_c *ResetRebateUserItemCreateBulk) Save(ctx context.Context) ([]*ResetRebateUserItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResetRebateUserItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResetRebateUserItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResetRebateUserItemCreateBulk) SaveX(ctx context.Context) []*ResetRebateUserItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResetRebateUserItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResetRebateUserItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResetRebateUserItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResetRebateUserItemUpsert) {
//			SetBatchID(v+v).
//		}).
//		Exec(ctx)
func (_c *ResetRebateUserItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResetRebateUserItemUpsertBulk {
	_c.conflict = opts
	return &ResetRebateUserItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResetRebateUserItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResetRebateUserItemCreateBulk) OnConflictColumns(columns ...string) *ResetRebateUserItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResetRebateUserItemUpsertBulk{
		create: _c,
	}
}

// ResetRebateUserItemUpsertBulk is the builder for "upsert"-ing
// a bulk of ResetRebateUserItem nodes.
type ResetRebateUserItemUpsertBulk struct {
	create *ResetRebateUserItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResetRebateUserItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResetRebateUserItemUpsertBulk) UpdateNewValues() *ResetRebateUserItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResetRebateUserItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResetRebateUserItemUpsertBulk) Ignore() *ResetRebateUserItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResetRebateUserItemUpsertBulk) DoNothing() *ResetRebateUserItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResetRebateUserItemCreateBulk.OnConflict
// documentation for more info.
func (u *ResetRebateUserItemUpsertBulk) Update(set func(*ResetRebateUserItemUpsert)) *ResetRebateUserItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResetRebateUserItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *ResetRebateUserItemUpsertBulk) SetBatchID(v int64) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetBatchID(v)
	})
}

// AddBatchID adds v to the "batch_id" field.
func (u *ResetRebateUserItemUpsertBulk) AddBatchID(v int64) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.AddBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertBulk) UpdateBatchID() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateBatchID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ResetRebateUserItemUpsertBulk) SetUserID(v int64) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ResetRebateUserItemUpsertBulk) AddUserID(v int64) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertBulk) UpdateUserID() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateUserID()
	})
}

// SetEmail sets the "email" field.
func (u *ResetRebateUserItemUpsertBulk) SetEmail(v string) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertBulk) UpdateEmail() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateEmail()
	})
}

// SetUsername sets the "username" field.
func (u *ResetRebateUserItemUpsertBulk) SetUsername(v string) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertBulk) UpdateUsername() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateUsername()
	})
}

// SetUserStatus sets the "user_status" field.
func (u *ResetRebateUserItemUpsertBulk) SetUserStatus(v string) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetUserStatus(v)
	})
}

// UpdateUserStatus sets the "user_status" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertBulk) UpdateUserStatus() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateUserStatus()
	})
}

// SetUserDeleted sets the "user_deleted" field.
func (u *ResetRebateUserItemUpsertBulk) SetUserDeleted(v bool) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetUserDeleted(v)
	})
}

// UpdateUserDeleted sets the "user_deleted" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertBulk) UpdateUserDeleted() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateUserDeleted()
	})
}

// SetActualAmount sets the "actual_amount" field.
func (u *ResetRebateUserItemUpsertBulk) SetActualAmount(v float64) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetActualAmount(v)
	})
}

// AddActualAmount adds v to the "actual_amount" field.
func (u *ResetRebateUserItemUpsertBulk) AddActualAmount(v float64) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.AddActualAmount(v)
	})
}

// UpdateActualAmount sets the "actual_amount" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertBulk) UpdateActualAmount() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateActualAmount()
	})
}

// SetRebateRatio sets the "rebate_ratio" field.
func (u *ResetRebateUserItemUpsertBulk) SetRebateRatio(v int) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetRebateRatio(v)
	})
}

// AddRebateRatio adds v to the "rebate_ratio" field.
func (u *ResetRebateUserItemUpsertBulk) AddRebateRatio(v int) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.AddRebateRatio(v)
	})
}

// UpdateRebateRatio sets the "rebate_ratio" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertBulk) UpdateRebateRatio() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateRebateRatio()
	})
}

// ClearRebateRatio clears the value of the "rebate_ratio" field.
func (u *ResetRebateUserItemUpsertBulk) ClearRebateRatio() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.ClearRebateRatio()
	})
}

// SetRebateAmount sets the "rebate_amount" field.
func (u *ResetRebateUserItemUpsertBulk) SetRebateAmount(v float64) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetRebateAmount(v)
	})
}

// AddRebateAmount adds v to the "rebate_amount" field.
func (u *ResetRebateUserItemUpsertBulk) AddRebateAmount(v float64) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.AddRebateAmount(v)
	})
}

// UpdateRebateAmount sets the "rebate_amount" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertBulk) UpdateRebateAmount() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateRebateAmount()
	})
}

// SetIssued sets the "issued" field.
func (u *ResetRebateUserItemUpsertBulk) SetIssued(v bool) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetIssued(v)
	})
}

// UpdateIssued sets the "issued" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertBulk) UpdateIssued() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateIssued()
	})
}

// SetExclusionReason sets the "exclusion_reason" field.
func (u *ResetRebateUserItemUpsertBulk) SetExclusionReason(v string) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetExclusionReason(v)
	})
}

// UpdateExclusionReason sets the "exclusion_reason" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertBulk) UpdateExclusionReason() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateExclusionReason()
	})
}

// SetGrantID sets the "grant_id" field.
func (u *ResetRebateUserItemUpsertBulk) SetGrantID(v int64) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetGrantID(v)
	})
}

// AddGrantID adds v to the "grant_id" field.
func (u *ResetRebateUserItemUpsertBulk) AddGrantID(v int64) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.AddGrantID(v)
	})
}

// UpdateGrantID sets the "grant_id" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertBulk) UpdateGrantID() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateGrantID()
	})
}

// ClearGrantID clears the value of the "grant_id" field.
func (u *ResetRebateUserItemUpsertBulk) ClearGrantID() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.ClearGrantID()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ResetRebateUserItemUpsertBulk) SetExpiresAt(v time.Time) *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ResetRebateUserItemUpsertBulk) UpdateExpiresAt() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ResetRebateUserItemUpsertBulk) ClearExpiresAt() *ResetRebateUserItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserItemUpsert) {
		s.ClearExpiresAt()
	})
}

// Exec executes the query.
func (u *ResetRebateUserItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResetRebateUserItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResetRebateUserItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResetRebateUserItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
