// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/resetrebateuseraccountitem"
)

// ResetRebateUserAccountItemCreate is the builder for creating a ResetRebateUserAccountItem entity.
type ResetRebateUserAccountItemCreate struct {
	config
	mutation *ResetRebateUserAccountItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetBatchID sets the "batch_id" field.
func (_c *ResetRebateUserAccountItemCreate) SetBatchID(v int64) *ResetRebateUserAccountItemCreate {
	_c.mutation.SetBatchID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ResetRebateUserAccountItemCreate) SetUserID(v int64) *ResetRebateUserAccountItemCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ResetRebateUserAccountItemCreate) SetAccountID(v int64) *ResetRebateUserAccountItemCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetAccountName sets the "account_name" field.
func (_c *ResetRebateUserAccountItemCreate) SetAccountName(v string) *ResetRebateUserAccountItemCreate {
	_c.mutation.SetAccountName(v)
	return _c
}

// SetPeriodStart sets the "period_start" field.
func (_c *ResetRebateUserAccountItemCreate) SetPeriodStart(v time.Time) *ResetRebateUserAccountItemCreate {
	_c.mutation.SetPeriodStart(v)
	return _c
}

// SetPeriodEnd sets the "period_end" field.
func (_c *ResetRebateUserAccountItemCreate) SetPeriodEnd(v time.Time) *ResetRebateUserAccountItemCreate {
	_c.mutation.SetPeriodEnd(v)
	return _c
}

// SetRawAmount sets the "raw_amount" field.
func (_c *ResetRebateUserAccountItemCreate) SetRawAmount(v string) *ResetRebateUserAccountItemCreate {
	_c.mutation.SetRawAmount(v)
	return _c
}

// SetNillableRawAmount sets the "raw_amount" field if the given value is not nil.
func (_c *ResetRebateUserAccountItemCreate) SetNillableRawAmount(v *string) *ResetRebateUserAccountItemCreate {
	if v != nil {
		_c.SetRawAmount(*v)
	}
	return _c
}

// SetEffectiveStatRatio sets the "effective_stat_ratio" field.
func (_c *ResetRebateUserAccountItemCreate) SetEffectiveStatRatio(v string) *ResetRebateUserAccountItemCreate {
	_c.mutation.SetEffectiveStatRatio(v)
	return _c
}

// SetNillableEffectiveStatRatio sets the "effective_stat_ratio" field if the given value is not nil.
func (_c *ResetRebateUserAccountItemCreate) SetNillableEffectiveStatRatio(v *string) *ResetRebateUserAccountItemCreate {
	if v != nil {
		_c.SetEffectiveStatRatio(*v)
	}
	return _c
}

// SetWeightedAmount sets the "weighted_amount" field.
func (_c *ResetRebateUserAccountItemCreate) SetWeightedAmount(v string) *ResetRebateUserAccountItemCreate {
	_c.mutation.SetWeightedAmount(v)
	return _c
}

// SetNillableWeightedAmount sets the "weighted_amount" field if the given value is not nil.
func (_c *ResetRebateUserAccountItemCreate) SetNillableWeightedAmount(v *string) *ResetRebateUserAccountItemCreate {
	if v != nil {
		_c.SetWeightedAmount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ResetRebateUserAccountItemCreate) SetCreatedAt(v time.Time) *ResetRebateUserAccountItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ResetRebateUserAccountItemCreate) SetNillableCreatedAt(v *time.Time) *ResetRebateUserAccountItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ResetRebateUserAccountItemMutation object of the builder.
func (_c *ResetRebateUserAccountItemCreate) Mutation() *ResetRebateUserAccountItemMutation {
	return _c.mutation
}

// Save creates the ResetRebateUserAccountItem in the database.
func (_c *ResetRebateUserAccountItemCreate) Save(ctx context.Context) (*ResetRebateUserAccountItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ResetRebateUserAccountItemCreate) SaveX(ctx context.Context) *ResetRebateUserAccountItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResetRebateUserAccountItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResetRebateUserAccountItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ResetRebateUserAccountItemCreate) defaults() {
	if _, ok := _c.mutation.RawAmount(); !ok {
		v := resetrebateuseraccountitem.DefaultRawAmount
		_c.mutation.SetRawAmount(v)
	}
	if _, ok := _c.mutation.EffectiveStatRatio(); !ok {
		v := resetrebateuseraccountitem.DefaultEffectiveStatRatio
		_c.mutation.SetEffectiveStatRatio(v)
	}
	if _, ok := _c.mutation.WeightedAmount(); !ok {
		v := resetrebateuseraccountitem.DefaultWeightedAmount
		_c.mutation.SetWeightedAmount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := resetrebateuseraccountitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ResetRebateUserAccountItemCreate) check() error {
	if _, ok := _c.mutation.BatchID(); !ok {
		return &ValidationError{Name: "batch_id", err: errors.New(`ent: missing required field "ResetRebateUserAccountItem.batch_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ResetRebateUserAccountItem.user_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ResetRebateUserAccountItem.account_id"`)}
	}
	if _, ok := _c.mutation.AccountName(); !ok {
		return &ValidationError{Name: "account_name", err: errors.New(`ent: missing required field "ResetRebateUserAccountItem.account_name"`)}
	}
	if v, ok := _c.mutation.AccountName(); ok {
		if err := resetrebateuseraccountitem.AccountNameValidator(v); err != nil {
			return &ValidationError{Name: "account_name", err: fmt.Errorf(`ent: validator failed for field "ResetRebateUserAccountItem.account_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PeriodStart(); !ok {
		return &ValidationError{Name: "period_start", err: errors.New(`ent: missing required field "ResetRebateUserAccountItem.period_start"`)}
	}
	if _, ok := _c.mutation.PeriodEnd(); !ok {
		return &ValidationError{Name: "period_end", err: errors.New(`ent: missing required field "ResetRebateUserAccountItem.period_end"`)}
	}
	if _, ok := _c.mutation.RawAmount(); !ok {
		return &ValidationError{Name: "raw_amount", err: errors.New(`ent: missing required field "ResetRebateUserAccountItem.raw_amount"`)}
	}
	if _, ok := _c.mutation.EffectiveStatRatio(); !ok {
		return &ValidationError{Name: "effective_stat_ratio", err: errors.New(`ent: missing required field "ResetRebateUserAccountItem.effective_stat_ratio"`)}
	}
	if _, ok := _c.mutation.WeightedAmount(); !ok {
		return &ValidationError{Name: "weighted_amount", err: errors.New(`ent: missing required field "ResetRebateUserAccountItem.weighted_amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ResetRebateUserAccountItem.created_at"`)}
	}
	return nil
}

func (_c *ResetRebateUserAccountItemCreate) sqlSave(ctx context.Context) (*ResetRebateUserAccountItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ResetRebateUserAccountItemCreate) createSpec() (*ResetRebateUserAccountItem, *sqlgraph.CreateSpec) {
	var (
		_node = &ResetRebateUserAccountItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(resetrebateuseraccountitem.Table, sqlgraph.NewFieldSpec(resetrebateuseraccountitem.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.BatchID(); ok {
		_spec.SetField(resetrebateuseraccountitem.FieldBatchID, field.TypeInt64, value)
		_node.BatchID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(resetrebateuseraccountitem.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(resetrebateuseraccountitem.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.AccountName(); ok {
		_spec.SetField(resetrebateuseraccountitem.FieldAccountName, field.TypeString, value)
		_node.AccountName = value
	}
	if value, ok := _c.mutation.PeriodStart(); ok {
		_spec.SetField(resetrebateuseraccountitem.FieldPeriodStart, field.TypeTime, value)
		_node.PeriodStart = value
	}
	if value, ok := _c.mutation.PeriodEnd(); ok {
		_spec.SetField(resetrebateuseraccountitem.FieldPeriodEnd, field.TypeTime, value)
		_node.PeriodEnd = value
	}
	if value, ok := _c.mutation.RawAmount(); ok {
		_spec.SetField(resetrebateuseraccountitem.FieldRawAmount, field.TypeString, value)
		_node.RawAmount = value
	}
	if value, ok := _c.mutation.EffectiveStatRatio(); ok {
		_spec.SetField(resetrebateuseraccountitem.FieldEffectiveStatRatio, field.TypeString, value)
		_node.EffectiveStatRatio = value
	}
	if value, ok := _c.mutation.WeightedAmount(); ok {
		_spec.SetField(resetrebateuseraccountitem.FieldWeightedAmount, field.TypeString, value)
		_node.WeightedAmount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(resetrebateuseraccountitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResetRebateUserAccountItem.Create().
//		SetBatchID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResetRebateUserAccountItemUpsert) {
//			SetBatchID(v+v).
//		}).
//		Exec(ctx)
func (_c *ResetRebateUserAccountItemCreate) OnConflict(opts ...sql.ConflictOption) *ResetRebateUserAccountItemUpsertOne {
	_c.conflict = opts
	return &ResetRebateUserAccountItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResetRebateUserAccountItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResetRebateUserAccountItemCreate) OnConflictColumns(columns ...string) *ResetRebateUserAccountItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResetRebateUserAccountItemUpsertOne{
		create: _c,
	}
}

type (
	// ResetRebateUserAccountItemUpsertOne is the builder for "upsert"-ing
	//  one ResetRebateUserAccountItem node.
	ResetRebateUserAccountItemUpsertOne struct {
		create *ResetRebateUserAccountItemCreate
	}

	// ResetRebateUserAccountItemUpsert is the "OnConflict" setter.
	ResetRebateUserAccountItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetBatchID sets the "batch_id" field.
func (u *ResetRebateUserAccountItemUpsert) SetBatchID(v int64) *ResetRebateUserAccountItemUpsert {
	u.Set(resetrebateuseraccountitem.FieldBatchID, v)
	return u
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsert) UpdateBatchID() *ResetRebateUserAccountItemUpsert {
	u.SetExcluded(resetrebateuseraccountitem.FieldBatchID)
	return u
}

// AddBatchID adds v to the "batch_id" field.
func (u *ResetRebateUserAccountItemUpsert) AddBatchID(v int64) *ResetRebateUserAccountItemUpsert {
	u.Add(resetrebateuseraccountitem.FieldBatchID, v)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ResetRebateUserAccountItemUpsert) SetUserID(v int64) *ResetRebateUserAccountItemUpsert {
	u.Set(resetrebateuseraccountitem.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsert) UpdateUserID() *ResetRebateUserAccountItemUpsert {
	u.SetExcluded(resetrebateuseraccountitem.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *ResetRebateUserAccountItemUpsert) AddUserID(v int64) *ResetRebateUserAccountItemUpsert {
	u.Add(resetrebateuseraccountitem.FieldUserID, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *ResetRebateUserAccountItemUpsert) SetAccountID(v int64) *ResetRebateUserAccountItemUpsert {
	u.Set(resetrebateuseraccountitem.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsert) UpdateAccountID() *ResetRebateUserAccountItemUpsert {
	u.SetExcluded(resetrebateuseraccountitem.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *ResetRebateUserAccountItemUpsert) AddAccountID(v int64) *ResetRebateUserAccountItemUpsert {
	u.Add(resetrebateuseraccountitem.FieldAccountID, v)
	return u
}

// SetAccountName sets the "account_name" field.
func (u *ResetRebateUserAccountItemUpsert) SetAccountName(v string) *ResetRebateUserAccountItemUpsert {
	u.Set(resetrebateuseraccountitem.FieldAccountName, v)
	return u
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsert) UpdateAccountName() *ResetRebateUserAccountItemUpsert {
	u.SetExcluded(resetrebateuseraccountitem.FieldAccountName)
	return u
}

// SetPeriodStart sets the "period_start" field.
func (u *ResetRebateUserAccountItemUpsert) SetPeriodStart(v time.Time) *ResetRebateUserAccountItemUpsert {
	u.Set(resetrebateuseraccountitem.FieldPeriodStart, v)
	return u
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsert) UpdatePeriodStart() *ResetRebateUserAccountItemUpsert {
	u.SetExcluded(resetrebateuseraccountitem.FieldPeriodStart)
	return u
}

// SetPeriodEnd sets the "period_end" field.
func (u *ResetRebateUserAccountItemUpsert) SetPeriodEnd(v time.Time) *ResetRebateUserAccountItemUpsert {
	u.Set(resetrebateuseraccountitem.FieldPeriodEnd, v)
	return u
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsert) UpdatePeriodEnd() *ResetRebateUserAccountItemUpsert {
	u.SetExcluded(resetrebateuseraccountitem.FieldPeriodEnd)
	return u
}

// SetRawAmount sets the "raw_amount" field.
func (u *ResetRebateUserAccountItemUpsert) SetRawAmount(v string) *ResetRebateUserAccountItemUpsert {
	u.Set(resetrebateuseraccountitem.FieldRawAmount, v)
	return u
}

// UpdateRawAmount sets the "raw_amount" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsert) UpdateRawAmount() *ResetRebateUserAccountItemUpsert {
	u.SetExcluded(resetrebateuseraccountitem.FieldRawAmount)
	return u
}

// SetEffectiveStatRatio sets the "effective_stat_ratio" field.
func (u *ResetRebateUserAccountItemUpsert) SetEffectiveStatRatio(v string) *ResetRebateUserAccountItemUpsert {
	u.Set(resetrebateuseraccountitem.FieldEffectiveStatRatio, v)
	return u
}

// UpdateEffectiveStatRatio sets the "effective_stat_ratio" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsert) UpdateEffectiveStatRatio() *ResetRebateUserAccountItemUpsert {
	u.SetExcluded(resetrebateuseraccountitem.FieldEffectiveStatRatio)
	return u
}

// SetWeightedAmount sets the "weighted_amount" field.
func (u *ResetRebateUserAccountItemUpsert) SetWeightedAmount(v string) *ResetRebateUserAccountItemUpsert {
	u.Set(resetrebateuseraccountitem.FieldWeightedAmount, v)
	return u
}

// UpdateWeightedAmount sets the "weighted_amount" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsert) UpdateWeightedAmount() *ResetRebateUserAccountItemUpsert {
	u.SetExcluded(resetrebateuseraccountitem.FieldWeightedAmount)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ResetRebateUserAccountItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResetRebateUserAccountItemUpsertOne) UpdateNewValues() *ResetRebateUserAccountItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(resetrebateuseraccountitem.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResetRebateUserAccountItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResetRebateUserAccountItemUpsertOne) Ignore() *ResetRebateUserAccountItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResetRebateUserAccountItemUpsertOne) DoNothing() *ResetRebateUserAccountItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResetRebateUserAccountItemCreate.OnConflict
// documentation for more info.
func (u *ResetRebateUserAccountItemUpsertOne) Update(set func(*ResetRebateUserAccountItemUpsert)) *ResetRebateUserAccountItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResetRebateUserAccountItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *ResetRebateUserAccountItemUpsertOne) SetBatchID(v int64) *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetBatchID(v)
	})
}

// AddBatchID adds v to the "batch_id" field.
func (u *ResetRebateUserAccountItemUpsertOne) AddBatchID(v int64) *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.AddBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertOne) UpdateBatchID() *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdateBatchID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ResetRebateUserAccountItemUpsertOne) SetUserID(v int64) *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ResetRebateUserAccountItemUpsertOne) AddUserID(v int64) *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertOne) UpdateUserID() *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdateUserID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ResetRebateUserAccountItemUpsertOne) SetAccountID(v int64) *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *ResetRebateUserAccountItemUpsertOne) AddAccountID(v int64) *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertOne) UpdateAccountID() *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdateAccountID()
	})
}

// SetAccountName sets the "account_name" field.
func (u *ResetRebateUserAccountItemUpsertOne) SetAccountName(v string) *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetAccountName(v)
	})
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertOne) UpdateAccountName() *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdateAccountName()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *ResetRebateUserAccountItemUpsertOne) SetPeriodStart(v time.Time) *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertOne) UpdatePeriodStart() *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetPeriodEnd sets the "period_end" field.
func (u *ResetRebateUserAccountItemUpsertOne) SetPeriodEnd(v time.Time) *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetPeriodEnd(v)
	})
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertOne) UpdatePeriodEnd() *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdatePeriodEnd()
	})
}

// SetRawAmount sets the "raw_amount" field.
func (u *ResetRebateUserAccountItemUpsertOne) SetRawAmount(v string) *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetRawAmount(v)
	})
}

// UpdateRawAmount sets the "raw_amount" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertOne) UpdateRawAmount() *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdateRawAmount()
	})
}

// SetEffectiveStatRatio sets the "effective_stat_ratio" field.
func (u *ResetRebateUserAccountItemUpsertOne) SetEffectiveStatRatio(v string) *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetEffectiveStatRatio(v)
	})
}

// UpdateEffectiveStatRatio sets the "effective_stat_ratio" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertOne) UpdateEffectiveStatRatio() *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdateEffectiveStatRatio()
	})
}

// SetWeightedAmount sets the "weighted_amount" field.
func (u *ResetRebateUserAccountItemUpsertOne) SetWeightedAmount(v string) *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetWeightedAmount(v)
	})
}

// UpdateWeightedAmount sets the "weighted_amount" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertOne) UpdateWeightedAmount() *ResetRebateUserAccountItemUpsertOne {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdateWeightedAmount()
	})
}

// Exec executes the query.
func (u *ResetRebateUserAccountItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResetRebateUserAccountItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResetRebateUserAccountItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResetRebateUserAccountItemUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResetRebateUserAccountItemUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResetRebateUserAccountItemCreateBulk is the builder for creating many ResetRebateUserAccountItem entities in bulk.
type ResetRebateUserAccountItemCreateBulk struct {
	config
	err      error
	builders []*ResetRebateUserAccountItemCreate
	conflict []sql.ConflictOption
}

// Save creates the ResetRebateUserAccountItem entities in the database.
func (_c *ResetRebateUserAccountItemCreateBulk) Save(ctx context.Context) ([]*ResetRebateUserAccountItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ResetRebateUserAccountItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResetRebateUserAccountItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ResetRebateUserAccountItemCreateBulk) SaveX(ctx context.Context) []*ResetRebateUserAccountItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ResetRebateUserAccountItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ResetRebateUserAccountItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResetRebateUserAccountItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResetRebateUserAccountItemUpsert) {
//			SetBatchID(v+v).
//		}).
//		Exec(ctx)
func (_c *ResetRebateUserAccountItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResetRebateUserAccountItemUpsertBulk {
	_c.conflict = opts
	return &ResetRebateUserAccountItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResetRebateUserAccountItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ResetRebateUserAccountItemCreateBulk) OnConflictColumns(columns ...string) *ResetRebateUserAccountItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ResetRebateUserAccountItemUpsertBulk{
		create: _c,
	}
}

// ResetRebateUserAccountItemUpsertBulk is the builder for "upsert"-ing
// a bulk of ResetRebateUserAccountItem nodes.
type ResetRebateUserAccountItemUpsertBulk struct {
	create *ResetRebateUserAccountItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResetRebateUserAccountItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResetRebateUserAccountItemUpsertBulk) UpdateNewValues() *ResetRebateUserAccountItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(resetrebateuseraccountitem.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResetRebateUserAccountItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResetRebateUserAccountItemUpsertBulk) Ignore() *ResetRebateUserAccountItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResetRebateUserAccountItemUpsertBulk) DoNothing() *ResetRebateUserAccountItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResetRebateUserAccountItemCreateBulk.OnConflict
// documentation for more info.
func (u *ResetRebateUserAccountItemUpsertBulk) Update(set func(*ResetRebateUserAccountItemUpsert)) *ResetRebateUserAccountItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResetRebateUserAccountItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetBatchID sets the "batch_id" field.
func (u *ResetRebateUserAccountItemUpsertBulk) SetBatchID(v int64) *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetBatchID(v)
	})
}

// AddBatchID adds v to the "batch_id" field.
func (u *ResetRebateUserAccountItemUpsertBulk) AddBatchID(v int64) *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.AddBatchID(v)
	})
}

// UpdateBatchID sets the "batch_id" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertBulk) UpdateBatchID() *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdateBatchID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ResetRebateUserAccountItemUpsertBulk) SetUserID(v int64) *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *ResetRebateUserAccountItemUpsertBulk) AddUserID(v int64) *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertBulk) UpdateUserID() *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdateUserID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ResetRebateUserAccountItemUpsertBulk) SetAccountID(v int64) *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *ResetRebateUserAccountItemUpsertBulk) AddAccountID(v int64) *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertBulk) UpdateAccountID() *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdateAccountID()
	})
}

// SetAccountName sets the "account_name" field.
func (u *ResetRebateUserAccountItemUpsertBulk) SetAccountName(v string) *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetAccountName(v)
	})
}

// UpdateAccountName sets the "account_name" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertBulk) UpdateAccountName() *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdateAccountName()
	})
}

// SetPeriodStart sets the "period_start" field.
func (u *ResetRebateUserAccountItemUpsertBulk) SetPeriodStart(v time.Time) *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetPeriodStart(v)
	})
}

// UpdatePeriodStart sets the "period_start" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertBulk) UpdatePeriodStart() *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdatePeriodStart()
	})
}

// SetPeriodEnd sets the "period_end" field.
func (u *ResetRebateUserAccountItemUpsertBulk) SetPeriodEnd(v time.Time) *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetPeriodEnd(v)
	})
}

// UpdatePeriodEnd sets the "period_end" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertBulk) UpdatePeriodEnd() *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdatePeriodEnd()
	})
}

// SetRawAmount sets the "raw_amount" field.
func (u *ResetRebateUserAccountItemUpsertBulk) SetRawAmount(v string) *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetRawAmount(v)
	})
}

// UpdateRawAmount sets the "raw_amount" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertBulk) UpdateRawAmount() *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdateRawAmount()
	})
}

// SetEffectiveStatRatio sets the "effective_stat_ratio" field.
func (u *ResetRebateUserAccountItemUpsertBulk) SetEffectiveStatRatio(v string) *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetEffectiveStatRatio(v)
	})
}

// UpdateEffectiveStatRatio sets the "effective_stat_ratio" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertBulk) UpdateEffectiveStatRatio() *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdateEffectiveStatRatio()
	})
}

// SetWeightedAmount sets the "weighted_amount" field.
func (u *ResetRebateUserAccountItemUpsertBulk) SetWeightedAmount(v string) *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.SetWeightedAmount(v)
	})
}

// UpdateWeightedAmount sets the "weighted_amount" field to the value that was provided on create.
func (u *ResetRebateUserAccountItemUpsertBulk) UpdateWeightedAmount() *ResetRebateUserAccountItemUpsertBulk {
	return u.Update(func(s *ResetRebateUserAccountItemUpsert) {
		s.UpdateWeightedAmount()
	})
}

// Exec executes the query.
func (u *ResetRebateUserAccountItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResetRebateUserAccountItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResetRebateUserAccountItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResetRebateUserAccountItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
