// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/securitydepositrefund"
)

// SecurityDepositRefundCreate is the builder for creating a SecurityDepositRefund entity.
type SecurityDepositRefundCreate struct {
	config
	mutation *SecurityDepositRefundMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRefundID sets the "refund_id" field.
func (_c *SecurityDepositRefundCreate) SetRefundID(v string) *SecurityDepositRefundCreate {
	_c.mutation.SetRefundID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SecurityDepositRefundCreate) SetUserID(v int64) *SecurityDepositRefundCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetLotID sets the "lot_id" field.
func (_c *SecurityDepositRefundCreate) SetLotID(v int64) *SecurityDepositRefundCreate {
	_c.mutation.SetLotID(v)
	return _c
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_c *SecurityDepositRefundCreate) SetPaymentOrderID(v int64) *SecurityDepositRefundCreate {
	_c.mutation.SetPaymentOrderID(v)
	return _c
}

// SetPrincipalCents sets the "principal_cents" field.
func (_c *SecurityDepositRefundCreate) SetPrincipalCents(v int64) *SecurityDepositRefundCreate {
	_c.mutation.SetPrincipalCents(v)
	return _c
}

// SetGatewayAmount sets the "gateway_amount" field.
func (_c *SecurityDepositRefundCreate) SetGatewayAmount(v string) *SecurityDepositRefundCreate {
	_c.mutation.SetGatewayAmount(v)
	return _c
}

// SetGatewayCurrency sets the "gateway_currency" field.
func (_c *SecurityDepositRefundCreate) SetGatewayCurrency(v string) *SecurityDepositRefundCreate {
	_c.mutation.SetGatewayCurrency(v)
	return _c
}

// SetNillableGatewayCurrency sets the "gateway_currency" field if the given value is not nil.
func (_c *SecurityDepositRefundCreate) SetNillableGatewayCurrency(v *string) *SecurityDepositRefundCreate {
	if v != nil {
		_c.SetGatewayCurrency(*v)
	}
	return _c
}

// SetMode sets the "mode" field.
func (_c *SecurityDepositRefundCreate) SetMode(v securitydepositrefund.Mode) *SecurityDepositRefundCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetState sets the "state" field.
func (_c *SecurityDepositRefundCreate) SetState(v string) *SecurityDepositRefundCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetRequestedBy sets the "requested_by" field.
func (_c *SecurityDepositRefundCreate) SetRequestedBy(v int64) *SecurityDepositRefundCreate {
	_c.mutation.SetRequestedBy(v)
	return _c
}

// SetNillableRequestedBy sets the "requested_by" field if the given value is not nil.
func (_c *SecurityDepositRefundCreate) SetNillableRequestedBy(v *int64) *SecurityDepositRefundCreate {
	if v != nil {
		_c.SetRequestedBy(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *SecurityDepositRefundCreate) SetReason(v string) *SecurityDepositRefundCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *SecurityDepositRefundCreate) SetNillableReason(v *string) *SecurityDepositRefundCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetQuoteHash sets the "quote_hash" field.
func (_c *SecurityDepositRefundCreate) SetQuoteHash(v string) *SecurityDepositRefundCreate {
	_c.mutation.SetQuoteHash(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *SecurityDepositRefundCreate) SetIdempotencyKey(v string) *SecurityDepositRefundCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetProviderRequestID sets the "provider_request_id" field.
func (_c *SecurityDepositRefundCreate) SetProviderRequestID(v string) *SecurityDepositRefundCreate {
	_c.mutation.SetProviderRequestID(v)
	return _c
}

// SetNillableProviderRequestID sets the "provider_request_id" field if the given value is not nil.
func (_c *SecurityDepositRefundCreate) SetNillableProviderRequestID(v *string) *SecurityDepositRefundCreate {
	if v != nil {
		_c.SetProviderRequestID(*v)
	}
	return _c
}

// SetProviderResponseSnapshot sets the "provider_response_snapshot" field.
func (_c *SecurityDepositRefundCreate) SetProviderResponseSnapshot(v map[string]interface{}) *SecurityDepositRefundCreate {
	_c.mutation.SetProviderResponseSnapshot(v)
	return _c
}

// SetExternalRefundID sets the "external_refund_id" field.
func (_c *SecurityDepositRefundCreate) SetExternalRefundID(v string) *SecurityDepositRefundCreate {
	_c.mutation.SetExternalRefundID(v)
	return _c
}

// SetNillableExternalRefundID sets the "external_refund_id" field if the given value is not nil.
func (_c *SecurityDepositRefundCreate) SetNillableExternalRefundID(v *string) *SecurityDepositRefundCreate {
	if v != nil {
		_c.SetExternalRefundID(*v)
	}
	return _c
}

// SetExternalRefundedAt sets the "external_refunded_at" field.
func (_c *SecurityDepositRefundCreate) SetExternalRefundedAt(v time.Time) *SecurityDepositRefundCreate {
	_c.mutation.SetExternalRefundedAt(v)
	return _c
}

// SetNillableExternalRefundedAt sets the "external_refunded_at" field if the given value is not nil.
func (_c *SecurityDepositRefundCreate) SetNillableExternalRefundedAt(v *time.Time) *SecurityDepositRefundCreate {
	if v != nil {
		_c.SetExternalRefundedAt(*v)
	}
	return _c
}

// SetExternalEvidence sets the "external_evidence" field.
func (_c *SecurityDepositRefundCreate) SetExternalEvidence(v map[string]interface{}) *SecurityDepositRefundCreate {
	_c.mutation.SetExternalEvidence(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SecurityDepositRefundCreate) SetCreatedAt(v time.Time) *SecurityDepositRefundCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SecurityDepositRefundCreate) SetNillableCreatedAt(v *time.Time) *SecurityDepositRefundCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSubmittedAt sets the "submitted_at" field.
func (_c *SecurityDepositRefundCreate) SetSubmittedAt(v time.Time) *SecurityDepositRefundCreate {
	_c.mutation.SetSubmittedAt(v)
	return _c
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_c *SecurityDepositRefundCreate) SetNillableSubmittedAt(v *time.Time) *SecurityDepositRefundCreate {
	if v != nil {
		_c.SetSubmittedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *SecurityDepositRefundCreate) SetCompletedAt(v time.Time) *SecurityDepositRefundCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *SecurityDepositRefundCreate) SetNillableCompletedAt(v *time.Time) *SecurityDepositRefundCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// Mutation returns the SecurityDepositRefundMutation object of the builder.
func (_c *SecurityDepositRefundCreate) Mutation() *SecurityDepositRefundMutation {
	return _c.mutation
}

// Save creates the SecurityDepositRefund in the database.
func (_c *SecurityDepositRefundCreate) Save(ctx context.Context) (*SecurityDepositRefund, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SecurityDepositRefundCreate) SaveX(ctx context.Context) *SecurityDepositRefund {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecurityDepositRefundCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecurityDepositRefundCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SecurityDepositRefundCreate) defaults() {
	if _, ok := _c.mutation.GatewayCurrency(); !ok {
		v := securitydepositrefund.DefaultGatewayCurrency
		_c.mutation.SetGatewayCurrency(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := securitydepositrefund.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SecurityDepositRefundCreate) check() error {
	if _, ok := _c.mutation.RefundID(); !ok {
		return &ValidationError{Name: "refund_id", err: errors.New(`ent: missing required field "SecurityDepositRefund.refund_id"`)}
	}
	if v, ok := _c.mutation.RefundID(); ok {
		if err := securitydepositrefund.RefundIDValidator(v); err != nil {
			return &ValidationError{Name: "refund_id", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositRefund.refund_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SecurityDepositRefund.user_id"`)}
	}
	if _, ok := _c.mutation.LotID(); !ok {
		return &ValidationError{Name: "lot_id", err: errors.New(`ent: missing required field "SecurityDepositRefund.lot_id"`)}
	}
	if _, ok := _c.mutation.PaymentOrderID(); !ok {
		return &ValidationError{Name: "payment_order_id", err: errors.New(`ent: missing required field "SecurityDepositRefund.payment_order_id"`)}
	}
	if _, ok := _c.mutation.PrincipalCents(); !ok {
		return &ValidationError{Name: "principal_cents", err: errors.New(`ent: missing required field "SecurityDepositRefund.principal_cents"`)}
	}
	if v, ok := _c.mutation.PrincipalCents(); ok {
		if err := securitydepositrefund.PrincipalCentsValidator(v); err != nil {
			return &ValidationError{Name: "principal_cents", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositRefund.principal_cents": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GatewayAmount(); !ok {
		return &ValidationError{Name: "gateway_amount", err: errors.New(`ent: missing required field "SecurityDepositRefund.gateway_amount"`)}
	}
	if v, ok := _c.mutation.GatewayAmount(); ok {
		if err := securitydepositrefund.GatewayAmountValidator(v); err != nil {
			return &ValidationError{Name: "gateway_amount", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositRefund.gateway_amount": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GatewayCurrency(); !ok {
		return &ValidationError{Name: "gateway_currency", err: errors.New(`ent: missing required field "SecurityDepositRefund.gateway_currency"`)}
	}
	if v, ok := _c.mutation.GatewayCurrency(); ok {
		if err := securitydepositrefund.GatewayCurrencyValidator(v); err != nil {
			return &ValidationError{Name: "gateway_currency", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositRefund.gateway_currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "SecurityDepositRefund.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := securitydepositrefund.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositRefund.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "SecurityDepositRefund.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := securitydepositrefund.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositRefund.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QuoteHash(); !ok {
		return &ValidationError{Name: "quote_hash", err: errors.New(`ent: missing required field "SecurityDepositRefund.quote_hash"`)}
	}
	if v, ok := _c.mutation.QuoteHash(); ok {
		if err := securitydepositrefund.QuoteHashValidator(v); err != nil {
			return &ValidationError{Name: "quote_hash", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositRefund.quote_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "SecurityDepositRefund.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := securitydepositrefund.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositRefund.idempotency_key": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProviderRequestID(); ok {
		if err := securitydepositrefund.ProviderRequestIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_request_id", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositRefund.provider_request_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ExternalRefundID(); ok {
		if err := securitydepositrefund.ExternalRefundIDValidator(v); err != nil {
			return &ValidationError{Name: "external_refund_id", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositRefund.external_refund_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SecurityDepositRefund.created_at"`)}
	}
	return nil
}

func (_c *SecurityDepositRefundCreate) sqlSave(ctx context.Context) (*SecurityDepositRefund, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SecurityDepositRefundCreate) createSpec() (*SecurityDepositRefund, *sqlgraph.CreateSpec) {
	var (
		_node = &SecurityDepositRefund{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(securitydepositrefund.Table, sqlgraph.NewFieldSpec(securitydepositrefund.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RefundID(); ok {
		_spec.SetField(securitydepositrefund.FieldRefundID, field.TypeString, value)
		_node.RefundID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(securitydepositrefund.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.LotID(); ok {
		_spec.SetField(securitydepositrefund.FieldLotID, field.TypeInt64, value)
		_node.LotID = value
	}
	if value, ok := _c.mutation.PaymentOrderID(); ok {
		_spec.SetField(securitydepositrefund.FieldPaymentOrderID, field.TypeInt64, value)
		_node.PaymentOrderID = value
	}
	if value, ok := _c.mutation.PrincipalCents(); ok {
		_spec.SetField(securitydepositrefund.FieldPrincipalCents, field.TypeInt64, value)
		_node.PrincipalCents = value
	}
	if value, ok := _c.mutation.GatewayAmount(); ok {
		_spec.SetField(securitydepositrefund.FieldGatewayAmount, field.TypeString, value)
		_node.GatewayAmount = value
	}
	if value, ok := _c.mutation.GatewayCurrency(); ok {
		_spec.SetField(securitydepositrefund.FieldGatewayCurrency, field.TypeString, value)
		_node.GatewayCurrency = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(securitydepositrefund.FieldMode, field.TypeEnum, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(securitydepositrefund.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.RequestedBy(); ok {
		_spec.SetField(securitydepositrefund.FieldRequestedBy, field.TypeInt64, value)
		_node.RequestedBy = &value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(securitydepositrefund.FieldReason, field.TypeString, value)
		_node.Reason = &value
	}
	if value, ok := _c.mutation.QuoteHash(); ok {
		_spec.SetField(securitydepositrefund.FieldQuoteHash, field.TypeString, value)
		_node.QuoteHash = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(securitydepositrefund.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.ProviderRequestID(); ok {
		_spec.SetField(securitydepositrefund.FieldProviderRequestID, field.TypeString, value)
		_node.ProviderRequestID = &value
	}
	if value, ok := _c.mutation.ProviderResponseSnapshot(); ok {
		_spec.SetField(securitydepositrefund.FieldProviderResponseSnapshot, field.TypeJSON, value)
		_node.ProviderResponseSnapshot = value
	}
	if value, ok := _c.mutation.ExternalRefundID(); ok {
		_spec.SetField(securitydepositrefund.FieldExternalRefundID, field.TypeString, value)
		_node.ExternalRefundID = &value
	}
	if value, ok := _c.mutation.ExternalRefundedAt(); ok {
		_spec.SetField(securitydepositrefund.FieldExternalRefundedAt, field.TypeTime, value)
		_node.ExternalRefundedAt = &value
	}
	if value, ok := _c.mutation.ExternalEvidence(); ok {
		_spec.SetField(securitydepositrefund.FieldExternalEvidence, field.TypeJSON, value)
		_node.ExternalEvidence = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(securitydepositrefund.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.SubmittedAt(); ok {
		_spec.SetField(securitydepositrefund.FieldSubmittedAt, field.TypeTime, value)
		_node.SubmittedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(securitydepositrefund.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SecurityDepositRefund.Create().
//		SetRefundID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SecurityDepositRefundUpsert) {
//			SetRefundID(v+v).
//		}).
//		Exec(ctx)
func (_c *SecurityDepositRefundCreate) OnConflict(opts ...sql.ConflictOption) *SecurityDepositRefundUpsertOne {
	_c.conflict = opts
	return &SecurityDepositRefundUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SecurityDepositRefund.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SecurityDepositRefundCreate) OnConflictColumns(columns ...string) *SecurityDepositRefundUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SecurityDepositRefundUpsertOne{
		create: _c,
	}
}

type (
	// SecurityDepositRefundUpsertOne is the builder for "upsert"-ing
	//  one SecurityDepositRefund node.
	SecurityDepositRefundUpsertOne struct {
		create *SecurityDepositRefundCreate
	}

	// SecurityDepositRefundUpsert is the "OnConflict" setter.
	SecurityDepositRefundUpsert struct {
		*sql.UpdateSet
	}
)

// SetRefundID sets the "refund_id" field.
func (u *SecurityDepositRefundUpsert) SetRefundID(v string) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldRefundID, v)
	return u
}

// UpdateRefundID sets the "refund_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateRefundID() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldRefundID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *SecurityDepositRefundUpsert) SetUserID(v int64) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateUserID() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *SecurityDepositRefundUpsert) AddUserID(v int64) *SecurityDepositRefundUpsert {
	u.Add(securitydepositrefund.FieldUserID, v)
	return u
}

// SetLotID sets the "lot_id" field.
func (u *SecurityDepositRefundUpsert) SetLotID(v int64) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldLotID, v)
	return u
}

// UpdateLotID sets the "lot_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateLotID() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldLotID)
	return u
}

// AddLotID adds v to the "lot_id" field.
func (u *SecurityDepositRefundUpsert) AddLotID(v int64) *SecurityDepositRefundUpsert {
	u.Add(securitydepositrefund.FieldLotID, v)
	return u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *SecurityDepositRefundUpsert) SetPaymentOrderID(v int64) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldPaymentOrderID, v)
	return u
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdatePaymentOrderID() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldPaymentOrderID)
	return u
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *SecurityDepositRefundUpsert) AddPaymentOrderID(v int64) *SecurityDepositRefundUpsert {
	u.Add(securitydepositrefund.FieldPaymentOrderID, v)
	return u
}

// SetPrincipalCents sets the "principal_cents" field.
func (u *SecurityDepositRefundUpsert) SetPrincipalCents(v int64) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldPrincipalCents, v)
	return u
}

// UpdatePrincipalCents sets the "principal_cents" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdatePrincipalCents() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldPrincipalCents)
	return u
}

// AddPrincipalCents adds v to the "principal_cents" field.
func (u *SecurityDepositRefundUpsert) AddPrincipalCents(v int64) *SecurityDepositRefundUpsert {
	u.Add(securitydepositrefund.FieldPrincipalCents, v)
	return u
}

// SetGatewayAmount sets the "gateway_amount" field.
func (u *SecurityDepositRefundUpsert) SetGatewayAmount(v string) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldGatewayAmount, v)
	return u
}

// UpdateGatewayAmount sets the "gateway_amount" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateGatewayAmount() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldGatewayAmount)
	return u
}

// SetGatewayCurrency sets the "gateway_currency" field.
func (u *SecurityDepositRefundUpsert) SetGatewayCurrency(v string) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldGatewayCurrency, v)
	return u
}

// UpdateGatewayCurrency sets the "gateway_currency" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateGatewayCurrency() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldGatewayCurrency)
	return u
}

// SetMode sets the "mode" field.
func (u *SecurityDepositRefundUpsert) SetMode(v securitydepositrefund.Mode) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateMode() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldMode)
	return u
}

// SetState sets the "state" field.
func (u *SecurityDepositRefundUpsert) SetState(v string) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateState() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldState)
	return u
}

// SetRequestedBy sets the "requested_by" field.
func (u *SecurityDepositRefundUpsert) SetRequestedBy(v int64) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldRequestedBy, v)
	return u
}

// UpdateRequestedBy sets the "requested_by" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateRequestedBy() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldRequestedBy)
	return u
}

// AddRequestedBy adds v to the "requested_by" field.
func (u *SecurityDepositRefundUpsert) AddRequestedBy(v int64) *SecurityDepositRefundUpsert {
	u.Add(securitydepositrefund.FieldRequestedBy, v)
	return u
}

// ClearRequestedBy clears the value of the "requested_by" field.
func (u *SecurityDepositRefundUpsert) ClearRequestedBy() *SecurityDepositRefundUpsert {
	u.SetNull(securitydepositrefund.FieldRequestedBy)
	return u
}

// SetReason sets the "reason" field.
func (u *SecurityDepositRefundUpsert) SetReason(v string) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateReason() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *SecurityDepositRefundUpsert) ClearReason() *SecurityDepositRefundUpsert {
	u.SetNull(securitydepositrefund.FieldReason)
	return u
}

// SetQuoteHash sets the "quote_hash" field.
func (u *SecurityDepositRefundUpsert) SetQuoteHash(v string) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldQuoteHash, v)
	return u
}

// UpdateQuoteHash sets the "quote_hash" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateQuoteHash() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldQuoteHash)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *SecurityDepositRefundUpsert) SetIdempotencyKey(v string) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateIdempotencyKey() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldIdempotencyKey)
	return u
}

// SetProviderRequestID sets the "provider_request_id" field.
func (u *SecurityDepositRefundUpsert) SetProviderRequestID(v string) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldProviderRequestID, v)
	return u
}

// UpdateProviderRequestID sets the "provider_request_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateProviderRequestID() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldProviderRequestID)
	return u
}

// ClearProviderRequestID clears the value of the "provider_request_id" field.
func (u *SecurityDepositRefundUpsert) ClearProviderRequestID() *SecurityDepositRefundUpsert {
	u.SetNull(securitydepositrefund.FieldProviderRequestID)
	return u
}

// SetProviderResponseSnapshot sets the "provider_response_snapshot" field.
func (u *SecurityDepositRefundUpsert) SetProviderResponseSnapshot(v map[string]interface{}) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldProviderResponseSnapshot, v)
	return u
}

// UpdateProviderResponseSnapshot sets the "provider_response_snapshot" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateProviderResponseSnapshot() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldProviderResponseSnapshot)
	return u
}

// ClearProviderResponseSnapshot clears the value of the "provider_response_snapshot" field.
func (u *SecurityDepositRefundUpsert) ClearProviderResponseSnapshot() *SecurityDepositRefundUpsert {
	u.SetNull(securitydepositrefund.FieldProviderResponseSnapshot)
	return u
}

// SetExternalRefundID sets the "external_refund_id" field.
func (u *SecurityDepositRefundUpsert) SetExternalRefundID(v string) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldExternalRefundID, v)
	return u
}

// UpdateExternalRefundID sets the "external_refund_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateExternalRefundID() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldExternalRefundID)
	return u
}

// ClearExternalRefundID clears the value of the "external_refund_id" field.
func (u *SecurityDepositRefundUpsert) ClearExternalRefundID() *SecurityDepositRefundUpsert {
	u.SetNull(securitydepositrefund.FieldExternalRefundID)
	return u
}

// SetExternalRefundedAt sets the "external_refunded_at" field.
func (u *SecurityDepositRefundUpsert) SetExternalRefundedAt(v time.Time) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldExternalRefundedAt, v)
	return u
}

// UpdateExternalRefundedAt sets the "external_refunded_at" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateExternalRefundedAt() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldExternalRefundedAt)
	return u
}

// ClearExternalRefundedAt clears the value of the "external_refunded_at" field.
func (u *SecurityDepositRefundUpsert) ClearExternalRefundedAt() *SecurityDepositRefundUpsert {
	u.SetNull(securitydepositrefund.FieldExternalRefundedAt)
	return u
}

// SetExternalEvidence sets the "external_evidence" field.
func (u *SecurityDepositRefundUpsert) SetExternalEvidence(v map[string]interface{}) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldExternalEvidence, v)
	return u
}

// UpdateExternalEvidence sets the "external_evidence" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateExternalEvidence() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldExternalEvidence)
	return u
}

// ClearExternalEvidence clears the value of the "external_evidence" field.
func (u *SecurityDepositRefundUpsert) ClearExternalEvidence() *SecurityDepositRefundUpsert {
	u.SetNull(securitydepositrefund.FieldExternalEvidence)
	return u
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *SecurityDepositRefundUpsert) SetSubmittedAt(v time.Time) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldSubmittedAt, v)
	return u
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateSubmittedAt() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldSubmittedAt)
	return u
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (u *SecurityDepositRefundUpsert) ClearSubmittedAt() *SecurityDepositRefundUpsert {
	u.SetNull(securitydepositrefund.FieldSubmittedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *SecurityDepositRefundUpsert) SetCompletedAt(v time.Time) *SecurityDepositRefundUpsert {
	u.Set(securitydepositrefund.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsert) UpdateCompletedAt() *SecurityDepositRefundUpsert {
	u.SetExcluded(securitydepositrefund.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *SecurityDepositRefundUpsert) ClearCompletedAt() *SecurityDepositRefundUpsert {
	u.SetNull(securitydepositrefund.FieldCompletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SecurityDepositRefund.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SecurityDepositRefundUpsertOne) UpdateNewValues() *SecurityDepositRefundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(securitydepositrefund.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SecurityDepositRefund.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SecurityDepositRefundUpsertOne) Ignore() *SecurityDepositRefundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SecurityDepositRefundUpsertOne) DoNothing() *SecurityDepositRefundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SecurityDepositRefundCreate.OnConflict
// documentation for more info.
func (u *SecurityDepositRefundUpsertOne) Update(set func(*SecurityDepositRefundUpsert)) *SecurityDepositRefundUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SecurityDepositRefundUpsert{UpdateSet: update})
	}))
	return u
}

// SetRefundID sets the "refund_id" field.
func (u *SecurityDepositRefundUpsertOne) SetRefundID(v string) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetRefundID(v)
	})
}

// UpdateRefundID sets the "refund_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateRefundID() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateRefundID()
	})
}

// SetUserID sets the "user_id" field.
func (u *SecurityDepositRefundUpsertOne) SetUserID(v int64) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SecurityDepositRefundUpsertOne) AddUserID(v int64) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateUserID() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateUserID()
	})
}

// SetLotID sets the "lot_id" field.
func (u *SecurityDepositRefundUpsertOne) SetLotID(v int64) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetLotID(v)
	})
}

// AddLotID adds v to the "lot_id" field.
func (u *SecurityDepositRefundUpsertOne) AddLotID(v int64) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.AddLotID(v)
	})
}

// UpdateLotID sets the "lot_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateLotID() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateLotID()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *SecurityDepositRefundUpsertOne) SetPaymentOrderID(v int64) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *SecurityDepositRefundUpsertOne) AddPaymentOrderID(v int64) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdatePaymentOrderID() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// SetPrincipalCents sets the "principal_cents" field.
func (u *SecurityDepositRefundUpsertOne) SetPrincipalCents(v int64) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetPrincipalCents(v)
	})
}

// AddPrincipalCents adds v to the "principal_cents" field.
func (u *SecurityDepositRefundUpsertOne) AddPrincipalCents(v int64) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.AddPrincipalCents(v)
	})
}

// UpdatePrincipalCents sets the "principal_cents" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdatePrincipalCents() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdatePrincipalCents()
	})
}

// SetGatewayAmount sets the "gateway_amount" field.
func (u *SecurityDepositRefundUpsertOne) SetGatewayAmount(v string) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetGatewayAmount(v)
	})
}

// UpdateGatewayAmount sets the "gateway_amount" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateGatewayAmount() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateGatewayAmount()
	})
}

// SetGatewayCurrency sets the "gateway_currency" field.
func (u *SecurityDepositRefundUpsertOne) SetGatewayCurrency(v string) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetGatewayCurrency(v)
	})
}

// UpdateGatewayCurrency sets the "gateway_currency" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateGatewayCurrency() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateGatewayCurrency()
	})
}

// SetMode sets the "mode" field.
func (u *SecurityDepositRefundUpsertOne) SetMode(v securitydepositrefund.Mode) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateMode() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateMode()
	})
}

// SetState sets the "state" field.
func (u *SecurityDepositRefundUpsertOne) SetState(v string) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateState() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateState()
	})
}

// SetRequestedBy sets the "requested_by" field.
func (u *SecurityDepositRefundUpsertOne) SetRequestedBy(v int64) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetRequestedBy(v)
	})
}

// AddRequestedBy adds v to the "requested_by" field.
func (u *SecurityDepositRefundUpsertOne) AddRequestedBy(v int64) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.AddRequestedBy(v)
	})
}

// UpdateRequestedBy sets the "requested_by" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateRequestedBy() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateRequestedBy()
	})
}

// ClearRequestedBy clears the value of the "requested_by" field.
func (u *SecurityDepositRefundUpsertOne) ClearRequestedBy() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearRequestedBy()
	})
}

// SetReason sets the "reason" field.
func (u *SecurityDepositRefundUpsertOne) SetReason(v string) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateReason() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *SecurityDepositRefundUpsertOne) ClearReason() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearReason()
	})
}

// SetQuoteHash sets the "quote_hash" field.
func (u *SecurityDepositRefundUpsertOne) SetQuoteHash(v string) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetQuoteHash(v)
	})
}

// UpdateQuoteHash sets the "quote_hash" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateQuoteHash() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateQuoteHash()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *SecurityDepositRefundUpsertOne) SetIdempotencyKey(v string) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateIdempotencyKey() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// SetProviderRequestID sets the "provider_request_id" field.
func (u *SecurityDepositRefundUpsertOne) SetProviderRequestID(v string) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetProviderRequestID(v)
	})
}

// UpdateProviderRequestID sets the "provider_request_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateProviderRequestID() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateProviderRequestID()
	})
}

// ClearProviderRequestID clears the value of the "provider_request_id" field.
func (u *SecurityDepositRefundUpsertOne) ClearProviderRequestID() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearProviderRequestID()
	})
}

// SetProviderResponseSnapshot sets the "provider_response_snapshot" field.
func (u *SecurityDepositRefundUpsertOne) SetProviderResponseSnapshot(v map[string]interface{}) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetProviderResponseSnapshot(v)
	})
}

// UpdateProviderResponseSnapshot sets the "provider_response_snapshot" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateProviderResponseSnapshot() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateProviderResponseSnapshot()
	})
}

// ClearProviderResponseSnapshot clears the value of the "provider_response_snapshot" field.
func (u *SecurityDepositRefundUpsertOne) ClearProviderResponseSnapshot() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearProviderResponseSnapshot()
	})
}

// SetExternalRefundID sets the "external_refund_id" field.
func (u *SecurityDepositRefundUpsertOne) SetExternalRefundID(v string) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetExternalRefundID(v)
	})
}

// UpdateExternalRefundID sets the "external_refund_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateExternalRefundID() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateExternalRefundID()
	})
}

// ClearExternalRefundID clears the value of the "external_refund_id" field.
func (u *SecurityDepositRefundUpsertOne) ClearExternalRefundID() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearExternalRefundID()
	})
}

// SetExternalRefundedAt sets the "external_refunded_at" field.
func (u *SecurityDepositRefundUpsertOne) SetExternalRefundedAt(v time.Time) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetExternalRefundedAt(v)
	})
}

// UpdateExternalRefundedAt sets the "external_refunded_at" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateExternalRefundedAt() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateExternalRefundedAt()
	})
}

// ClearExternalRefundedAt clears the value of the "external_refunded_at" field.
func (u *SecurityDepositRefundUpsertOne) ClearExternalRefundedAt() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearExternalRefundedAt()
	})
}

// SetExternalEvidence sets the "external_evidence" field.
func (u *SecurityDepositRefundUpsertOne) SetExternalEvidence(v map[string]interface{}) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetExternalEvidence(v)
	})
}

// UpdateExternalEvidence sets the "external_evidence" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateExternalEvidence() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateExternalEvidence()
	})
}

// ClearExternalEvidence clears the value of the "external_evidence" field.
func (u *SecurityDepositRefundUpsertOne) ClearExternalEvidence() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearExternalEvidence()
	})
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *SecurityDepositRefundUpsertOne) SetSubmittedAt(v time.Time) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetSubmittedAt(v)
	})
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateSubmittedAt() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateSubmittedAt()
	})
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (u *SecurityDepositRefundUpsertOne) ClearSubmittedAt() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearSubmittedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *SecurityDepositRefundUpsertOne) SetCompletedAt(v time.Time) *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertOne) UpdateCompletedAt() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *SecurityDepositRefundUpsertOne) ClearCompletedAt() *SecurityDepositRefundUpsertOne {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *SecurityDepositRefundUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SecurityDepositRefundCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SecurityDepositRefundUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SecurityDepositRefundUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SecurityDepositRefundUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SecurityDepositRefundCreateBulk is the builder for creating many SecurityDepositRefund entities in bulk.
type SecurityDepositRefundCreateBulk struct {
	config
	err      error
	builders []*SecurityDepositRefundCreate
	conflict []sql.ConflictOption
}

// Save creates the SecurityDepositRefund entities in the database.
func (_c *SecurityDepositRefundCreateBulk) Save(ctx context.Context) ([]*SecurityDepositRefund, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SecurityDepositRefund, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SecurityDepositRefundMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SecurityDepositRefundCreateBulk) SaveX(ctx context.Context) []*SecurityDepositRefund {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SecurityDepositRefundCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SecurityDepositRefundCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SecurityDepositRefund.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SecurityDepositRefundUpsert) {
//			SetRefundID(v+v).
//		}).
//		Exec(ctx)
func (_c *SecurityDepositRefundCreateBulk) OnConflict(opts ...sql.ConflictOption) *SecurityDepositRefundUpsertBulk {
	_c.conflict = opts
	return &SecurityDepositRefundUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SecurityDepositRefund.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SecurityDepositRefundCreateBulk) OnConflictColumns(columns ...string) *SecurityDepositRefundUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SecurityDepositRefundUpsertBulk{
		create: _c,
	}
}

// SecurityDepositRefundUpsertBulk is the builder for "upsert"-ing
// a bulk of SecurityDepositRefund nodes.
type SecurityDepositRefundUpsertBulk struct {
	create *SecurityDepositRefundCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SecurityDepositRefund.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SecurityDepositRefundUpsertBulk) UpdateNewValues() *SecurityDepositRefundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(securitydepositrefund.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SecurityDepositRefund.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SecurityDepositRefundUpsertBulk) Ignore() *SecurityDepositRefundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SecurityDepositRefundUpsertBulk) DoNothing() *SecurityDepositRefundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SecurityDepositRefundCreateBulk.OnConflict
// documentation for more info.
func (u *SecurityDepositRefundUpsertBulk) Update(set func(*SecurityDepositRefundUpsert)) *SecurityDepositRefundUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SecurityDepositRefundUpsert{UpdateSet: update})
	}))
	return u
}

// SetRefundID sets the "refund_id" field.
func (u *SecurityDepositRefundUpsertBulk) SetRefundID(v string) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetRefundID(v)
	})
}

// UpdateRefundID sets the "refund_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateRefundID() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateRefundID()
	})
}

// SetUserID sets the "user_id" field.
func (u *SecurityDepositRefundUpsertBulk) SetUserID(v int64) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SecurityDepositRefundUpsertBulk) AddUserID(v int64) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateUserID() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateUserID()
	})
}

// SetLotID sets the "lot_id" field.
func (u *SecurityDepositRefundUpsertBulk) SetLotID(v int64) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetLotID(v)
	})
}

// AddLotID adds v to the "lot_id" field.
func (u *SecurityDepositRefundUpsertBulk) AddLotID(v int64) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.AddLotID(v)
	})
}

// UpdateLotID sets the "lot_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateLotID() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateLotID()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *SecurityDepositRefundUpsertBulk) SetPaymentOrderID(v int64) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *SecurityDepositRefundUpsertBulk) AddPaymentOrderID(v int64) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdatePaymentOrderID() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// SetPrincipalCents sets the "principal_cents" field.
func (u *SecurityDepositRefundUpsertBulk) SetPrincipalCents(v int64) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetPrincipalCents(v)
	})
}

// AddPrincipalCents adds v to the "principal_cents" field.
func (u *SecurityDepositRefundUpsertBulk) AddPrincipalCents(v int64) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.AddPrincipalCents(v)
	})
}

// UpdatePrincipalCents sets the "principal_cents" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdatePrincipalCents() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdatePrincipalCents()
	})
}

// SetGatewayAmount sets the "gateway_amount" field.
func (u *SecurityDepositRefundUpsertBulk) SetGatewayAmount(v string) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetGatewayAmount(v)
	})
}

// UpdateGatewayAmount sets the "gateway_amount" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateGatewayAmount() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateGatewayAmount()
	})
}

// SetGatewayCurrency sets the "gateway_currency" field.
func (u *SecurityDepositRefundUpsertBulk) SetGatewayCurrency(v string) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetGatewayCurrency(v)
	})
}

// UpdateGatewayCurrency sets the "gateway_currency" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateGatewayCurrency() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateGatewayCurrency()
	})
}

// SetMode sets the "mode" field.
func (u *SecurityDepositRefundUpsertBulk) SetMode(v securitydepositrefund.Mode) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateMode() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateMode()
	})
}

// SetState sets the "state" field.
func (u *SecurityDepositRefundUpsertBulk) SetState(v string) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateState() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateState()
	})
}

// SetRequestedBy sets the "requested_by" field.
func (u *SecurityDepositRefundUpsertBulk) SetRequestedBy(v int64) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetRequestedBy(v)
	})
}

// AddRequestedBy adds v to the "requested_by" field.
func (u *SecurityDepositRefundUpsertBulk) AddRequestedBy(v int64) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.AddRequestedBy(v)
	})
}

// UpdateRequestedBy sets the "requested_by" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateRequestedBy() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateRequestedBy()
	})
}

// ClearRequestedBy clears the value of the "requested_by" field.
func (u *SecurityDepositRefundUpsertBulk) ClearRequestedBy() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearRequestedBy()
	})
}

// SetReason sets the "reason" field.
func (u *SecurityDepositRefundUpsertBulk) SetReason(v string) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateReason() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *SecurityDepositRefundUpsertBulk) ClearReason() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearReason()
	})
}

// SetQuoteHash sets the "quote_hash" field.
func (u *SecurityDepositRefundUpsertBulk) SetQuoteHash(v string) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetQuoteHash(v)
	})
}

// UpdateQuoteHash sets the "quote_hash" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateQuoteHash() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateQuoteHash()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *SecurityDepositRefundUpsertBulk) SetIdempotencyKey(v string) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateIdempotencyKey() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// SetProviderRequestID sets the "provider_request_id" field.
func (u *SecurityDepositRefundUpsertBulk) SetProviderRequestID(v string) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetProviderRequestID(v)
	})
}

// UpdateProviderRequestID sets the "provider_request_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateProviderRequestID() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateProviderRequestID()
	})
}

// ClearProviderRequestID clears the value of the "provider_request_id" field.
func (u *SecurityDepositRefundUpsertBulk) ClearProviderRequestID() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearProviderRequestID()
	})
}

// SetProviderResponseSnapshot sets the "provider_response_snapshot" field.
func (u *SecurityDepositRefundUpsertBulk) SetProviderResponseSnapshot(v map[string]interface{}) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetProviderResponseSnapshot(v)
	})
}

// UpdateProviderResponseSnapshot sets the "provider_response_snapshot" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateProviderResponseSnapshot() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateProviderResponseSnapshot()
	})
}

// ClearProviderResponseSnapshot clears the value of the "provider_response_snapshot" field.
func (u *SecurityDepositRefundUpsertBulk) ClearProviderResponseSnapshot() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearProviderResponseSnapshot()
	})
}

// SetExternalRefundID sets the "external_refund_id" field.
func (u *SecurityDepositRefundUpsertBulk) SetExternalRefundID(v string) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetExternalRefundID(v)
	})
}

// UpdateExternalRefundID sets the "external_refund_id" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateExternalRefundID() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateExternalRefundID()
	})
}

// ClearExternalRefundID clears the value of the "external_refund_id" field.
func (u *SecurityDepositRefundUpsertBulk) ClearExternalRefundID() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearExternalRefundID()
	})
}

// SetExternalRefundedAt sets the "external_refunded_at" field.
func (u *SecurityDepositRefundUpsertBulk) SetExternalRefundedAt(v time.Time) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetExternalRefundedAt(v)
	})
}

// UpdateExternalRefundedAt sets the "external_refunded_at" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateExternalRefundedAt() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateExternalRefundedAt()
	})
}

// ClearExternalRefundedAt clears the value of the "external_refunded_at" field.
func (u *SecurityDepositRefundUpsertBulk) ClearExternalRefundedAt() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearExternalRefundedAt()
	})
}

// SetExternalEvidence sets the "external_evidence" field.
func (u *SecurityDepositRefundUpsertBulk) SetExternalEvidence(v map[string]interface{}) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetExternalEvidence(v)
	})
}

// UpdateExternalEvidence sets the "external_evidence" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateExternalEvidence() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateExternalEvidence()
	})
}

// ClearExternalEvidence clears the value of the "external_evidence" field.
func (u *SecurityDepositRefundUpsertBulk) ClearExternalEvidence() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearExternalEvidence()
	})
}

// SetSubmittedAt sets the "submitted_at" field.
func (u *SecurityDepositRefundUpsertBulk) SetSubmittedAt(v time.Time) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetSubmittedAt(v)
	})
}

// UpdateSubmittedAt sets the "submitted_at" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateSubmittedAt() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateSubmittedAt()
	})
}

// ClearSubmittedAt clears the value of the "submitted_at" field.
func (u *SecurityDepositRefundUpsertBulk) ClearSubmittedAt() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearSubmittedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *SecurityDepositRefundUpsertBulk) SetCompletedAt(v time.Time) *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *SecurityDepositRefundUpsertBulk) UpdateCompletedAt() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *SecurityDepositRefundUpsertBulk) ClearCompletedAt() *SecurityDepositRefundUpsertBulk {
	return u.Update(func(s *SecurityDepositRefundUpsert) {
		s.ClearCompletedAt()
	})
}

// Exec executes the query.
func (u *SecurityDepositRefundUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SecurityDepositRefundCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SecurityDepositRefundCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SecurityDepositRefundUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
