// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/securitydepositviolation"
)

// SecurityDepositViolationUpdate is the builder for updating SecurityDepositViolation entities.
type SecurityDepositViolationUpdate struct {
	config
	hooks    []Hook
	mutation *SecurityDepositViolationMutation
}

// Where appends a list predicates to the SecurityDepositViolationUpdate builder.
func (_u *SecurityDepositViolationUpdate) Where(ps ...predicate.SecurityDepositViolation) *SecurityDepositViolationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEventKey sets the "event_key" field.
func (_u *SecurityDepositViolationUpdate) SetEventKey(v string) *SecurityDepositViolationUpdate {
	_u.mutation.SetEventKey(v)
	return _u
}

// SetNillableEventKey sets the "event_key" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableEventKey(v *string) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetEventKey(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *SecurityDepositViolationUpdate) SetRequestID(v string) *SecurityDepositViolationUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableRequestID(v *string) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetUpstreamResponseID sets the "upstream_response_id" field.
func (_u *SecurityDepositViolationUpdate) SetUpstreamResponseID(v string) *SecurityDepositViolationUpdate {
	_u.mutation.SetUpstreamResponseID(v)
	return _u
}

// SetNillableUpstreamResponseID sets the "upstream_response_id" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableUpstreamResponseID(v *string) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetUpstreamResponseID(*v)
	}
	return _u
}

// ClearUpstreamResponseID clears the value of the "upstream_response_id" field.
func (_u *SecurityDepositViolationUpdate) ClearUpstreamResponseID() *SecurityDepositViolationUpdate {
	_u.mutation.ClearUpstreamResponseID()
	return _u
}

// SetTurnIndex sets the "turn_index" field.
func (_u *SecurityDepositViolationUpdate) SetTurnIndex(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.ResetTurnIndex()
	_u.mutation.SetTurnIndex(v)
	return _u
}

// SetNillableTurnIndex sets the "turn_index" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableTurnIndex(v *int64) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetTurnIndex(*v)
	}
	return _u
}

// AddTurnIndex adds value to the "turn_index" field.
func (_u *SecurityDepositViolationUpdate) AddTurnIndex(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.AddTurnIndex(v)
	return _u
}

// ClearTurnIndex clears the value of the "turn_index" field.
func (_u *SecurityDepositViolationUpdate) ClearTurnIndex() *SecurityDepositViolationUpdate {
	_u.mutation.ClearTurnIndex()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SecurityDepositViolationUpdate) SetUserID(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableUserID(v *int64) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SecurityDepositViolationUpdate) AddUserID(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *SecurityDepositViolationUpdate) SetAPIKeyID(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableAPIKeyID(v *int64) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *SecurityDepositViolationUpdate) AddAPIKeyID(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SecurityDepositViolationUpdate) SetGroupID(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableGroupID(v *int64) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SecurityDepositViolationUpdate) AddGroupID(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetPolicyCode sets the "policy_code" field.
func (_u *SecurityDepositViolationUpdate) SetPolicyCode(v string) *SecurityDepositViolationUpdate {
	_u.mutation.SetPolicyCode(v)
	return _u
}

// SetNillablePolicyCode sets the "policy_code" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillablePolicyCode(v *string) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetPolicyCode(*v)
	}
	return _u
}

// SetDetectorVersion sets the "detector_version" field.
func (_u *SecurityDepositViolationUpdate) SetDetectorVersion(v string) *SecurityDepositViolationUpdate {
	_u.mutation.SetDetectorVersion(v)
	return _u
}

// SetNillableDetectorVersion sets the "detector_version" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableDetectorVersion(v *string) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetDetectorVersion(*v)
	}
	return _u
}

// SetBaseRequiredSnapshotCents sets the "base_required_snapshot_cents" field.
func (_u *SecurityDepositViolationUpdate) SetBaseRequiredSnapshotCents(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.ResetBaseRequiredSnapshotCents()
	_u.mutation.SetBaseRequiredSnapshotCents(v)
	return _u
}

// SetNillableBaseRequiredSnapshotCents sets the "base_required_snapshot_cents" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableBaseRequiredSnapshotCents(v *int64) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetBaseRequiredSnapshotCents(*v)
	}
	return _u
}

// AddBaseRequiredSnapshotCents adds value to the "base_required_snapshot_cents" field.
func (_u *SecurityDepositViolationUpdate) AddBaseRequiredSnapshotCents(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.AddBaseRequiredSnapshotCents(v)
	return _u
}

// SetRiskMultiplierBefore sets the "risk_multiplier_before" field.
func (_u *SecurityDepositViolationUpdate) SetRiskMultiplierBefore(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.ResetRiskMultiplierBefore()
	_u.mutation.SetRiskMultiplierBefore(v)
	return _u
}

// SetNillableRiskMultiplierBefore sets the "risk_multiplier_before" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableRiskMultiplierBefore(v *int64) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetRiskMultiplierBefore(*v)
	}
	return _u
}

// AddRiskMultiplierBefore adds value to the "risk_multiplier_before" field.
func (_u *SecurityDepositViolationUpdate) AddRiskMultiplierBefore(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.AddRiskMultiplierBefore(v)
	return _u
}

// SetRequiredSnapshotCents sets the "required_snapshot_cents" field.
func (_u *SecurityDepositViolationUpdate) SetRequiredSnapshotCents(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.ResetRequiredSnapshotCents()
	_u.mutation.SetRequiredSnapshotCents(v)
	return _u
}

// SetNillableRequiredSnapshotCents sets the "required_snapshot_cents" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableRequiredSnapshotCents(v *int64) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetRequiredSnapshotCents(*v)
	}
	return _u
}

// AddRequiredSnapshotCents adds value to the "required_snapshot_cents" field.
func (_u *SecurityDepositViolationUpdate) AddRequiredSnapshotCents(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.AddRequiredSnapshotCents(v)
	return _u
}

// SetRiskMultiplierAfter sets the "risk_multiplier_after" field.
func (_u *SecurityDepositViolationUpdate) SetRiskMultiplierAfter(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.ResetRiskMultiplierAfter()
	_u.mutation.SetRiskMultiplierAfter(v)
	return _u
}

// SetNillableRiskMultiplierAfter sets the "risk_multiplier_after" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableRiskMultiplierAfter(v *int64) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetRiskMultiplierAfter(*v)
	}
	return _u
}

// AddRiskMultiplierAfter adds value to the "risk_multiplier_after" field.
func (_u *SecurityDepositViolationUpdate) AddRiskMultiplierAfter(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.AddRiskMultiplierAfter(v)
	return _u
}

// SetForfeitedCents sets the "forfeited_cents" field.
func (_u *SecurityDepositViolationUpdate) SetForfeitedCents(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.ResetForfeitedCents()
	_u.mutation.SetForfeitedCents(v)
	return _u
}

// SetNillableForfeitedCents sets the "forfeited_cents" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableForfeitedCents(v *int64) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetForfeitedCents(*v)
	}
	return _u
}

// AddForfeitedCents adds value to the "forfeited_cents" field.
func (_u *SecurityDepositViolationUpdate) AddForfeitedCents(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.AddForfeitedCents(v)
	return _u
}

// SetShortfallCents sets the "shortfall_cents" field.
func (_u *SecurityDepositViolationUpdate) SetShortfallCents(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.ResetShortfallCents()
	_u.mutation.SetShortfallCents(v)
	return _u
}

// SetNillableShortfallCents sets the "shortfall_cents" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableShortfallCents(v *int64) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetShortfallCents(*v)
	}
	return _u
}

// AddShortfallCents adds value to the "shortfall_cents" field.
func (_u *SecurityDepositViolationUpdate) AddShortfallCents(v int64) *SecurityDepositViolationUpdate {
	_u.mutation.AddShortfallCents(v)
	return _u
}

// SetState sets the "state" field.
func (_u *SecurityDepositViolationUpdate) SetState(v string) *SecurityDepositViolationUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableState(v *string) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *SecurityDepositViolationUpdate) SetErrorCode(v string) *SecurityDepositViolationUpdate {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableErrorCode(v *string) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *SecurityDepositViolationUpdate) ClearErrorCode() *SecurityDepositViolationUpdate {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *SecurityDepositViolationUpdate) SetRetryCount(v int) *SecurityDepositViolationUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableRetryCount(v *int) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *SecurityDepositViolationUpdate) AddRetryCount(v int) *SecurityDepositViolationUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetAPIKeyNameSnapshot sets the "api_key_name_snapshot" field.
func (_u *SecurityDepositViolationUpdate) SetAPIKeyNameSnapshot(v string) *SecurityDepositViolationUpdate {
	_u.mutation.SetAPIKeyNameSnapshot(v)
	return _u
}

// SetNillableAPIKeyNameSnapshot sets the "api_key_name_snapshot" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableAPIKeyNameSnapshot(v *string) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetAPIKeyNameSnapshot(*v)
	}
	return _u
}

// SetGroupNameSnapshot sets the "group_name_snapshot" field.
func (_u *SecurityDepositViolationUpdate) SetGroupNameSnapshot(v string) *SecurityDepositViolationUpdate {
	_u.mutation.SetGroupNameSnapshot(v)
	return _u
}

// SetNillableGroupNameSnapshot sets the "group_name_snapshot" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableGroupNameSnapshot(v *string) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetGroupNameSnapshot(*v)
	}
	return _u
}

// SetProcessedAt sets the "processed_at" field.
func (_u *SecurityDepositViolationUpdate) SetProcessedAt(v time.Time) *SecurityDepositViolationUpdate {
	_u.mutation.SetProcessedAt(v)
	return _u
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdate) SetNillableProcessedAt(v *time.Time) *SecurityDepositViolationUpdate {
	if v != nil {
		_u.SetProcessedAt(*v)
	}
	return _u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (_u *SecurityDepositViolationUpdate) ClearProcessedAt() *SecurityDepositViolationUpdate {
	_u.mutation.ClearProcessedAt()
	return _u
}

// Mutation returns the SecurityDepositViolationMutation object of the builder.
func (_u *SecurityDepositViolationUpdate) Mutation() *SecurityDepositViolationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SecurityDepositViolationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SecurityDepositViolationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SecurityDepositViolationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SecurityDepositViolationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SecurityDepositViolationUpdate) check() error {
	if v, ok := _u.mutation.EventKey(); ok {
		if err := securitydepositviolation.EventKeyValidator(v); err != nil {
			return &ValidationError{Name: "event_key", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.event_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := securitydepositviolation.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamResponseID(); ok {
		if err := securitydepositviolation.UpstreamResponseIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_response_id", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.upstream_response_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TurnIndex(); ok {
		if err := securitydepositviolation.TurnIndexValidator(v); err != nil {
			return &ValidationError{Name: "turn_index", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.turn_index": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PolicyCode(); ok {
		if err := securitydepositviolation.PolicyCodeValidator(v); err != nil {
			return &ValidationError{Name: "policy_code", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.policy_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DetectorVersion(); ok {
		if err := securitydepositviolation.DetectorVersionValidator(v); err != nil {
			return &ValidationError{Name: "detector_version", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.detector_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseRequiredSnapshotCents(); ok {
		if err := securitydepositviolation.BaseRequiredSnapshotCentsValidator(v); err != nil {
			return &ValidationError{Name: "base_required_snapshot_cents", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.base_required_snapshot_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RiskMultiplierBefore(); ok {
		if err := securitydepositviolation.RiskMultiplierBeforeValidator(v); err != nil {
			return &ValidationError{Name: "risk_multiplier_before", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.risk_multiplier_before": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequiredSnapshotCents(); ok {
		if err := securitydepositviolation.RequiredSnapshotCentsValidator(v); err != nil {
			return &ValidationError{Name: "required_snapshot_cents", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.required_snapshot_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RiskMultiplierAfter(); ok {
		if err := securitydepositviolation.RiskMultiplierAfterValidator(v); err != nil {
			return &ValidationError{Name: "risk_multiplier_after", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.risk_multiplier_after": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ForfeitedCents(); ok {
		if err := securitydepositviolation.ForfeitedCentsValidator(v); err != nil {
			return &ValidationError{Name: "forfeited_cents", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.forfeited_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ShortfallCents(); ok {
		if err := securitydepositviolation.ShortfallCentsValidator(v); err != nil {
			return &ValidationError{Name: "shortfall_cents", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.shortfall_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := securitydepositviolation.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := securitydepositviolation.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RetryCount(); ok {
		if err := securitydepositviolation.RetryCountValidator(v); err != nil {
			return &ValidationError{Name: "retry_count", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.retry_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyNameSnapshot(); ok {
		if err := securitydepositviolation.APIKeyNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "api_key_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.api_key_name_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupNameSnapshot(); ok {
		if err := securitydepositviolation.GroupNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "group_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.group_name_snapshot": %w`, err)}
		}
	}
	return nil
}

func (_u *SecurityDepositViolationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(securitydepositviolation.Table, securitydepositviolation.Columns, sqlgraph.NewFieldSpec(securitydepositviolation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventKey(); ok {
		_spec.SetField(securitydepositviolation.FieldEventKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(securitydepositviolation.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamResponseID(); ok {
		_spec.SetField(securitydepositviolation.FieldUpstreamResponseID, field.TypeString, value)
	}
	if _u.mutation.UpstreamResponseIDCleared() {
		_spec.ClearField(securitydepositviolation.FieldUpstreamResponseID, field.TypeString)
	}
	if value, ok := _u.mutation.TurnIndex(); ok {
		_spec.SetField(securitydepositviolation.FieldTurnIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTurnIndex(); ok {
		_spec.AddField(securitydepositviolation.FieldTurnIndex, field.TypeInt64, value)
	}
	if _u.mutation.TurnIndexCleared() {
		_spec.ClearField(securitydepositviolation.FieldTurnIndex, field.TypeInt64)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(securitydepositviolation.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(securitydepositviolation.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(securitydepositviolation.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(securitydepositviolation.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(securitydepositviolation.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(securitydepositviolation.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PolicyCode(); ok {
		_spec.SetField(securitydepositviolation.FieldPolicyCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DetectorVersion(); ok {
		_spec.SetField(securitydepositviolation.FieldDetectorVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseRequiredSnapshotCents(); ok {
		_spec.SetField(securitydepositviolation.FieldBaseRequiredSnapshotCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBaseRequiredSnapshotCents(); ok {
		_spec.AddField(securitydepositviolation.FieldBaseRequiredSnapshotCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RiskMultiplierBefore(); ok {
		_spec.SetField(securitydepositviolation.FieldRiskMultiplierBefore, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRiskMultiplierBefore(); ok {
		_spec.AddField(securitydepositviolation.FieldRiskMultiplierBefore, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequiredSnapshotCents(); ok {
		_spec.SetField(securitydepositviolation.FieldRequiredSnapshotCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequiredSnapshotCents(); ok {
		_spec.AddField(securitydepositviolation.FieldRequiredSnapshotCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RiskMultiplierAfter(); ok {
		_spec.SetField(securitydepositviolation.FieldRiskMultiplierAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRiskMultiplierAfter(); ok {
		_spec.AddField(securitydepositviolation.FieldRiskMultiplierAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ForfeitedCents(); ok {
		_spec.SetField(securitydepositviolation.FieldForfeitedCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedForfeitedCents(); ok {
		_spec.AddField(securitydepositviolation.FieldForfeitedCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ShortfallCents(); ok {
		_spec.SetField(securitydepositviolation.FieldShortfallCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedShortfallCents(); ok {
		_spec.AddField(securitydepositviolation.FieldShortfallCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(securitydepositviolation.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(securitydepositviolation.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(securitydepositviolation.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(securitydepositviolation.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(securitydepositviolation.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.APIKeyNameSnapshot(); ok {
		_spec.SetField(securitydepositviolation.FieldAPIKeyNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupNameSnapshot(); ok {
		_spec.SetField(securitydepositviolation.FieldGroupNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcessedAt(); ok {
		_spec.SetField(securitydepositviolation.FieldProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessedAtCleared() {
		_spec.ClearField(securitydepositviolation.FieldProcessedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{securitydepositviolation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SecurityDepositViolationUpdateOne is the builder for updating a single SecurityDepositViolation entity.
type SecurityDepositViolationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SecurityDepositViolationMutation
}

// SetEventKey sets the "event_key" field.
func (_u *SecurityDepositViolationUpdateOne) SetEventKey(v string) *SecurityDepositViolationUpdateOne {
	_u.mutation.SetEventKey(v)
	return _u
}

// SetNillableEventKey sets the "event_key" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableEventKey(v *string) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetEventKey(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *SecurityDepositViolationUpdateOne) SetRequestID(v string) *SecurityDepositViolationUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableRequestID(v *string) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetUpstreamResponseID sets the "upstream_response_id" field.
func (_u *SecurityDepositViolationUpdateOne) SetUpstreamResponseID(v string) *SecurityDepositViolationUpdateOne {
	_u.mutation.SetUpstreamResponseID(v)
	return _u
}

// SetNillableUpstreamResponseID sets the "upstream_response_id" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableUpstreamResponseID(v *string) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetUpstreamResponseID(*v)
	}
	return _u
}

// ClearUpstreamResponseID clears the value of the "upstream_response_id" field.
func (_u *SecurityDepositViolationUpdateOne) ClearUpstreamResponseID() *SecurityDepositViolationUpdateOne {
	_u.mutation.ClearUpstreamResponseID()
	return _u
}

// SetTurnIndex sets the "turn_index" field.
func (_u *SecurityDepositViolationUpdateOne) SetTurnIndex(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.ResetTurnIndex()
	_u.mutation.SetTurnIndex(v)
	return _u
}

// SetNillableTurnIndex sets the "turn_index" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableTurnIndex(v *int64) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetTurnIndex(*v)
	}
	return _u
}

// AddTurnIndex adds value to the "turn_index" field.
func (_u *SecurityDepositViolationUpdateOne) AddTurnIndex(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.AddTurnIndex(v)
	return _u
}

// ClearTurnIndex clears the value of the "turn_index" field.
func (_u *SecurityDepositViolationUpdateOne) ClearTurnIndex() *SecurityDepositViolationUpdateOne {
	_u.mutation.ClearTurnIndex()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SecurityDepositViolationUpdateOne) SetUserID(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableUserID(v *int64) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SecurityDepositViolationUpdateOne) AddUserID(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *SecurityDepositViolationUpdateOne) SetAPIKeyID(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableAPIKeyID(v *int64) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *SecurityDepositViolationUpdateOne) AddAPIKeyID(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *SecurityDepositViolationUpdateOne) SetGroupID(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableGroupID(v *int64) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *SecurityDepositViolationUpdateOne) AddGroupID(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetPolicyCode sets the "policy_code" field.
func (_u *SecurityDepositViolationUpdateOne) SetPolicyCode(v string) *SecurityDepositViolationUpdateOne {
	_u.mutation.SetPolicyCode(v)
	return _u
}

// SetNillablePolicyCode sets the "policy_code" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillablePolicyCode(v *string) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetPolicyCode(*v)
	}
	return _u
}

// SetDetectorVersion sets the "detector_version" field.
func (_u *SecurityDepositViolationUpdateOne) SetDetectorVersion(v string) *SecurityDepositViolationUpdateOne {
	_u.mutation.SetDetectorVersion(v)
	return _u
}

// SetNillableDetectorVersion sets the "detector_version" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableDetectorVersion(v *string) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetDetectorVersion(*v)
	}
	return _u
}

// SetBaseRequiredSnapshotCents sets the "base_required_snapshot_cents" field.
func (_u *SecurityDepositViolationUpdateOne) SetBaseRequiredSnapshotCents(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.ResetBaseRequiredSnapshotCents()
	_u.mutation.SetBaseRequiredSnapshotCents(v)
	return _u
}

// SetNillableBaseRequiredSnapshotCents sets the "base_required_snapshot_cents" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableBaseRequiredSnapshotCents(v *int64) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetBaseRequiredSnapshotCents(*v)
	}
	return _u
}

// AddBaseRequiredSnapshotCents adds value to the "base_required_snapshot_cents" field.
func (_u *SecurityDepositViolationUpdateOne) AddBaseRequiredSnapshotCents(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.AddBaseRequiredSnapshotCents(v)
	return _u
}

// SetRiskMultiplierBefore sets the "risk_multiplier_before" field.
func (_u *SecurityDepositViolationUpdateOne) SetRiskMultiplierBefore(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.ResetRiskMultiplierBefore()
	_u.mutation.SetRiskMultiplierBefore(v)
	return _u
}

// SetNillableRiskMultiplierBefore sets the "risk_multiplier_before" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableRiskMultiplierBefore(v *int64) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetRiskMultiplierBefore(*v)
	}
	return _u
}

// AddRiskMultiplierBefore adds value to the "risk_multiplier_before" field.
func (_u *SecurityDepositViolationUpdateOne) AddRiskMultiplierBefore(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.AddRiskMultiplierBefore(v)
	return _u
}

// SetRequiredSnapshotCents sets the "required_snapshot_cents" field.
func (_u *SecurityDepositViolationUpdateOne) SetRequiredSnapshotCents(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.ResetRequiredSnapshotCents()
	_u.mutation.SetRequiredSnapshotCents(v)
	return _u
}

// SetNillableRequiredSnapshotCents sets the "required_snapshot_cents" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableRequiredSnapshotCents(v *int64) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetRequiredSnapshotCents(*v)
	}
	return _u
}

// AddRequiredSnapshotCents adds value to the "required_snapshot_cents" field.
func (_u *SecurityDepositViolationUpdateOne) AddRequiredSnapshotCents(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.AddRequiredSnapshotCents(v)
	return _u
}

// SetRiskMultiplierAfter sets the "risk_multiplier_after" field.
func (_u *SecurityDepositViolationUpdateOne) SetRiskMultiplierAfter(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.ResetRiskMultiplierAfter()
	_u.mutation.SetRiskMultiplierAfter(v)
	return _u
}

// SetNillableRiskMultiplierAfter sets the "risk_multiplier_after" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableRiskMultiplierAfter(v *int64) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetRiskMultiplierAfter(*v)
	}
	return _u
}

// AddRiskMultiplierAfter adds value to the "risk_multiplier_after" field.
func (_u *SecurityDepositViolationUpdateOne) AddRiskMultiplierAfter(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.AddRiskMultiplierAfter(v)
	return _u
}

// SetForfeitedCents sets the "forfeited_cents" field.
func (_u *SecurityDepositViolationUpdateOne) SetForfeitedCents(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.ResetForfeitedCents()
	_u.mutation.SetForfeitedCents(v)
	return _u
}

// SetNillableForfeitedCents sets the "forfeited_cents" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableForfeitedCents(v *int64) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetForfeitedCents(*v)
	}
	return _u
}

// AddForfeitedCents adds value to the "forfeited_cents" field.
func (_u *SecurityDepositViolationUpdateOne) AddForfeitedCents(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.AddForfeitedCents(v)
	return _u
}

// SetShortfallCents sets the "shortfall_cents" field.
func (_u *SecurityDepositViolationUpdateOne) SetShortfallCents(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.ResetShortfallCents()
	_u.mutation.SetShortfallCents(v)
	return _u
}

// SetNillableShortfallCents sets the "shortfall_cents" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableShortfallCents(v *int64) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetShortfallCents(*v)
	}
	return _u
}

// AddShortfallCents adds value to the "shortfall_cents" field.
func (_u *SecurityDepositViolationUpdateOne) AddShortfallCents(v int64) *SecurityDepositViolationUpdateOne {
	_u.mutation.AddShortfallCents(v)
	return _u
}

// SetState sets the "state" field.
func (_u *SecurityDepositViolationUpdateOne) SetState(v string) *SecurityDepositViolationUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableState(v *string) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetErrorCode sets the "error_code" field.
func (_u *SecurityDepositViolationUpdateOne) SetErrorCode(v string) *SecurityDepositViolationUpdateOne {
	_u.mutation.SetErrorCode(v)
	return _u
}

// SetNillableErrorCode sets the "error_code" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableErrorCode(v *string) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetErrorCode(*v)
	}
	return _u
}

// ClearErrorCode clears the value of the "error_code" field.
func (_u *SecurityDepositViolationUpdateOne) ClearErrorCode() *SecurityDepositViolationUpdateOne {
	_u.mutation.ClearErrorCode()
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *SecurityDepositViolationUpdateOne) SetRetryCount(v int) *SecurityDepositViolationUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableRetryCount(v *int) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *SecurityDepositViolationUpdateOne) AddRetryCount(v int) *SecurityDepositViolationUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetAPIKeyNameSnapshot sets the "api_key_name_snapshot" field.
func (_u *SecurityDepositViolationUpdateOne) SetAPIKeyNameSnapshot(v string) *SecurityDepositViolationUpdateOne {
	_u.mutation.SetAPIKeyNameSnapshot(v)
	return _u
}

// SetNillableAPIKeyNameSnapshot sets the "api_key_name_snapshot" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableAPIKeyNameSnapshot(v *string) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetAPIKeyNameSnapshot(*v)
	}
	return _u
}

// SetGroupNameSnapshot sets the "group_name_snapshot" field.
func (_u *SecurityDepositViolationUpdateOne) SetGroupNameSnapshot(v string) *SecurityDepositViolationUpdateOne {
	_u.mutation.SetGroupNameSnapshot(v)
	return _u
}

// SetNillableGroupNameSnapshot sets the "group_name_snapshot" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableGroupNameSnapshot(v *string) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetGroupNameSnapshot(*v)
	}
	return _u
}

// SetProcessedAt sets the "processed_at" field.
func (_u *SecurityDepositViolationUpdateOne) SetProcessedAt(v time.Time) *SecurityDepositViolationUpdateOne {
	_u.mutation.SetProcessedAt(v)
	return _u
}

// SetNillableProcessedAt sets the "processed_at" field if the given value is not nil.
func (_u *SecurityDepositViolationUpdateOne) SetNillableProcessedAt(v *time.Time) *SecurityDepositViolationUpdateOne {
	if v != nil {
		_u.SetProcessedAt(*v)
	}
	return _u
}

// ClearProcessedAt clears the value of the "processed_at" field.
func (_u *SecurityDepositViolationUpdateOne) ClearProcessedAt() *SecurityDepositViolationUpdateOne {
	_u.mutation.ClearProcessedAt()
	return _u
}

// Mutation returns the SecurityDepositViolationMutation object of the builder.
func (_u *SecurityDepositViolationUpdateOne) Mutation() *SecurityDepositViolationMutation {
	return _u.mutation
}

// Where appends a list predicates to the SecurityDepositViolationUpdate builder.
func (_u *SecurityDepositViolationUpdateOne) Where(ps ...predicate.SecurityDepositViolation) *SecurityDepositViolationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SecurityDepositViolationUpdateOne) Select(field string, fields ...string) *SecurityDepositViolationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SecurityDepositViolation entity.
func (_u *SecurityDepositViolationUpdateOne) Save(ctx context.Context) (*SecurityDepositViolation, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SecurityDepositViolationUpdateOne) SaveX(ctx context.Context) *SecurityDepositViolation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SecurityDepositViolationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SecurityDepositViolationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SecurityDepositViolationUpdateOne) check() error {
	if v, ok := _u.mutation.EventKey(); ok {
		if err := securitydepositviolation.EventKeyValidator(v); err != nil {
			return &ValidationError{Name: "event_key", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.event_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := securitydepositviolation.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamResponseID(); ok {
		if err := securitydepositviolation.UpstreamResponseIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_response_id", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.upstream_response_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TurnIndex(); ok {
		if err := securitydepositviolation.TurnIndexValidator(v); err != nil {
			return &ValidationError{Name: "turn_index", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.turn_index": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PolicyCode(); ok {
		if err := securitydepositviolation.PolicyCodeValidator(v); err != nil {
			return &ValidationError{Name: "policy_code", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.policy_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DetectorVersion(); ok {
		if err := securitydepositviolation.DetectorVersionValidator(v); err != nil {
			return &ValidationError{Name: "detector_version", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.detector_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseRequiredSnapshotCents(); ok {
		if err := securitydepositviolation.BaseRequiredSnapshotCentsValidator(v); err != nil {
			return &ValidationError{Name: "base_required_snapshot_cents", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.base_required_snapshot_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RiskMultiplierBefore(); ok {
		if err := securitydepositviolation.RiskMultiplierBeforeValidator(v); err != nil {
			return &ValidationError{Name: "risk_multiplier_before", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.risk_multiplier_before": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequiredSnapshotCents(); ok {
		if err := securitydepositviolation.RequiredSnapshotCentsValidator(v); err != nil {
			return &ValidationError{Name: "required_snapshot_cents", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.required_snapshot_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RiskMultiplierAfter(); ok {
		if err := securitydepositviolation.RiskMultiplierAfterValidator(v); err != nil {
			return &ValidationError{Name: "risk_multiplier_after", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.risk_multiplier_after": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ForfeitedCents(); ok {
		if err := securitydepositviolation.ForfeitedCentsValidator(v); err != nil {
			return &ValidationError{Name: "forfeited_cents", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.forfeited_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ShortfallCents(); ok {
		if err := securitydepositviolation.ShortfallCentsValidator(v); err != nil {
			return &ValidationError{Name: "shortfall_cents", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.shortfall_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.State(); ok {
		if err := securitydepositviolation.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ErrorCode(); ok {
		if err := securitydepositviolation.ErrorCodeValidator(v); err != nil {
			return &ValidationError{Name: "error_code", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.error_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RetryCount(); ok {
		if err := securitydepositviolation.RetryCountValidator(v); err != nil {
			return &ValidationError{Name: "retry_count", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.retry_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIKeyNameSnapshot(); ok {
		if err := securitydepositviolation.APIKeyNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "api_key_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.api_key_name_snapshot": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupNameSnapshot(); ok {
		if err := securitydepositviolation.GroupNameSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "group_name_snapshot", err: fmt.Errorf(`ent: validator failed for field "SecurityDepositViolation.group_name_snapshot": %w`, err)}
		}
	}
	return nil
}

func (_u *SecurityDepositViolationUpdateOne) sqlSave(ctx context.Context) (_node *SecurityDepositViolation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(securitydepositviolation.Table, securitydepositviolation.Columns, sqlgraph.NewFieldSpec(securitydepositviolation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SecurityDepositViolation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, securitydepositviolation.FieldID)
		for _, f := range fields {
			if !securitydepositviolation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != securitydepositviolation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventKey(); ok {
		_spec.SetField(securitydepositviolation.FieldEventKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(securitydepositviolation.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamResponseID(); ok {
		_spec.SetField(securitydepositviolation.FieldUpstreamResponseID, field.TypeString, value)
	}
	if _u.mutation.UpstreamResponseIDCleared() {
		_spec.ClearField(securitydepositviolation.FieldUpstreamResponseID, field.TypeString)
	}
	if value, ok := _u.mutation.TurnIndex(); ok {
		_spec.SetField(securitydepositviolation.FieldTurnIndex, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTurnIndex(); ok {
		_spec.AddField(securitydepositviolation.FieldTurnIndex, field.TypeInt64, value)
	}
	if _u.mutation.TurnIndexCleared() {
		_spec.ClearField(securitydepositviolation.FieldTurnIndex, field.TypeInt64)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(securitydepositviolation.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(securitydepositviolation.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(securitydepositviolation.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(securitydepositviolation.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(securitydepositviolation.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(securitydepositviolation.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PolicyCode(); ok {
		_spec.SetField(securitydepositviolation.FieldPolicyCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.DetectorVersion(); ok {
		_spec.SetField(securitydepositviolation.FieldDetectorVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseRequiredSnapshotCents(); ok {
		_spec.SetField(securitydepositviolation.FieldBaseRequiredSnapshotCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBaseRequiredSnapshotCents(); ok {
		_spec.AddField(securitydepositviolation.FieldBaseRequiredSnapshotCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RiskMultiplierBefore(); ok {
		_spec.SetField(securitydepositviolation.FieldRiskMultiplierBefore, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRiskMultiplierBefore(); ok {
		_spec.AddField(securitydepositviolation.FieldRiskMultiplierBefore, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RequiredSnapshotCents(); ok {
		_spec.SetField(securitydepositviolation.FieldRequiredSnapshotCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRequiredSnapshotCents(); ok {
		_spec.AddField(securitydepositviolation.FieldRequiredSnapshotCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.RiskMultiplierAfter(); ok {
		_spec.SetField(securitydepositviolation.FieldRiskMultiplierAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRiskMultiplierAfter(); ok {
		_spec.AddField(securitydepositviolation.FieldRiskMultiplierAfter, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ForfeitedCents(); ok {
		_spec.SetField(securitydepositviolation.FieldForfeitedCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedForfeitedCents(); ok {
		_spec.AddField(securitydepositviolation.FieldForfeitedCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ShortfallCents(); ok {
		_spec.SetField(securitydepositviolation.FieldShortfallCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedShortfallCents(); ok {
		_spec.AddField(securitydepositviolation.FieldShortfallCents, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(securitydepositviolation.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorCode(); ok {
		_spec.SetField(securitydepositviolation.FieldErrorCode, field.TypeString, value)
	}
	if _u.mutation.ErrorCodeCleared() {
		_spec.ClearField(securitydepositviolation.FieldErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(securitydepositviolation.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(securitydepositviolation.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.APIKeyNameSnapshot(); ok {
		_spec.SetField(securitydepositviolation.FieldAPIKeyNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.GroupNameSnapshot(); ok {
		_spec.SetField(securitydepositviolation.FieldGroupNameSnapshot, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProcessedAt(); ok {
		_spec.SetField(securitydepositviolation.FieldProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessedAtCleared() {
		_spec.ClearField(securitydepositviolation.FieldProcessedAt, field.TypeTime)
	}
	_node = &SecurityDepositViolation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{securitydepositviolation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
