// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/securitydepositledger"
)

// SecurityDepositLedger is the model entity for the SecurityDepositLedger schema.
type SecurityDepositLedger struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// LotID holds the value of the "lot_id" field.
	LotID int64 `json:"lot_id,omitempty"`
	// BucketType holds the value of the "bucket_type" field.
	BucketType securitydepositledger.BucketType `json:"bucket_type,omitempty"`
	// EntryType holds the value of the "entry_type" field.
	EntryType securitydepositledger.EntryType `json:"entry_type,omitempty"`
	// DeltaCents holds the value of the "delta_cents" field.
	DeltaCents int64 `json:"delta_cents,omitempty"`
	// ReservedDeltaCents holds the value of the "reserved_delta_cents" field.
	ReservedDeltaCents int64 `json:"reserved_delta_cents,omitempty"`
	// BucketBalanceAfterCents holds the value of the "bucket_balance_after_cents" field.
	BucketBalanceAfterCents int64 `json:"bucket_balance_after_cents,omitempty"`
	// BucketReservedAfterCents holds the value of the "bucket_reserved_after_cents" field.
	BucketReservedAfterCents int64 `json:"bucket_reserved_after_cents,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID *int64 `json:"api_key_id,omitempty"`
	// ViolationID holds the value of the "violation_id" field.
	ViolationID *int64 `json:"violation_id,omitempty"`
	// RefundID holds the value of the "refund_id" field.
	RefundID *int64 `json:"refund_id,omitempty"`
	// PaymentOrderID holds the value of the "payment_order_id" field.
	PaymentOrderID *int64 `json:"payment_order_id,omitempty"`
	// OperatorID holds the value of the "operator_id" field.
	OperatorID *int64 `json:"operator_id,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SecurityDepositLedger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case securitydepositledger.FieldID, securitydepositledger.FieldUserID, securitydepositledger.FieldLotID, securitydepositledger.FieldDeltaCents, securitydepositledger.FieldReservedDeltaCents, securitydepositledger.FieldBucketBalanceAfterCents, securitydepositledger.FieldBucketReservedAfterCents, securitydepositledger.FieldGroupID, securitydepositledger.FieldAPIKeyID, securitydepositledger.FieldViolationID, securitydepositledger.FieldRefundID, securitydepositledger.FieldPaymentOrderID, securitydepositledger.FieldOperatorID:
			values[i] = new(sql.NullInt64)
		case securitydepositledger.FieldBucketType, securitydepositledger.FieldEntryType, securitydepositledger.FieldReason, securitydepositledger.FieldIdempotencyKey:
			values[i] = new(sql.NullString)
		case securitydepositledger.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SecurityDepositLedger fields.
func (_m *SecurityDepositLedger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case securitydepositledger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case securitydepositledger.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case securitydepositledger.FieldLotID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field lot_id", values[i])
			} else if value.Valid {
				_m.LotID = value.Int64
			}
		case securitydepositledger.FieldBucketType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bucket_type", values[i])
			} else if value.Valid {
				_m.BucketType = securitydepositledger.BucketType(value.String)
			}
		case securitydepositledger.FieldEntryType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entry_type", values[i])
			} else if value.Valid {
				_m.EntryType = securitydepositledger.EntryType(value.String)
			}
		case securitydepositledger.FieldDeltaCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delta_cents", values[i])
			} else if value.Valid {
				_m.DeltaCents = value.Int64
			}
		case securitydepositledger.FieldReservedDeltaCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reserved_delta_cents", values[i])
			} else if value.Valid {
				_m.ReservedDeltaCents = value.Int64
			}
		case securitydepositledger.FieldBucketBalanceAfterCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bucket_balance_after_cents", values[i])
			} else if value.Valid {
				_m.BucketBalanceAfterCents = value.Int64
			}
		case securitydepositledger.FieldBucketReservedAfterCents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bucket_reserved_after_cents", values[i])
			} else if value.Valid {
				_m.BucketReservedAfterCents = value.Int64
			}
		case securitydepositledger.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case securitydepositledger.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = new(int64)
				*_m.APIKeyID = value.Int64
			}
		case securitydepositledger.FieldViolationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field violation_id", values[i])
			} else if value.Valid {
				_m.ViolationID = new(int64)
				*_m.ViolationID = value.Int64
			}
		case securitydepositledger.FieldRefundID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refund_id", values[i])
			} else if value.Valid {
				_m.RefundID = new(int64)
				*_m.RefundID = value.Int64
			}
		case securitydepositledger.FieldPaymentOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field payment_order_id", values[i])
			} else if value.Valid {
				_m.PaymentOrderID = new(int64)
				*_m.PaymentOrderID = value.Int64
			}
		case securitydepositledger.FieldOperatorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operator_id", values[i])
			} else if value.Valid {
				_m.OperatorID = new(int64)
				*_m.OperatorID = value.Int64
			}
		case securitydepositledger.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case securitydepositledger.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case securitydepositledger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SecurityDepositLedger.
// This includes values selected through modifiers, order, etc.
func (_m *SecurityDepositLedger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SecurityDepositLedger.
// Note that you need to call SecurityDepositLedger.Unwrap() before calling this method if this SecurityDepositLedger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SecurityDepositLedger) Update() *SecurityDepositLedgerUpdateOne {
	return NewSecurityDepositLedgerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SecurityDepositLedger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SecurityDepositLedger) Unwrap() *SecurityDepositLedger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SecurityDepositLedger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SecurityDepositLedger) String() string {
	var builder strings.Builder
	builder.WriteString("SecurityDepositLedger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("lot_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.LotID))
	builder.WriteString(", ")
	builder.WriteString("bucket_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.BucketType))
	builder.WriteString(", ")
	builder.WriteString("entry_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntryType))
	builder.WriteString(", ")
	builder.WriteString("delta_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeltaCents))
	builder.WriteString(", ")
	builder.WriteString("reserved_delta_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReservedDeltaCents))
	builder.WriteString(", ")
	builder.WriteString("bucket_balance_after_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.BucketBalanceAfterCents))
	builder.WriteString(", ")
	builder.WriteString("bucket_reserved_after_cents=")
	builder.WriteString(fmt.Sprintf("%v", _m.BucketReservedAfterCents))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.APIKeyID; v != nil {
		builder.WriteString("api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ViolationID; v != nil {
		builder.WriteString("violation_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.RefundID; v != nil {
		builder.WriteString("refund_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PaymentOrderID; v != nil {
		builder.WriteString("payment_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OperatorID; v != nil {
		builder.WriteString("operator_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SecurityDepositLedgers is a parsable slice of SecurityDepositLedger.
type SecurityDepositLedgers []*SecurityDepositLedger
