// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/creditgrantevent"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usercreditgranteventtrigger"
	"github.com/Wei-Shaw/sub2api/ent/userlimitedcreditgrant"
)

// UserCreditGrantEventTriggerCreate is the builder for creating a UserCreditGrantEventTrigger entity.
type UserCreditGrantEventTriggerCreate struct {
	config
	mutation *UserCreditGrantEventTriggerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetEventID sets the "event_id" field.
func (_c *UserCreditGrantEventTriggerCreate) SetEventID(v int64) *UserCreditGrantEventTriggerCreate {
	_c.mutation.SetEventID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserCreditGrantEventTriggerCreate) SetUserID(v int64) *UserCreditGrantEventTriggerCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCreditTypeSnapshot sets the "credit_type_snapshot" field.
func (_c *UserCreditGrantEventTriggerCreate) SetCreditTypeSnapshot(v string) *UserCreditGrantEventTriggerCreate {
	_c.mutation.SetCreditTypeSnapshot(v)
	return _c
}

// SetAmountSnapshot sets the "amount_snapshot" field.
func (_c *UserCreditGrantEventTriggerCreate) SetAmountSnapshot(v float64) *UserCreditGrantEventTriggerCreate {
	_c.mutation.SetAmountSnapshot(v)
	return _c
}

// SetValidityDaysSnapshot sets the "validity_days_snapshot" field.
func (_c *UserCreditGrantEventTriggerCreate) SetValidityDaysSnapshot(v int) *UserCreditGrantEventTriggerCreate {
	_c.mutation.SetValidityDaysSnapshot(v)
	return _c
}

// SetNillableValidityDaysSnapshot sets the "validity_days_snapshot" field if the given value is not nil.
func (_c *UserCreditGrantEventTriggerCreate) SetNillableValidityDaysSnapshot(v *int) *UserCreditGrantEventTriggerCreate {
	if v != nil {
		_c.SetValidityDaysSnapshot(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *UserCreditGrantEventTriggerCreate) SetExpiresAt(v time.Time) *UserCreditGrantEventTriggerCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *UserCreditGrantEventTriggerCreate) SetNillableExpiresAt(v *time.Time) *UserCreditGrantEventTriggerCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetBalanceHistoryID sets the "balance_history_id" field.
func (_c *UserCreditGrantEventTriggerCreate) SetBalanceHistoryID(v int64) *UserCreditGrantEventTriggerCreate {
	_c.mutation.SetBalanceHistoryID(v)
	return _c
}

// SetNillableBalanceHistoryID sets the "balance_history_id" field if the given value is not nil.
func (_c *UserCreditGrantEventTriggerCreate) SetNillableBalanceHistoryID(v *int64) *UserCreditGrantEventTriggerCreate {
	if v != nil {
		_c.SetBalanceHistoryID(*v)
	}
	return _c
}

// SetLimitedCreditGrantID sets the "limited_credit_grant_id" field.
func (_c *UserCreditGrantEventTriggerCreate) SetLimitedCreditGrantID(v int64) *UserCreditGrantEventTriggerCreate {
	_c.mutation.SetLimitedCreditGrantID(v)
	return _c
}

// SetNillableLimitedCreditGrantID sets the "limited_credit_grant_id" field if the given value is not nil.
func (_c *UserCreditGrantEventTriggerCreate) SetNillableLimitedCreditGrantID(v *int64) *UserCreditGrantEventTriggerCreate {
	if v != nil {
		_c.SetLimitedCreditGrantID(*v)
	}
	return _c
}

// SetTriggeredAt sets the "triggered_at" field.
func (_c *UserCreditGrantEventTriggerCreate) SetTriggeredAt(v time.Time) *UserCreditGrantEventTriggerCreate {
	_c.mutation.SetTriggeredAt(v)
	return _c
}

// SetNillableTriggeredAt sets the "triggered_at" field if the given value is not nil.
func (_c *UserCreditGrantEventTriggerCreate) SetNillableTriggeredAt(v *time.Time) *UserCreditGrantEventTriggerCreate {
	if v != nil {
		_c.SetTriggeredAt(*v)
	}
	return _c
}

// SetEvent sets the "event" edge to the CreditGrantEvent entity.
func (_c *UserCreditGrantEventTriggerCreate) SetEvent(v *CreditGrantEvent) *UserCreditGrantEventTriggerCreate {
	return _c.SetEventID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserCreditGrantEventTriggerCreate) SetUser(v *User) *UserCreditGrantEventTriggerCreate {
	return _c.SetUserID(v.ID)
}

// SetBalanceHistory sets the "balance_history" edge to the RedeemCode entity.
func (_c *UserCreditGrantEventTriggerCreate) SetBalanceHistory(v *RedeemCode) *UserCreditGrantEventTriggerCreate {
	return _c.SetBalanceHistoryID(v.ID)
}

// SetLimitedCreditGrant sets the "limited_credit_grant" edge to the UserLimitedCreditGrant entity.
func (_c *UserCreditGrantEventTriggerCreate) SetLimitedCreditGrant(v *UserLimitedCreditGrant) *UserCreditGrantEventTriggerCreate {
	return _c.SetLimitedCreditGrantID(v.ID)
}

// Mutation returns the UserCreditGrantEventTriggerMutation object of the builder.
func (_c *UserCreditGrantEventTriggerCreate) Mutation() *UserCreditGrantEventTriggerMutation {
	return _c.mutation
}

// Save creates the UserCreditGrantEventTrigger in the database.
func (_c *UserCreditGrantEventTriggerCreate) Save(ctx context.Context) (*UserCreditGrantEventTrigger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreditGrantEventTriggerCreate) SaveX(ctx context.Context) *UserCreditGrantEventTrigger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreditGrantEventTriggerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreditGrantEventTriggerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreditGrantEventTriggerCreate) defaults() {
	if _, ok := _c.mutation.TriggeredAt(); !ok {
		v := usercreditgranteventtrigger.DefaultTriggeredAt()
		_c.mutation.SetTriggeredAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreditGrantEventTriggerCreate) check() error {
	if _, ok := _c.mutation.EventID(); !ok {
		return &ValidationError{Name: "event_id", err: errors.New(`ent: missing required field "UserCreditGrantEventTrigger.event_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserCreditGrantEventTrigger.user_id"`)}
	}
	if _, ok := _c.mutation.CreditTypeSnapshot(); !ok {
		return &ValidationError{Name: "credit_type_snapshot", err: errors.New(`ent: missing required field "UserCreditGrantEventTrigger.credit_type_snapshot"`)}
	}
	if v, ok := _c.mutation.CreditTypeSnapshot(); ok {
		if err := usercreditgranteventtrigger.CreditTypeSnapshotValidator(v); err != nil {
			return &ValidationError{Name: "credit_type_snapshot", err: fmt.Errorf(`ent: validator failed for field "UserCreditGrantEventTrigger.credit_type_snapshot": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountSnapshot(); !ok {
		return &ValidationError{Name: "amount_snapshot", err: errors.New(`ent: missing required field "UserCreditGrantEventTrigger.amount_snapshot"`)}
	}
	if _, ok := _c.mutation.TriggeredAt(); !ok {
		return &ValidationError{Name: "triggered_at", err: errors.New(`ent: missing required field "UserCreditGrantEventTrigger.triggered_at"`)}
	}
	if len(_c.mutation.EventIDs()) == 0 {
		return &ValidationError{Name: "event", err: errors.New(`ent: missing required edge "UserCreditGrantEventTrigger.event"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserCreditGrantEventTrigger.user"`)}
	}
	return nil
}

func (_c *UserCreditGrantEventTriggerCreate) sqlSave(ctx context.Context) (*UserCreditGrantEventTrigger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreditGrantEventTriggerCreate) createSpec() (*UserCreditGrantEventTrigger, *sqlgraph.CreateSpec) {
	var (
		_node = &UserCreditGrantEventTrigger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usercreditgranteventtrigger.Table, sqlgraph.NewFieldSpec(usercreditgranteventtrigger.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreditTypeSnapshot(); ok {
		_spec.SetField(usercreditgranteventtrigger.FieldCreditTypeSnapshot, field.TypeString, value)
		_node.CreditTypeSnapshot = value
	}
	if value, ok := _c.mutation.AmountSnapshot(); ok {
		_spec.SetField(usercreditgranteventtrigger.FieldAmountSnapshot, field.TypeFloat64, value)
		_node.AmountSnapshot = value
	}
	if value, ok := _c.mutation.ValidityDaysSnapshot(); ok {
		_spec.SetField(usercreditgranteventtrigger.FieldValidityDaysSnapshot, field.TypeInt, value)
		_node.ValidityDaysSnapshot = &value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(usercreditgranteventtrigger.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.TriggeredAt(); ok {
		_spec.SetField(usercreditgranteventtrigger.FieldTriggeredAt, field.TypeTime, value)
		_node.TriggeredAt = value
	}
	if nodes := _c.mutation.EventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usercreditgranteventtrigger.EventTable,
			Columns: []string{usercreditgranteventtrigger.EventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(creditgrantevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EventID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usercreditgranteventtrigger.UserTable,
			Columns: []string{usercreditgranteventtrigger.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.BalanceHistoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usercreditgranteventtrigger.BalanceHistoryTable,
			Columns: []string{usercreditgranteventtrigger.BalanceHistoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BalanceHistoryID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LimitedCreditGrantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usercreditgranteventtrigger.LimitedCreditGrantTable,
			Columns: []string{usercreditgranteventtrigger.LimitedCreditGrantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userlimitedcreditgrant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LimitedCreditGrantID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserCreditGrantEventTrigger.Create().
//		SetEventID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserCreditGrantEventTriggerUpsert) {
//			SetEventID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserCreditGrantEventTriggerCreate) OnConflict(opts ...sql.ConflictOption) *UserCreditGrantEventTriggerUpsertOne {
	_c.conflict = opts
	return &UserCreditGrantEventTriggerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserCreditGrantEventTrigger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserCreditGrantEventTriggerCreate) OnConflictColumns(columns ...string) *UserCreditGrantEventTriggerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserCreditGrantEventTriggerUpsertOne{
		create: _c,
	}
}

type (
	// UserCreditGrantEventTriggerUpsertOne is the builder for "upsert"-ing
	//  one UserCreditGrantEventTrigger node.
	UserCreditGrantEventTriggerUpsertOne struct {
		create *UserCreditGrantEventTriggerCreate
	}

	// UserCreditGrantEventTriggerUpsert is the "OnConflict" setter.
	UserCreditGrantEventTriggerUpsert struct {
		*sql.UpdateSet
	}
)

// SetEventID sets the "event_id" field.
func (u *UserCreditGrantEventTriggerUpsert) SetEventID(v int64) *UserCreditGrantEventTriggerUpsert {
	u.Set(usercreditgranteventtrigger.FieldEventID, v)
	return u
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsert) UpdateEventID() *UserCreditGrantEventTriggerUpsert {
	u.SetExcluded(usercreditgranteventtrigger.FieldEventID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *UserCreditGrantEventTriggerUpsert) SetUserID(v int64) *UserCreditGrantEventTriggerUpsert {
	u.Set(usercreditgranteventtrigger.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsert) UpdateUserID() *UserCreditGrantEventTriggerUpsert {
	u.SetExcluded(usercreditgranteventtrigger.FieldUserID)
	return u
}

// SetCreditTypeSnapshot sets the "credit_type_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsert) SetCreditTypeSnapshot(v string) *UserCreditGrantEventTriggerUpsert {
	u.Set(usercreditgranteventtrigger.FieldCreditTypeSnapshot, v)
	return u
}

// UpdateCreditTypeSnapshot sets the "credit_type_snapshot" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsert) UpdateCreditTypeSnapshot() *UserCreditGrantEventTriggerUpsert {
	u.SetExcluded(usercreditgranteventtrigger.FieldCreditTypeSnapshot)
	return u
}

// SetAmountSnapshot sets the "amount_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsert) SetAmountSnapshot(v float64) *UserCreditGrantEventTriggerUpsert {
	u.Set(usercreditgranteventtrigger.FieldAmountSnapshot, v)
	return u
}

// UpdateAmountSnapshot sets the "amount_snapshot" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsert) UpdateAmountSnapshot() *UserCreditGrantEventTriggerUpsert {
	u.SetExcluded(usercreditgranteventtrigger.FieldAmountSnapshot)
	return u
}

// AddAmountSnapshot adds v to the "amount_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsert) AddAmountSnapshot(v float64) *UserCreditGrantEventTriggerUpsert {
	u.Add(usercreditgranteventtrigger.FieldAmountSnapshot, v)
	return u
}

// SetValidityDaysSnapshot sets the "validity_days_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsert) SetValidityDaysSnapshot(v int) *UserCreditGrantEventTriggerUpsert {
	u.Set(usercreditgranteventtrigger.FieldValidityDaysSnapshot, v)
	return u
}

// UpdateValidityDaysSnapshot sets the "validity_days_snapshot" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsert) UpdateValidityDaysSnapshot() *UserCreditGrantEventTriggerUpsert {
	u.SetExcluded(usercreditgranteventtrigger.FieldValidityDaysSnapshot)
	return u
}

// AddValidityDaysSnapshot adds v to the "validity_days_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsert) AddValidityDaysSnapshot(v int) *UserCreditGrantEventTriggerUpsert {
	u.Add(usercreditgranteventtrigger.FieldValidityDaysSnapshot, v)
	return u
}

// ClearValidityDaysSnapshot clears the value of the "validity_days_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsert) ClearValidityDaysSnapshot() *UserCreditGrantEventTriggerUpsert {
	u.SetNull(usercreditgranteventtrigger.FieldValidityDaysSnapshot)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserCreditGrantEventTriggerUpsert) SetExpiresAt(v time.Time) *UserCreditGrantEventTriggerUpsert {
	u.Set(usercreditgranteventtrigger.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsert) UpdateExpiresAt() *UserCreditGrantEventTriggerUpsert {
	u.SetExcluded(usercreditgranteventtrigger.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserCreditGrantEventTriggerUpsert) ClearExpiresAt() *UserCreditGrantEventTriggerUpsert {
	u.SetNull(usercreditgranteventtrigger.FieldExpiresAt)
	return u
}

// SetBalanceHistoryID sets the "balance_history_id" field.
func (u *UserCreditGrantEventTriggerUpsert) SetBalanceHistoryID(v int64) *UserCreditGrantEventTriggerUpsert {
	u.Set(usercreditgranteventtrigger.FieldBalanceHistoryID, v)
	return u
}

// UpdateBalanceHistoryID sets the "balance_history_id" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsert) UpdateBalanceHistoryID() *UserCreditGrantEventTriggerUpsert {
	u.SetExcluded(usercreditgranteventtrigger.FieldBalanceHistoryID)
	return u
}

// ClearBalanceHistoryID clears the value of the "balance_history_id" field.
func (u *UserCreditGrantEventTriggerUpsert) ClearBalanceHistoryID() *UserCreditGrantEventTriggerUpsert {
	u.SetNull(usercreditgranteventtrigger.FieldBalanceHistoryID)
	return u
}

// SetLimitedCreditGrantID sets the "limited_credit_grant_id" field.
func (u *UserCreditGrantEventTriggerUpsert) SetLimitedCreditGrantID(v int64) *UserCreditGrantEventTriggerUpsert {
	u.Set(usercreditgranteventtrigger.FieldLimitedCreditGrantID, v)
	return u
}

// UpdateLimitedCreditGrantID sets the "limited_credit_grant_id" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsert) UpdateLimitedCreditGrantID() *UserCreditGrantEventTriggerUpsert {
	u.SetExcluded(usercreditgranteventtrigger.FieldLimitedCreditGrantID)
	return u
}

// ClearLimitedCreditGrantID clears the value of the "limited_credit_grant_id" field.
func (u *UserCreditGrantEventTriggerUpsert) ClearLimitedCreditGrantID() *UserCreditGrantEventTriggerUpsert {
	u.SetNull(usercreditgranteventtrigger.FieldLimitedCreditGrantID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserCreditGrantEventTrigger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserCreditGrantEventTriggerUpsertOne) UpdateNewValues() *UserCreditGrantEventTriggerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.TriggeredAt(); exists {
			s.SetIgnore(usercreditgranteventtrigger.FieldTriggeredAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserCreditGrantEventTrigger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserCreditGrantEventTriggerUpsertOne) Ignore() *UserCreditGrantEventTriggerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserCreditGrantEventTriggerUpsertOne) DoNothing() *UserCreditGrantEventTriggerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCreditGrantEventTriggerCreate.OnConflict
// documentation for more info.
func (u *UserCreditGrantEventTriggerUpsertOne) Update(set func(*UserCreditGrantEventTriggerUpsert)) *UserCreditGrantEventTriggerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserCreditGrantEventTriggerUpsert{UpdateSet: update})
	}))
	return u
}

// SetEventID sets the "event_id" field.
func (u *UserCreditGrantEventTriggerUpsertOne) SetEventID(v int64) *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetEventID(v)
	})
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertOne) UpdateEventID() *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateEventID()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserCreditGrantEventTriggerUpsertOne) SetUserID(v int64) *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertOne) UpdateUserID() *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateUserID()
	})
}

// SetCreditTypeSnapshot sets the "credit_type_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsertOne) SetCreditTypeSnapshot(v string) *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetCreditTypeSnapshot(v)
	})
}

// UpdateCreditTypeSnapshot sets the "credit_type_snapshot" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertOne) UpdateCreditTypeSnapshot() *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateCreditTypeSnapshot()
	})
}

// SetAmountSnapshot sets the "amount_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsertOne) SetAmountSnapshot(v float64) *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetAmountSnapshot(v)
	})
}

// AddAmountSnapshot adds v to the "amount_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsertOne) AddAmountSnapshot(v float64) *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.AddAmountSnapshot(v)
	})
}

// UpdateAmountSnapshot sets the "amount_snapshot" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertOne) UpdateAmountSnapshot() *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateAmountSnapshot()
	})
}

// SetValidityDaysSnapshot sets the "validity_days_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsertOne) SetValidityDaysSnapshot(v int) *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetValidityDaysSnapshot(v)
	})
}

// AddValidityDaysSnapshot adds v to the "validity_days_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsertOne) AddValidityDaysSnapshot(v int) *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.AddValidityDaysSnapshot(v)
	})
}

// UpdateValidityDaysSnapshot sets the "validity_days_snapshot" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertOne) UpdateValidityDaysSnapshot() *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateValidityDaysSnapshot()
	})
}

// ClearValidityDaysSnapshot clears the value of the "validity_days_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsertOne) ClearValidityDaysSnapshot() *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.ClearValidityDaysSnapshot()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserCreditGrantEventTriggerUpsertOne) SetExpiresAt(v time.Time) *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertOne) UpdateExpiresAt() *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserCreditGrantEventTriggerUpsertOne) ClearExpiresAt() *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.ClearExpiresAt()
	})
}

// SetBalanceHistoryID sets the "balance_history_id" field.
func (u *UserCreditGrantEventTriggerUpsertOne) SetBalanceHistoryID(v int64) *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetBalanceHistoryID(v)
	})
}

// UpdateBalanceHistoryID sets the "balance_history_id" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertOne) UpdateBalanceHistoryID() *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateBalanceHistoryID()
	})
}

// ClearBalanceHistoryID clears the value of the "balance_history_id" field.
func (u *UserCreditGrantEventTriggerUpsertOne) ClearBalanceHistoryID() *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.ClearBalanceHistoryID()
	})
}

// SetLimitedCreditGrantID sets the "limited_credit_grant_id" field.
func (u *UserCreditGrantEventTriggerUpsertOne) SetLimitedCreditGrantID(v int64) *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetLimitedCreditGrantID(v)
	})
}

// UpdateLimitedCreditGrantID sets the "limited_credit_grant_id" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertOne) UpdateLimitedCreditGrantID() *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateLimitedCreditGrantID()
	})
}

// ClearLimitedCreditGrantID clears the value of the "limited_credit_grant_id" field.
func (u *UserCreditGrantEventTriggerUpsertOne) ClearLimitedCreditGrantID() *UserCreditGrantEventTriggerUpsertOne {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.ClearLimitedCreditGrantID()
	})
}

// Exec executes the query.
func (u *UserCreditGrantEventTriggerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCreditGrantEventTriggerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserCreditGrantEventTriggerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserCreditGrantEventTriggerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserCreditGrantEventTriggerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserCreditGrantEventTriggerCreateBulk is the builder for creating many UserCreditGrantEventTrigger entities in bulk.
type UserCreditGrantEventTriggerCreateBulk struct {
	config
	err      error
	builders []*UserCreditGrantEventTriggerCreate
	conflict []sql.ConflictOption
}

// Save creates the UserCreditGrantEventTrigger entities in the database.
func (_c *UserCreditGrantEventTriggerCreateBulk) Save(ctx context.Context) ([]*UserCreditGrantEventTrigger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserCreditGrantEventTrigger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserCreditGrantEventTriggerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreditGrantEventTriggerCreateBulk) SaveX(ctx context.Context) []*UserCreditGrantEventTrigger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreditGrantEventTriggerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreditGrantEventTriggerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserCreditGrantEventTrigger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserCreditGrantEventTriggerUpsert) {
//			SetEventID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserCreditGrantEventTriggerCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserCreditGrantEventTriggerUpsertBulk {
	_c.conflict = opts
	return &UserCreditGrantEventTriggerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserCreditGrantEventTrigger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserCreditGrantEventTriggerCreateBulk) OnConflictColumns(columns ...string) *UserCreditGrantEventTriggerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserCreditGrantEventTriggerUpsertBulk{
		create: _c,
	}
}

// UserCreditGrantEventTriggerUpsertBulk is the builder for "upsert"-ing
// a bulk of UserCreditGrantEventTrigger nodes.
type UserCreditGrantEventTriggerUpsertBulk struct {
	create *UserCreditGrantEventTriggerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserCreditGrantEventTrigger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserCreditGrantEventTriggerUpsertBulk) UpdateNewValues() *UserCreditGrantEventTriggerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.TriggeredAt(); exists {
				s.SetIgnore(usercreditgranteventtrigger.FieldTriggeredAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserCreditGrantEventTrigger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserCreditGrantEventTriggerUpsertBulk) Ignore() *UserCreditGrantEventTriggerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserCreditGrantEventTriggerUpsertBulk) DoNothing() *UserCreditGrantEventTriggerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCreditGrantEventTriggerCreateBulk.OnConflict
// documentation for more info.
func (u *UserCreditGrantEventTriggerUpsertBulk) Update(set func(*UserCreditGrantEventTriggerUpsert)) *UserCreditGrantEventTriggerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserCreditGrantEventTriggerUpsert{UpdateSet: update})
	}))
	return u
}

// SetEventID sets the "event_id" field.
func (u *UserCreditGrantEventTriggerUpsertBulk) SetEventID(v int64) *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetEventID(v)
	})
}

// UpdateEventID sets the "event_id" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertBulk) UpdateEventID() *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateEventID()
	})
}

// SetUserID sets the "user_id" field.
func (u *UserCreditGrantEventTriggerUpsertBulk) SetUserID(v int64) *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertBulk) UpdateUserID() *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateUserID()
	})
}

// SetCreditTypeSnapshot sets the "credit_type_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsertBulk) SetCreditTypeSnapshot(v string) *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetCreditTypeSnapshot(v)
	})
}

// UpdateCreditTypeSnapshot sets the "credit_type_snapshot" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertBulk) UpdateCreditTypeSnapshot() *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateCreditTypeSnapshot()
	})
}

// SetAmountSnapshot sets the "amount_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsertBulk) SetAmountSnapshot(v float64) *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetAmountSnapshot(v)
	})
}

// AddAmountSnapshot adds v to the "amount_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsertBulk) AddAmountSnapshot(v float64) *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.AddAmountSnapshot(v)
	})
}

// UpdateAmountSnapshot sets the "amount_snapshot" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertBulk) UpdateAmountSnapshot() *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateAmountSnapshot()
	})
}

// SetValidityDaysSnapshot sets the "validity_days_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsertBulk) SetValidityDaysSnapshot(v int) *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetValidityDaysSnapshot(v)
	})
}

// AddValidityDaysSnapshot adds v to the "validity_days_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsertBulk) AddValidityDaysSnapshot(v int) *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.AddValidityDaysSnapshot(v)
	})
}

// UpdateValidityDaysSnapshot sets the "validity_days_snapshot" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertBulk) UpdateValidityDaysSnapshot() *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateValidityDaysSnapshot()
	})
}

// ClearValidityDaysSnapshot clears the value of the "validity_days_snapshot" field.
func (u *UserCreditGrantEventTriggerUpsertBulk) ClearValidityDaysSnapshot() *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.ClearValidityDaysSnapshot()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *UserCreditGrantEventTriggerUpsertBulk) SetExpiresAt(v time.Time) *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertBulk) UpdateExpiresAt() *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *UserCreditGrantEventTriggerUpsertBulk) ClearExpiresAt() *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.ClearExpiresAt()
	})
}

// SetBalanceHistoryID sets the "balance_history_id" field.
func (u *UserCreditGrantEventTriggerUpsertBulk) SetBalanceHistoryID(v int64) *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetBalanceHistoryID(v)
	})
}

// UpdateBalanceHistoryID sets the "balance_history_id" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertBulk) UpdateBalanceHistoryID() *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateBalanceHistoryID()
	})
}

// ClearBalanceHistoryID clears the value of the "balance_history_id" field.
func (u *UserCreditGrantEventTriggerUpsertBulk) ClearBalanceHistoryID() *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.ClearBalanceHistoryID()
	})
}

// SetLimitedCreditGrantID sets the "limited_credit_grant_id" field.
func (u *UserCreditGrantEventTriggerUpsertBulk) SetLimitedCreditGrantID(v int64) *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.SetLimitedCreditGrantID(v)
	})
}

// UpdateLimitedCreditGrantID sets the "limited_credit_grant_id" field to the value that was provided on create.
func (u *UserCreditGrantEventTriggerUpsertBulk) UpdateLimitedCreditGrantID() *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.UpdateLimitedCreditGrantID()
	})
}

// ClearLimitedCreditGrantID clears the value of the "limited_credit_grant_id" field.
func (u *UserCreditGrantEventTriggerUpsertBulk) ClearLimitedCreditGrantID() *UserCreditGrantEventTriggerUpsertBulk {
	return u.Update(func(s *UserCreditGrantEventTriggerUpsert) {
		s.ClearLimitedCreditGrantID()
	})
}

// Exec executes the query.
func (u *UserCreditGrantEventTriggerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserCreditGrantEventTriggerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCreditGrantEventTriggerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserCreditGrantEventTriggerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
