// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/creditgrantevent"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usercreditgranteventtrigger"
	"github.com/Wei-Shaw/sub2api/ent/userlimitedcreditgrant"
)

// UserCreditGrantEventTrigger is the model entity for the UserCreditGrantEventTrigger schema.
type UserCreditGrantEventTrigger struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// EventID holds the value of the "event_id" field.
	EventID int64 `json:"event_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// CreditTypeSnapshot holds the value of the "credit_type_snapshot" field.
	CreditTypeSnapshot string `json:"credit_type_snapshot,omitempty"`
	// AmountSnapshot holds the value of the "amount_snapshot" field.
	AmountSnapshot float64 `json:"amount_snapshot,omitempty"`
	// ValidityDaysSnapshot holds the value of the "validity_days_snapshot" field.
	ValidityDaysSnapshot *int `json:"validity_days_snapshot,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// BalanceHistoryID holds the value of the "balance_history_id" field.
	BalanceHistoryID *int64 `json:"balance_history_id,omitempty"`
	// LimitedCreditGrantID holds the value of the "limited_credit_grant_id" field.
	LimitedCreditGrantID *int64 `json:"limited_credit_grant_id,omitempty"`
	// TriggeredAt holds the value of the "triggered_at" field.
	TriggeredAt time.Time `json:"triggered_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserCreditGrantEventTriggerQuery when eager-loading is set.
	Edges        UserCreditGrantEventTriggerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserCreditGrantEventTriggerEdges holds the relations/edges for other nodes in the graph.
type UserCreditGrantEventTriggerEdges struct {
	// Event holds the value of the event edge.
	Event *CreditGrantEvent `json:"event,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// BalanceHistory holds the value of the balance_history edge.
	BalanceHistory *RedeemCode `json:"balance_history,omitempty"`
	// LimitedCreditGrant holds the value of the limited_credit_grant edge.
	LimitedCreditGrant *UserLimitedCreditGrant `json:"limited_credit_grant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// EventOrErr returns the Event value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserCreditGrantEventTriggerEdges) EventOrErr() (*CreditGrantEvent, error) {
	if e.Event != nil {
		return e.Event, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: creditgrantevent.Label}
	}
	return nil, &NotLoadedError{edge: "event"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserCreditGrantEventTriggerEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// BalanceHistoryOrErr returns the BalanceHistory value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserCreditGrantEventTriggerEdges) BalanceHistoryOrErr() (*RedeemCode, error) {
	if e.BalanceHistory != nil {
		return e.BalanceHistory, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: redeemcode.Label}
	}
	return nil, &NotLoadedError{edge: "balance_history"}
}

// LimitedCreditGrantOrErr returns the LimitedCreditGrant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserCreditGrantEventTriggerEdges) LimitedCreditGrantOrErr() (*UserLimitedCreditGrant, error) {
	if e.LimitedCreditGrant != nil {
		return e.LimitedCreditGrant, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: userlimitedcreditgrant.Label}
	}
	return nil, &NotLoadedError{edge: "limited_credit_grant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserCreditGrantEventTrigger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usercreditgranteventtrigger.FieldAmountSnapshot:
			values[i] = new(sql.NullFloat64)
		case usercreditgranteventtrigger.FieldID, usercreditgranteventtrigger.FieldEventID, usercreditgranteventtrigger.FieldUserID, usercreditgranteventtrigger.FieldValidityDaysSnapshot, usercreditgranteventtrigger.FieldBalanceHistoryID, usercreditgranteventtrigger.FieldLimitedCreditGrantID:
			values[i] = new(sql.NullInt64)
		case usercreditgranteventtrigger.FieldCreditTypeSnapshot:
			values[i] = new(sql.NullString)
		case usercreditgranteventtrigger.FieldExpiresAt, usercreditgranteventtrigger.FieldTriggeredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserCreditGrantEventTrigger fields.
func (_m *UserCreditGrantEventTrigger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usercreditgranteventtrigger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usercreditgranteventtrigger.FieldEventID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value.Valid {
				_m.EventID = value.Int64
			}
		case usercreditgranteventtrigger.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case usercreditgranteventtrigger.FieldCreditTypeSnapshot:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credit_type_snapshot", values[i])
			} else if value.Valid {
				_m.CreditTypeSnapshot = value.String
			}
		case usercreditgranteventtrigger.FieldAmountSnapshot:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_snapshot", values[i])
			} else if value.Valid {
				_m.AmountSnapshot = value.Float64
			}
		case usercreditgranteventtrigger.FieldValidityDaysSnapshot:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field validity_days_snapshot", values[i])
			} else if value.Valid {
				_m.ValidityDaysSnapshot = new(int)
				*_m.ValidityDaysSnapshot = int(value.Int64)
			}
		case usercreditgranteventtrigger.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case usercreditgranteventtrigger.FieldBalanceHistoryID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_history_id", values[i])
			} else if value.Valid {
				_m.BalanceHistoryID = new(int64)
				*_m.BalanceHistoryID = value.Int64
			}
		case usercreditgranteventtrigger.FieldLimitedCreditGrantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field limited_credit_grant_id", values[i])
			} else if value.Valid {
				_m.LimitedCreditGrantID = new(int64)
				*_m.LimitedCreditGrantID = value.Int64
			}
		case usercreditgranteventtrigger.FieldTriggeredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field triggered_at", values[i])
			} else if value.Valid {
				_m.TriggeredAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserCreditGrantEventTrigger.
// This includes values selected through modifiers, order, etc.
func (_m *UserCreditGrantEventTrigger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEvent queries the "event" edge of the UserCreditGrantEventTrigger entity.
func (_m *UserCreditGrantEventTrigger) QueryEvent() *CreditGrantEventQuery {
	return NewUserCreditGrantEventTriggerClient(_m.config).QueryEvent(_m)
}

// QueryUser queries the "user" edge of the UserCreditGrantEventTrigger entity.
func (_m *UserCreditGrantEventTrigger) QueryUser() *UserQuery {
	return NewUserCreditGrantEventTriggerClient(_m.config).QueryUser(_m)
}

// QueryBalanceHistory queries the "balance_history" edge of the UserCreditGrantEventTrigger entity.
func (_m *UserCreditGrantEventTrigger) QueryBalanceHistory() *RedeemCodeQuery {
	return NewUserCreditGrantEventTriggerClient(_m.config).QueryBalanceHistory(_m)
}

// QueryLimitedCreditGrant queries the "limited_credit_grant" edge of the UserCreditGrantEventTrigger entity.
func (_m *UserCreditGrantEventTrigger) QueryLimitedCreditGrant() *UserLimitedCreditGrantQuery {
	return NewUserCreditGrantEventTriggerClient(_m.config).QueryLimitedCreditGrant(_m)
}

// Update returns a builder for updating this UserCreditGrantEventTrigger.
// Note that you need to call UserCreditGrantEventTrigger.Unwrap() before calling this method if this UserCreditGrantEventTrigger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserCreditGrantEventTrigger) Update() *UserCreditGrantEventTriggerUpdateOne {
	return NewUserCreditGrantEventTriggerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserCreditGrantEventTrigger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserCreditGrantEventTrigger) Unwrap() *UserCreditGrantEventTrigger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserCreditGrantEventTrigger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserCreditGrantEventTrigger) String() string {
	var builder strings.Builder
	builder.WriteString("UserCreditGrantEventTrigger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("credit_type_snapshot=")
	builder.WriteString(_m.CreditTypeSnapshot)
	builder.WriteString(", ")
	builder.WriteString("amount_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountSnapshot))
	builder.WriteString(", ")
	if v := _m.ValidityDaysSnapshot; v != nil {
		builder.WriteString("validity_days_snapshot=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.BalanceHistoryID; v != nil {
		builder.WriteString("balance_history_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LimitedCreditGrantID; v != nil {
		builder.WriteString("limited_credit_grant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("triggered_at=")
	builder.WriteString(_m.TriggeredAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserCreditGrantEventTriggers is a parsable slice of UserCreditGrantEventTrigger.
type UserCreditGrantEventTriggers []*UserCreditGrantEventTrigger
