export default {
  credits: {
      title: 'Credit Management', description: 'Manage permanent and time-limited user credits', search: 'Search email, username, or user ID', user: 'User', permanent: 'Permanent credit', limited: 'Limited credit', total: 'Total credit', items: 'items', manage: 'Manage', empty: 'No users', frozen: 'Frozen', add: 'Add', subtract: 'Deduct', balanceHistory: 'Permanent credit ledger', noHistory: 'No funding records', limitedDetails: 'Limited credit details', activeOnly: 'Active', allRecords: 'All records', createLimited: 'Add limited credit', limitedItem: 'Limited credit #{id}', adjustUsed: 'Adjust used credit', adjustLimit: 'Adjust upper limit', adjustExpiry: 'Adjust expiry', reset: 'Reset', revoke: 'Revoke', ledger: 'View ledger', creditUnit: 'credit', dayUnit: 'days', amount: 'Amount', days: 'Validity days', notes: 'Reason (optional)', balancePreview: 'Permanent credit: ${before} → ${after}', createPreview: 'Grant ${amount} for {days} days', limitPreview: 'Upper limit: ${before} → ${after}', usedPreview: 'Used credit: ${before} → ${after}', expiryPreview: 'New expiry: {date}', resetPreview: 'Used credit will reset to 0. Expiry stays unchanged.', resetWithExpiryPreview: 'Used credit will reset to 0. Expiry restarts for {days} days.', revokePreview: 'The remaining credit becomes unavailable immediately.',
      actions: { none: '', 'balance-add': 'Add permanent credit', 'balance-subtract': 'Deduct permanent credit', 'limited-create': 'Add limited credit', 'limited-used': 'Adjust used credit', 'limited-limit': 'Adjust upper limit', 'limited-expiry': 'Adjust limited credit expiry', 'limited-reset': 'Reset limited credit', 'limited-revoke': 'Revoke limited credit' },
      sources: { redeem_code: 'Redeem code', default_user_setting: 'Default setting', recharge_bonus: 'Recharge bonus', admin_manual: 'Admin grant' },
      statuses: { active: 'Active', depleted: 'Depleted', expired: 'Expired', revoked: 'Revoked' },
      events: { grant: 'Grant', consume: 'Usage charge', reserve: 'Reserve', capture: 'Capture', release: 'Release', admin_increase_limit: 'Admin increased upper limit', admin_decrease_limit: 'Admin decreased upper limit', admin_increase_used: 'Admin increased used credit', admin_decrease_used: 'Admin decreased used credit', admin_extend_expiry: 'Admin extended expiry', admin_reduce_expiry: 'Admin reduced expiry', admin_reset: 'Admin reset', admin_revoke: 'Admin revoke' },
      balanceEvents: { balance: 'Redeem or recharge', admin_balance: 'Admin adjustment', affiliate_balance: 'Affiliate transfer' }
  }
}
