// Code generated by ent, DO NOT EDIT.

package recurringcredittask

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the recurringcredittask type in the database.
	Label = "recurring_credit_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAdminNotes holds the string denoting the admin_notes field in the database.
	FieldAdminNotes = "admin_notes"
	// FieldScheduleType holds the string denoting the schedule_type field in the database.
	FieldScheduleType = "schedule_type"
	// FieldDayOfMonth holds the string denoting the day_of_month field in the database.
	FieldDayOfMonth = "day_of_month"
	// FieldDayOfWeek holds the string denoting the day_of_week field in the database.
	FieldDayOfWeek = "day_of_week"
	// FieldLocalTime holds the string denoting the local_time field in the database.
	FieldLocalTime = "local_time"
	// FieldTimezone holds the string denoting the timezone field in the database.
	FieldTimezone = "timezone"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldValidityDays holds the string denoting the validity_days field in the database.
	FieldValidityDays = "validity_days"
	// FieldExecutionMode holds the string denoting the execution_mode field in the database.
	FieldExecutionMode = "execution_mode"
	// FieldRemainingRuns holds the string denoting the remaining_runs field in the database.
	FieldRemainingRuns = "remaining_runs"
	// FieldSkipCount holds the string denoting the skip_count field in the database.
	FieldSkipCount = "skip_count"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldNextRunAt holds the string denoting the next_run_at field in the database.
	FieldNextRunAt = "next_run_at"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldCreatedByAdminID holds the string denoting the created_by_admin_id field in the database.
	FieldCreatedByAdminID = "created_by_admin_id"
	// FieldCreatedByAdminEmail holds the string denoting the created_by_admin_email field in the database.
	FieldCreatedByAdminEmail = "created_by_admin_email"
	// FieldUpdatedByAdminID holds the string denoting the updated_by_admin_id field in the database.
	FieldUpdatedByAdminID = "updated_by_admin_id"
	// FieldUpdatedByAdminEmail holds the string denoting the updated_by_admin_email field in the database.
	FieldUpdatedByAdminEmail = "updated_by_admin_email"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the recurringcredittask in the database.
	Table = "recurring_credit_tasks"
)

// Columns holds all SQL columns for recurringcredittask fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldAdminNotes,
	FieldScheduleType,
	FieldDayOfMonth,
	FieldDayOfWeek,
	FieldLocalTime,
	FieldTimezone,
	FieldAmount,
	FieldValidityDays,
	FieldExecutionMode,
	FieldRemainingRuns,
	FieldSkipCount,
	FieldStatus,
	FieldNextRunAt,
	FieldVersion,
	FieldIdempotencyKey,
	FieldCreatedByAdminID,
	FieldCreatedByAdminEmail,
	FieldUpdatedByAdminID,
	FieldUpdatedByAdminEmail,
	FieldDeletedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultAdminNotes holds the default value on creation for the "admin_notes" field.
	DefaultAdminNotes string
	// ScheduleTypeValidator is a validator for the "schedule_type" field. It is called by the builders before save.
	ScheduleTypeValidator func(string) error
	// LocalTimeValidator is a validator for the "local_time" field. It is called by the builders before save.
	LocalTimeValidator func(string) error
	// TimezoneValidator is a validator for the "timezone" field. It is called by the builders before save.
	TimezoneValidator func(string) error
	// ExecutionModeValidator is a validator for the "execution_mode" field. It is called by the builders before save.
	ExecutionModeValidator func(string) error
	// DefaultSkipCount holds the default value on creation for the "skip_count" field.
	DefaultSkipCount int
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// DefaultCreatedByAdminEmail holds the default value on creation for the "created_by_admin_email" field.
	DefaultCreatedByAdminEmail string
	// CreatedByAdminEmailValidator is a validator for the "created_by_admin_email" field. It is called by the builders before save.
	CreatedByAdminEmailValidator func(string) error
	// DefaultUpdatedByAdminEmail holds the default value on creation for the "updated_by_admin_email" field.
	DefaultUpdatedByAdminEmail string
	// UpdatedByAdminEmailValidator is a validator for the "updated_by_admin_email" field. It is called by the builders before save.
	UpdatedByAdminEmailValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the RecurringCreditTask queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAdminNotes orders the results by the admin_notes field.
func ByAdminNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminNotes, opts...).ToFunc()
}

// ByScheduleType orders the results by the schedule_type field.
func ByScheduleType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScheduleType, opts...).ToFunc()
}

// ByDayOfMonth orders the results by the day_of_month field.
func ByDayOfMonth(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDayOfMonth, opts...).ToFunc()
}

// ByDayOfWeek orders the results by the day_of_week field.
func ByDayOfWeek(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDayOfWeek, opts...).ToFunc()
}

// ByLocalTime orders the results by the local_time field.
func ByLocalTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalTime, opts...).ToFunc()
}

// ByTimezone orders the results by the timezone field.
func ByTimezone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimezone, opts...).ToFunc()
}

// ByAmount orders the results by the amount field.
func ByAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAmount, opts...).ToFunc()
}

// ByValidityDays orders the results by the validity_days field.
func ByValidityDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidityDays, opts...).ToFunc()
}

// ByExecutionMode orders the results by the execution_mode field.
func ByExecutionMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecutionMode, opts...).ToFunc()
}

// ByRemainingRuns orders the results by the remaining_runs field.
func ByRemainingRuns(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemainingRuns, opts...).ToFunc()
}

// BySkipCount orders the results by the skip_count field.
func BySkipCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkipCount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByNextRunAt orders the results by the next_run_at field.
func ByNextRunAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRunAt, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByCreatedByAdminID orders the results by the created_by_admin_id field.
func ByCreatedByAdminID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByAdminID, opts...).ToFunc()
}

// ByCreatedByAdminEmail orders the results by the created_by_admin_email field.
func ByCreatedByAdminEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedByAdminEmail, opts...).ToFunc()
}

// ByUpdatedByAdminID orders the results by the updated_by_admin_id field.
func ByUpdatedByAdminID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedByAdminID, opts...).ToFunc()
}

// ByUpdatedByAdminEmail orders the results by the updated_by_admin_email field.
func ByUpdatedByAdminEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedByAdminEmail, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
