// Code generated by ent, DO NOT EDIT.

package userlimitedcreditgrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldUserID, v))
}

// SourceType applies equality check predicate on the "source_type" field. It's identical to SourceTypeEQ.
func SourceType(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldSourceType, v))
}

// SourceID applies equality check predicate on the "source_id" field. It's identical to SourceIDEQ.
func SourceID(v int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldSourceID, v))
}

// InitialAmount applies equality check predicate on the "initial_amount" field. It's identical to InitialAmountEQ.
func InitialAmount(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldInitialAmount, v))
}

// UsedAmount applies equality check predicate on the "used_amount" field. It's identical to UsedAmountEQ.
func UsedAmount(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldUsedAmount, v))
}

// FrozenAmount applies equality check predicate on the "frozen_amount" field. It's identical to FrozenAmountEQ.
func FrozenAmount(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldFrozenAmount, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldStatus, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldNotes, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNotIn(FieldUserID, vs...))
}

// SourceTypeEQ applies the EQ predicate on the "source_type" field.
func SourceTypeEQ(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldSourceType, v))
}

// SourceTypeNEQ applies the NEQ predicate on the "source_type" field.
func SourceTypeNEQ(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNEQ(FieldSourceType, v))
}

// SourceTypeIn applies the In predicate on the "source_type" field.
func SourceTypeIn(vs ...string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldIn(FieldSourceType, vs...))
}

// SourceTypeNotIn applies the NotIn predicate on the "source_type" field.
func SourceTypeNotIn(vs ...string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNotIn(FieldSourceType, vs...))
}

// SourceTypeGT applies the GT predicate on the "source_type" field.
func SourceTypeGT(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGT(FieldSourceType, v))
}

// SourceTypeGTE applies the GTE predicate on the "source_type" field.
func SourceTypeGTE(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGTE(FieldSourceType, v))
}

// SourceTypeLT applies the LT predicate on the "source_type" field.
func SourceTypeLT(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLT(FieldSourceType, v))
}

// SourceTypeLTE applies the LTE predicate on the "source_type" field.
func SourceTypeLTE(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLTE(FieldSourceType, v))
}

// SourceTypeContains applies the Contains predicate on the "source_type" field.
func SourceTypeContains(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldContains(FieldSourceType, v))
}

// SourceTypeHasPrefix applies the HasPrefix predicate on the "source_type" field.
func SourceTypeHasPrefix(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldHasPrefix(FieldSourceType, v))
}

// SourceTypeHasSuffix applies the HasSuffix predicate on the "source_type" field.
func SourceTypeHasSuffix(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldHasSuffix(FieldSourceType, v))
}

// SourceTypeEqualFold applies the EqualFold predicate on the "source_type" field.
func SourceTypeEqualFold(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEqualFold(FieldSourceType, v))
}

// SourceTypeContainsFold applies the ContainsFold predicate on the "source_type" field.
func SourceTypeContainsFold(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldContainsFold(FieldSourceType, v))
}

// SourceIDEQ applies the EQ predicate on the "source_id" field.
func SourceIDEQ(v int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldSourceID, v))
}

// SourceIDNEQ applies the NEQ predicate on the "source_id" field.
func SourceIDNEQ(v int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNEQ(FieldSourceID, v))
}

// SourceIDIn applies the In predicate on the "source_id" field.
func SourceIDIn(vs ...int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldIn(FieldSourceID, vs...))
}

// SourceIDNotIn applies the NotIn predicate on the "source_id" field.
func SourceIDNotIn(vs ...int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNotIn(FieldSourceID, vs...))
}

// SourceIDGT applies the GT predicate on the "source_id" field.
func SourceIDGT(v int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGT(FieldSourceID, v))
}

// SourceIDGTE applies the GTE predicate on the "source_id" field.
func SourceIDGTE(v int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGTE(FieldSourceID, v))
}

// SourceIDLT applies the LT predicate on the "source_id" field.
func SourceIDLT(v int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLT(FieldSourceID, v))
}

// SourceIDLTE applies the LTE predicate on the "source_id" field.
func SourceIDLTE(v int64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLTE(FieldSourceID, v))
}

// SourceIDIsNil applies the IsNil predicate on the "source_id" field.
func SourceIDIsNil() predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldIsNull(FieldSourceID))
}

// SourceIDNotNil applies the NotNil predicate on the "source_id" field.
func SourceIDNotNil() predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNotNull(FieldSourceID))
}

// InitialAmountEQ applies the EQ predicate on the "initial_amount" field.
func InitialAmountEQ(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldInitialAmount, v))
}

// InitialAmountNEQ applies the NEQ predicate on the "initial_amount" field.
func InitialAmountNEQ(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNEQ(FieldInitialAmount, v))
}

// InitialAmountIn applies the In predicate on the "initial_amount" field.
func InitialAmountIn(vs ...float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldIn(FieldInitialAmount, vs...))
}

// InitialAmountNotIn applies the NotIn predicate on the "initial_amount" field.
func InitialAmountNotIn(vs ...float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNotIn(FieldInitialAmount, vs...))
}

// InitialAmountGT applies the GT predicate on the "initial_amount" field.
func InitialAmountGT(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGT(FieldInitialAmount, v))
}

// InitialAmountGTE applies the GTE predicate on the "initial_amount" field.
func InitialAmountGTE(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGTE(FieldInitialAmount, v))
}

// InitialAmountLT applies the LT predicate on the "initial_amount" field.
func InitialAmountLT(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLT(FieldInitialAmount, v))
}

// InitialAmountLTE applies the LTE predicate on the "initial_amount" field.
func InitialAmountLTE(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLTE(FieldInitialAmount, v))
}

// UsedAmountEQ applies the EQ predicate on the "used_amount" field.
func UsedAmountEQ(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldUsedAmount, v))
}

// UsedAmountNEQ applies the NEQ predicate on the "used_amount" field.
func UsedAmountNEQ(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNEQ(FieldUsedAmount, v))
}

// UsedAmountIn applies the In predicate on the "used_amount" field.
func UsedAmountIn(vs ...float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldIn(FieldUsedAmount, vs...))
}

// UsedAmountNotIn applies the NotIn predicate on the "used_amount" field.
func UsedAmountNotIn(vs ...float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNotIn(FieldUsedAmount, vs...))
}

// UsedAmountGT applies the GT predicate on the "used_amount" field.
func UsedAmountGT(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGT(FieldUsedAmount, v))
}

// UsedAmountGTE applies the GTE predicate on the "used_amount" field.
func UsedAmountGTE(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGTE(FieldUsedAmount, v))
}

// UsedAmountLT applies the LT predicate on the "used_amount" field.
func UsedAmountLT(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLT(FieldUsedAmount, v))
}

// UsedAmountLTE applies the LTE predicate on the "used_amount" field.
func UsedAmountLTE(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLTE(FieldUsedAmount, v))
}

// FrozenAmountEQ applies the EQ predicate on the "frozen_amount" field.
func FrozenAmountEQ(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldFrozenAmount, v))
}

// FrozenAmountNEQ applies the NEQ predicate on the "frozen_amount" field.
func FrozenAmountNEQ(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNEQ(FieldFrozenAmount, v))
}

// FrozenAmountIn applies the In predicate on the "frozen_amount" field.
func FrozenAmountIn(vs ...float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldIn(FieldFrozenAmount, vs...))
}

// FrozenAmountNotIn applies the NotIn predicate on the "frozen_amount" field.
func FrozenAmountNotIn(vs ...float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNotIn(FieldFrozenAmount, vs...))
}

// FrozenAmountGT applies the GT predicate on the "frozen_amount" field.
func FrozenAmountGT(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGT(FieldFrozenAmount, v))
}

// FrozenAmountGTE applies the GTE predicate on the "frozen_amount" field.
func FrozenAmountGTE(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGTE(FieldFrozenAmount, v))
}

// FrozenAmountLT applies the LT predicate on the "frozen_amount" field.
func FrozenAmountLT(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLT(FieldFrozenAmount, v))
}

// FrozenAmountLTE applies the LTE predicate on the "frozen_amount" field.
func FrozenAmountLTE(v float64) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLTE(FieldFrozenAmount, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLTE(FieldExpiresAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldContainsFold(FieldStatus, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldContainsFold(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLedgerEntries applies the HasEdge predicate on the "ledger_entries" edge.
func HasLedgerEntries() predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LedgerEntriesTable, LedgerEntriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedgerEntriesWith applies the HasEdge predicate on the "ledger_entries" edge with a given conditions (other predicates).
func HasLedgerEntriesWith(preds ...predicate.UserLimitedCreditLedger) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(func(s *sql.Selector) {
		step := newLedgerEntriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserLimitedCreditGrant) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserLimitedCreditGrant) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserLimitedCreditGrant) predicate.UserLimitedCreditGrant {
	return predicate.UserLimitedCreditGrant(sql.NotPredicates(p))
}
